### ISSUE TITLE
Add description of repository

### ISSUE THREAD

**Issue by wpank** [trustwallet/assets#1]
At the top it what be nice to know what kind of assets these are without context of going to the the developer documentation or the folders. We should add a description of what this repository is at the top, plus tags so it can easily be found.

**Comment by cyberience** [comment]
Developer Documentation is a dead link

**Comment by vikmeup** [comment]
@cyberience thanks! Fixed now, take a look: https://developer.trustwallet.com/add_new_asset

**Comment by vikmeup** [comment]
@kolya182 can you work on this issue? currently it's not intuitive to go to developer docs to figure out how to add, there is should be a way to easily learn how to add it on this repo.

**Comment by kolya182** [comment]
> @kolya182 can you work on this issue? currently it's not intuitive to go to developer docs to figure out how to add, there is should be a way to easily learn how to add it on this repo.

What is developer docs than for ?. It is just redundant to keep repo description in tho places, isn't?.

**Comment by vikmeup** [comment]
@kolya182 developer docs are official, github repo is internal and focused on providing quick access and description what it does.

Learn from others and see how they handle it.

**Comment by makcoin933** [comment]
![makcoi](https://user-images.githubusercontent.com/62119979/76689897-f336be00-65f7-11ea-87cd-25813f8cd37f.png)

**Comment by makcoin933** [comment]
![makcoi](https://user-images.githubusercontent.com/62119979/76689898-fb8ef900-65f7-11ea-93cd-db46421ff8f9.png)
