### ISSUE TITLE
PR price too high

### ISSUE THREAD

**Issue by sputniky** [trustwallet/assets#10079]
Hello.

I think the Pull Requests price is far too high. One year ago 1000 TWT were about $17. now it is $400 each PR. This is too heavy for any coin or community. I think you should adapt the number of TWT needed so that it corresponds to $20 or $30 for the day. people would just send the amount of TWT needed to reach that USD amount.

Else any other solution would be good, but this is far too expensive just for a PR, and destroys the community oriented database. You would still earn a lot with $20 per PR, like one year ago.
Is it possible to adapt this please?

**Comment by zachzwei** [comment]
This is being enforced as to prevent spam and fake projects in submitting PRs. This fee is waived if the project is legit and has an active community.
