### ISSUE TITLE
Accept BEP-20 Payments

### ISSUE THREAD

**Issue by winlambo** [trustwallet/assets#10120]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it takes me longer than 10 minutes to figure out how to pay for something.
A lot of projects that use this repo/service come from Binance Smart Chain (BEP-20), however they can only pay on Binance Chain (BEP-2)

**Describe the solution you'd like**
The TWT team should set up a payment method to accept payments on Binance Smart Chain (BEP-20).

**Describe alternatives you've considered**
I tried bridging from BEP-20 to BEP-2 using binance.org/en/bridge but it doesn't accept TWT.
Even then, the process to get Binance Chain Wallet, add network, figure out how to bridge, etc. is very cumbersome and takes more than 10 minutes.

**Additional context**
Ideally there would be a BEP-20 address that I can send 1000 TWT to for processing fee.

Thank you!

**Comment by Cryptocool1** [comment]
> **Is your feature request related to a problem? Please describe.**
> I'm always frustrated when it takes me longer than 10 minutes to figure out how to pay for something.
> A lot of projects that use this repo/service come from Binance Smart Chain (BEP-20), however they can only pay on Binance Chain (BEP-2)
> 
> **Describe the solution you'd like**
> The TWT team should set up a payment method to accept payments on Binance Smart Chain (BEP-20).
> 
> **Describe alternatives you've considered**
> I tried bridging from BEP-20 to BEP-2 using binance.org/en/bridge but it doesn't accept TWT.
> Even then, the process to get Binance Chain Wallet, add network, figure out how to bridge, etc. is very cumbersome and takes more than 10 minutes.
> 
> **Additional context**
> Ideally there would be a BEP-20 address that I can send 1000 TWT to for processing fee.
> 
> Thank you!

Hello,
you can swap your bep20 tokens to bep2. it's not a problem )

**Comment by winlambo** [comment]
It's a feature request. It would be nice to keep it open to see how many +1's it gets...

I've been trying for 24 hours to figure out how to swap and bridge and pay.

Most of the projects that pay for this service ($300+) each are coming from BEP-20.
I'm not saying you have to do it, but it is worth considering, since everything is automated.

Just something to think about.
