### ISSUE TITLE
Improve links format

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/assets#10140]
**Is your feature request related to a problem? Please describe.**

```
{
    "name": "Trust Wallet Token",
    "website": "https://trustwallet.com",
    "description": "Utility token to increase adoption of cryptocurrency.",
    "links": [
        {
            "name": "source_code",
            "url": "https://github.com/trustwallet/"
        },
        {
            "name": "whitepaper",
            "url": "https://github.com/trustwallet/"
        },
        {
            "name": "explorer",
            "url": "https://explorer.binance.org/asset/TWT-8C2"
        },
        {
            "name": "research",
            "url": "https://research.binance.com/en/projects/trustwallet"
        },
        {
            "name": "twitter",
            "url": "https://twitter.com/trustwalletapp"
        }
    ],
    "type": "BEP2",
    "symbol": "TWT",
    "decimals": 8,
    "status": "active",
    "id": "TWT-8C2"
}
```

**Supported types:**

- github (instead of source_code)
- whitepaper
- explorer
- twitter
- facebook
- reddit
- telegram
- community

**Required:**
- website
- explorer

**Comment by catenocrypt** [comment]
Update: fields to be included:

Valid link types:
- github, url https://github.com/  (from of source_code field)
- whitepaper, optional, url freeform (from of whitepaper)
- twitter, url https://twitter.com/  (from of socials/Twitter)
- telegram, url https://t.me/ open discussion  (from of socials/Telegram)
- telegram_news, url https://t.me/ read-only announcement channel
- medium, url contains 'medium' (from socials/medium)
- discord, url https://discord.com/
- reddit, url https://reddit.com/
- facebook, url https://facebook.com/
- youtube, url https://youtube.com/
- coinmarketcap, url https://coinmarketcap.com/
- coingecko, url https://coingecko.com/
- blog, url freeform, other than medium, url, etc.; socials/blog)
- forum, url freeform (forum web, from of community)
- docs, url freeform
- source_code, other than github, url  (from source_code)

Notes:
- website is being left outside as it is
- explorer is being left outside as it is for now
- some notable not supported fields:   linkedin, tiktok, instagram

**Comment by catenocrypt** [comment]
#10639 merged, all info is duplicated under links.
Socials section are still kept (to be removed soon), new assets should have both or none.
