### ISSUE TITLE
Script does not check if address is checksum

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/assets#1017]
https://github.com/trustwallet/assets/pull/1016

**Comment by sidko** [comment]
I see 4 of these addresses seem to have failed validation: 
```
0xa4f9cec920ca520a7feb2c3a63050e08967bc111
0xb19977b23b40d59254b8f5a0bdb67076b4fa0bc6
0xcf0425a35f1fa900bb347cb996d3094d1df3cd48
0xe6710e0cda178f3d921f456902707b0d4c4a332b
```
Should I re-submit them with the right checksum format and the same image?

**Comment by vikmeup** [comment]
@sidko yes please, use `git mv` to checksum those.

we will add script to CI those values

**Comment by sidko** [comment]
@vikmeup just a heads up, the diff in git may not show this correctly because the change is only for the folder case. Also, I used `git mv` twice because git doesn't like me changing only the case of the folder (see https://stackoverflow.com/questions/1094269/whats-the-purpose-of-git-mv).

**Comment by kolya182** [comment]
> @vikmeup just a heads up, the diff in git may not show this correctly because the change is only for the folder case. Also, I used `git mv` twice because git doesn't like me changing only the case of the folder (see https://stackoverflow.com/questions/1094269/whats-the-purpose-of-git-mv).

`npm run checksum-erc20` script already there

**Comment by vikmeup** [comment]
you need to run this automatically and commit changes on PR
