### ISSUE TITLE
Please reopen PR 6870 (I am unable to reply to TW staff)

### ISSUE THREAD

**Issue by iamjustaspore** [trustwallet/assets#10200]
Hello. @Cryptocool1 commented on our PR but I am unable to reply to it (the bot deletes comments).  Please reopen the PR.

_Originally posted by @Cryptocool1 in https://github.com/trustwallet/assets/pull/6870#issuecomment-860201200_

**Comment by cryptomanz** [comment]
this PR merged)

**Comment by cryptomanz** [comment]
you can type here

**Comment by iamjustaspore** [comment]
OK thanks.  That comment was in response to the name change mentioned in the tweet.  The project's name is now Spore (no longer Spore Finance).

**Comment by Cryptocool1** [comment]
> OK thanks. That comment was in response to the name change mentioned in the tweet. The project's name is now Spore (no longer Spore Finance). The change was made only a week after the PR was merged.

please create new PR for updating.

**Comment by Cryptocool1** [comment]
> OK thanks. That comment was in response to the name change mentioned in the tweet. The project's name is now Spore (no longer Spore Finance). The change was made only a week after the PR was merged.

https://github.com/trustwallet/assets/pull/10215 
renamed)

**Comment by iamjustaspore** [comment]
@Cryptocool1 Thank you!  Could you update the links and description as well?
`
{
    "name": "Spore",
    "website": "https://spore.earth/",
    "description": "Spore is an international movement of artists and blockchain developers who are building an ecosystem that connects content creators with users, using open standards for fair distribution. The ecosystem, which includes an NFT platform, is fueled by SPORE, a deflationary, globally-accepted currency available on Avalanche and Binance Smart Chain. The token seamlessly connects two massive blockchains and their user bases with the first of its kind Avalanche-BSC bridge, developed in-house by Spore.",
    "socials": [
        {
            "name": "Twitter",
            "url": "https://twitter.com/sporeproject"
        },
        {
            "name": "Reddit",
            "url": "https://reddit.com/r/sporeproject"
        },
        {
            "name": "Medium",
            "url": "https://sporeproject.medium.com/"
        },
        {
            "name": "Discord",
            "url": "https://discord.gg/xRrArCTG9Q"
        },
        {
            "name": "Facebook",
            "url": "https://www.facebook.com/sporeproject"
        },
        {
            "name": "Instagram",
            "url": "https://www.instagram.com/sporeproject"
        },
        {
            "name": "TikTok",
            "url": "https://www.tiktok.com/@sporeproject"
        },
        {
            "name": "YouTube",
            "url": "https://www.youtube.com/sporeproject"
        },
        {
            "name": "Telegram",
            "url": "https://t.me/sporefinanceofficial"
        },
        {
            "name": "GitHub",
            "url": "https://github.com/sporeproject"
        }
    ],
    "explorer": "https://bscscan.com/token/0x33A3d962955A3862C8093D1273344719f03cA17C",
    "type": "BEP20",
    "symbol": "SPORE",
    "decimals": 9,
    "status": "active",
    "id": "0x33A3d962955A3862C8093D1273344719f03cA17C"
}`

**Comment by Cryptocool1** [comment]
> @Cryptocool1 Thank you! Could you update the links and description as well?
> 
> ` { "name": "Spore", "website": "https://spore.earth/", "description": "Spore is an international movement of artists and blockchain developers who are building an ecosystem that connects content creators with users, using open standards for fair distribution. The ecosystem, which includes an NFT platform, is fueled by SPORE, a deflationary, globally-accepted currency available on Avalanche and Binance Smart Chain. The token seamlessly connects two massive blockchains and their user bases with the first of its kind Avalanche-BSC bridge, developed in-house by Spore.", "socials": [ { "name": "Twitter", "url": "https://twitter.com/sporeproject" }, { "name": "Reddit", "url": "https://reddit.com/r/sporeproject" }, { "name": "Medium", "url": "https://sporeproject.medium.com/" }, { "name": "Discord", "url": "https://discord.gg/xRrArCTG9Q" }, { "name": "Facebook", "url": "https://www.facebook.com/sporeproject" }, { "name": "Instagram", "url": "https://www.instagram.com/sporeproject" }, { "name": "TikTok", "url": "https://www.tiktok.com/@sporeproject" }, { "name": "YouTube", "url": "https://www.youtube.com/sporeproject" }, { "name": "Telegram", "url": "https://t.me/sporefinanceofficial" }, { "name": "GitHub", "url": "https://github.com/sporeproject" } ], "explorer": "https://bscscan.com/token/0x33A3d962955A3862C8093D1273344719f03cA17C", "type": "BEP20", "symbol": "SPORE", "decimals": 9, "status": "active", "id": "0x33A3d962955A3862C8093D1273344719f03cA17C" }`

done.
have a great day!
