### ISSUE TITLE
BSC NFT Collection

### ISSUE THREAD

**Issue by projectznft** [trustwallet/assets#10457]
Hi,

Currently, the **"Collectibles"** tab is only available for ethereum network.
How long would it take before BSC network is added? I've saw from [Brace Yourself, Binance Smart Chain NFTs Are Coming!](https://trustwallet.com/blog/brace-yourself-binance-smartchain-nfts) that Trustwallet will support BEP721. It was published Feb, and 4 months has passed. Any updates please?

Regards,

**Comment by vikmeup** [comment]
Are you on iOS or Android devices? it's should be available on both
