### ISSUE TITLE
Question with Submitting a Token Logo 

### ISSUE THREAD

**Issue by KayAlbertus** [trustwallet/assets#10718]
Good Day Team

Can You Please Tell Me Why

https://bscscan.com/token/0x4a080377f83d669d7bb83b3184a8a5e61b500608

is not a accepted ExplorerURL?

When Trying to Submit a Token Logo Following the below 

https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by Cryptocool1** [comment]
As we told you in the previous PR: "This is a BEp20 token, correct folder is blockchains/smartchain/assets"
