### ISSUE TITLE
All balance missing 

### ISSUE THREAD

**Issue by Veigatron** [trustwallet/assets#10784]
Hello , yesterday i bought some doryswap and made LPS dory BNB and Started farming , today i woke up and i had zero balance  in my farming pool , i send screen shots to prove o was farming , and today with zero balance please help me please !!!

 
![Screenshot_2021-06-26-16-07-39-379_com wallet crypto trustapp](https://user-images.githubusercontent.com/86532115/123522048-b8547e80-d6b2-11eb-8871-5ab31c9bd82d.jpg)
![Screenshot_2021-06-25-22-40-08-406_com wallet crypto trustapp](https://user-images.githubusercontent.com/86532115/123522049-bbe80580-d6b2-11eb-9d0a-ef269e22d9ce.jpg)
![Screenshot_2021-06-25-22-27-28-450_com wallet crypto trustapp](https://user-images.githubusercontent.com/86532115/123522052-c1455000-d6b2-11eb-9e02-773c442bef91.jpg)

**Comment by hanhungsoo** [comment]
> 안녕하세요, 어제 저는 doryswap을 사서 LPS dory BNB를 만들고 농사를 시작했습니다. 오늘 저는 깨어 났고 제 농장 풀에 균형이 없었습니다. 스크린 샷을 보내서 o가 농사를하고 있음을 증명했습니다. 오늘 제발 균형이없는 상태에서 제발 도와주세요! !!
> 
> ![Screenshot_2021-06-26-16-07-39-379_com 지갑 암호화 트러스트 앱](https://user-images.githubusercontent.com/86532115/123522048-b8547e80-d6b2-11eb-8871-5ab31c9bd82d.jpg)
> ![Screenshot_2021-06-25-22-40-08-406_com 지갑 암호화 트러스트 앱](https://user-images.githubusercontent.com/86532115/123522049-bbe80580-d6b2-11eb-9d0a-ef269e22d9ce.jpg)
> ![Screenshot_2021-06-25-22-27-28-450_com 지갑 암호화 트러스트 앱](https://user-images.githubusercontent.com/86532115/123522052-c1455000-d6b2-11eb-9e02-773c442bef91.jpg)
