### ISSUE TITLE
Logo on trust wallet too small.

### ISSUE THREAD

**Issue by debtfreebsc** [trustwallet/assets#10830]
**Is your feature request related to a problem? Please describe.**
Debt Free token logo on trust wallet is too small. Would be great if it could fit whole background.
Current trust wallet logo: 
![FAA49CE2-EBB2-457B-A9B0-88EEADD8D93E](https://user-images.githubusercontent.com/86198093/123552761-6cdeb680-d72c-11eb-84b1-0edc0b7a2211.jpeg)

**Describe the solution you'd like**
Here is a link to to debt free logo to maybe fit entire screen background. 

![](http://www.simpleimageresizer.com/_uploads/photos/852d4d70/FC6627AF-CA8A-441F-9E58-124046A792E8_256x256.png)

**Comment by Cryptocool1** [comment]
please create new PR for updating the logo
