### ISSUE TITLE
Add Chipee Logo and info.json to trustwallet

### ISSUE THREAD

**Issue by SageHeritage** [trustwallet/assets#11087]
## How can we help ?

![logo](https://user-images.githubusercontent.com/84780990/124277979-97ba7780-db3d-11eb-92ea-a6a17d779d81.png)

info.json

{
    "name": "Chipee",
    "type": "BEP20",
    "symbol": "CHIPEE",
    "decimals": 8,
    "website": "https://chipee.com/",
    "description": "Chipee The Animal Sancuary Help Token for animals both Small & Giant.",
    "explorer": "https://bscscan.com/token/0x7e745779940f6c578B121B4329265D995B03F6bf",
    "status": "active",
    "id": "0x7e745779940f6c578B121B4329265D995B03F6bf"
}

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
