### ISSUE TITLE
Asset trust wallet unable to create pull request due to website does not exist

### ISSUE THREAD

**Issue by flokishibainu** [trustwallet/assets#11127]
**Describe the bug**
Asset trust wallet unable to create pull request due to this error "Website does not exist, status 404, url https://www.flokishibainu.com"

anyway to fix this? and due to my earlier closed pull request whenever i pull the folder it doesnt work advice thank you

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by flokishibainu** [comment]
hello i cant create with https://assets.trustwallet.com, it keep giving me website error 404 website not found

can i create new one with the old ways but right now I cant do it without the old keep appearing in the pull request is there a way to remove and delete the pull request so i can start a new one?

**Comment by Cryptocool1** [comment]
It’s ok, this error is caused by bot

**Comment by flokishibainu** [comment]
Ok so I can proceed on this one https://github.com/trustwallet/assets/pull/11128 ?
