### ISSUE TITLE
Please Remove TXH [TradeX Token] on TrustWallet with TXH 

### ISSUE THREAD

**Issue by TradeX-Protocol** [trustwallet/assets#1130]
![0x5432c580e34f590f4dd901b825ddeb92e905e826](https://user-images.githubusercontent.com/58638083/73612355-ff9b2480-4610-11ea-95c2-2818709ea5d4.png)
Please Remove TXH [TradeX Token] on TrustWallet with TXH logo image

Contract Address: 0x8dc9947b6662485252e49b04f2e445100ab5804a
Total Supply : 500,000,000 TXH
Token Name : TradeX Token
Symbol : TXH
Decimals : 18

Need new one 

Add TXH [TradeX Token] on TrustWallet with TXH logo image

Contract Address: 0x5432c580e34f590f4dd901b825ddeb92e905e826
Total Supply : 500,000,000 TXH
Token Name : TradeX Token
Symbol : TXH
Decimals : 18

**Comment by TradeX-Protocol** [comment]
Add TXH [TradeX Token] on TrustWallet with TXH logo image

Contract Address: 0x5432c580e34f590f4dd901b825ddeb92e905e826
Total Supply : 500,000,000 TXH
Token Name : TradeX Token
Symbol : TXH
Decimals : 18

![0x5432c580e34f590f4dd901b825ddeb92e905e826](https://user-images.githubusercontent.com/58638083/73612373-34a77700-4611-11ea-92bf-5d243c0f49b4.png)

**Comment by kolya182** [comment]
Reason ?

**Comment by TradeX-Protocol** [comment]
Because my previous contract wallet lost sir ..no pass key or backup main wallet .

**Comment by TradeX-Protocol** [comment]
new token wallet coin store backup wallet

**Comment by TradeX-Protocol** [comment]
please add this token with same png file 
Add TXH [TradeX Token] on TrustWallet with TXH logo image

Contract Address: 0x5432c580e34f590f4dd901b825ddeb92e905e826
Total Supply : 500,000,000 TXH
Token Name : TradeX Token
Symbol : TXH
Decimals : 18
![0x5432c580e34f590f4dd901b825ddeb92e905e826](https://user-images.githubusercontent.com/58638083/73673816-51a57e00-46d5-11ea-9d1e-6b65008358ac.png)
