### ISSUE TITLE
**PR Summary**

### ISSUE THREAD

**Issue by ParabolicMindz** [trustwallet/assets#11396]
**PR Summary** 
File not allowed: 0x4cda4daad72340b28925ccd6fa78db631267d3c4/info.json. Please revert it. 
File not allowed: 0x4cda4daad72340b28925ccd6fa78db631267d3c4/logo.png. Please revert it.

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/11394#issuecomment-874482370_

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
