### ISSUE TITLE
If a PR is auto-closed, and it had non-empty description, the closing message overrides the description.

### ISSUE THREAD

**Issue by ny030897** [trustwallet/assets#11514]
If a PR is auto-closed, and it had non-empty description, the closing message overrides the description.
Not a big deal, a little annoying only when PR is reopened.

__Originally posted by @catenocrypt in https://github.com/trustwallet/assets/issues/6888__

**Comment by Cryptocool1** [comment]
what is the problem?

**Comment by Claudio060320** [comment]
> If a PR is auto-closed, and it had non-empty description, the closing message overrides the description. Not a big deal, a little annoying only when PR is reopened.
> 
> **Originally posted by @catenocrypt in #6888**
