### ISSUE TITLE
sadbaby LOGO

### ISSUE THREAD

**Issue by sadbabytoken** [trustwallet/assets#11603]
@@ -0,0 +1,10 @@
     " name " : " Sadbaby Token " ,
     " web sitesi " : " https://sadbaby.org/ " ,
     " description " : " SadBaby Token, öncelikle SMA hastası bebeklerimizin dünyayı hala sevdikleri bir yer olarak yaşamalarını sağlamak için oluşturulmuş bir bağış jetonudur " ,
     " kaşif " : " https://bscscan.com/token/0x4e84e47bbabd89835e2e9569d69a6d465de38122 " ,
     " type " : " BEP20 " ,
     " sembol " : " SDBY " ,
     " ondalık sayılar " : 9 ,
     " durum " : " aktif " ,
     " id " : " 0x4e84e47bbabd89835e2e9569d69a6d465de38122 "
 }

**Comment by sadbabytoken** [comment]
![Uploading 8E02FCE5-9383-48FE-9EA7-61D05CE49E15.png…]()

**Comment by sadbabytoken** [comment]
" name " : " Sadbaby Token " , 
" web sitesi " : " https://sadbaby.org/ , 
" description " : " SadBaby Token, öncelikle SMA hastası bebeklerimizin arabası hala sevdikleri bir yer olarak yaşamalarını sağlamak için bir bağış bağışladı " jetonudur, 
" kaşif " : " https://bscscan.com/token/0x4e84e47bbabd89835e2e9569d69a6d465de38122 " , 
" type " : " BEP20 " , 
" , 
" jetonudur " : " SDBY " , " ondalık say " : 9 , 
" durum " : " aktif " , 
" id " : " 0x4e84e47bbabd89835e2e9569d69a6d465de38122 " 
}

**Comment by sadbabytoken** [comment]
BAF76951-BF2D-47EA-A236-379674FF1BC0.png
Dosyaya git

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
