### ISSUE TITLE
Adai price and information not showing up

### ISSUE THREAD

**Issue by Iguins** [trustwallet/assets#11695]
**Describe the bug**
A clear and concise description of what the bug is
The Asset token adai available on
https://coinmarketcap.com/currencies/aave-dai/
Does not show up price and market information. 

The token info seems to be accurate in the asset info. 

**To Reproduce**
Add the the token in trust wallet

**Expected behavior**
Price and market data should be available
**Screenshots**

**Desktop (please complete the following information):**
Android, not tested on IOS

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vikmeup** [comment]
Pricing show up for the new AAVE DAI token, but not for the old one, I think this is expected behavior. 

<img width="736" alt="Screen Shot 2021-07-20 at 2 15 40 PM" src="https://user-images.githubusercontent.com/1641795/126396419-a722bd5a-8031-4b8b-b59f-24117b1440c8.png">

**Comment by vikmeup** [comment]
- Added current price to AAVE DAI token.

The issue is actually on CoinMarketCap, they currently only have association with https://etherscan.io/address/0xfC1E690f61EFd961294b3e1Ce3313fBD8aa4f85d and not with the new token v2: https://etherscan.io/address/0x028171bca77440897b824ca71d1c56cac55b68a3
