### ISSUE TITLE
Please ReOpen #11570

### ISSUE THREAD

**Issue by SafeBagDev** [trustwallet/assets#11714]
## How can we help ?

UNCX/UNCL have been listed for over a year on TW, we questioned if the holder threshold also applies to bridge tokens, since  the bot sees them as a different token.
As users of UNCX/UNCL we'd love to see them in our TWs in all chains.

For more details please check #11570

@catenocrypt, @Cryptocool1 Thank you!

**Comment by Cryptocool1** [comment]
reopened

**Comment by SafeBagDev** [comment]
@Cryptocool1 the bot insta closed it again...
Can you please get that bot under control so we can PAY?
