### ISSUE TITLE
Please Re Open #11439

### ISSUE THREAD

**Issue by Pierre764** [trustwallet/assets#11747]
We now solved the following issue:

__❌ Low token circulation: no. of holders is 12, below limit of 2500__

As we have 4K+ Holders and over13K Transactions.

Please Re Open ticket #11439 for us to make payment and get our logo up.

Many thanks!

**Comment by cryptomanz** [comment]
hello,
how did you get them?

**Comment by Pierre764** [comment]
Hello Cryptomanz!

We are listed on pancake swap mate.
When we submitted last week, it was 2 hours before IDO. I was not aware of the requirements you mentioned, my apologies for this.
Please check our bscscan address if you'd like:
https://bscscan.com/token/0xeac9873291ddaca754ea5642114151f3035c67a2

Thanks!
