### ISSUE TITLE
Please reopen PR #11035

### ISSUE THREAD

**Issue by NFTGameTheory** [trustwallet/assets#11779]
Please reopen PR #11035 and sort your bot out please lol. Third time closed in a very short amount of time. 
I have paid the PR fee but you will have to confirm as the bot doesn't seem to be having it.
Thanks.

**Comment by Cryptocool1** [comment]
Payment was not found by the bot; could you provide TXID or date for checking?

**Comment by NFTGameTheory** [comment]
Sure. TXID:
56752EE888C966FDAEB696AEC228A97AE00778D668B96ED9D7DBE326C0586D0E
