### ISSUE TITLE
Terra tokens are missing info.json

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/assets#11788]
There are some Terra tokens in the repo:
https://github.com/trustwallet/assets/tree/master/blockchains/terra/assets
and they are missing info.json files (the only assets left without info.json files).
I was not able to find info about these tokens on the explorer.
Minimal info needed: Name, Symbol, Decimals.

@YunSuk-Yeo, could you help us here?  (https://github.com/trustwallet/assets/pull/975)

**Comment by MelnikovAG** [comment]
Leave your wallet [prof wear your ](home one day)

**Comment by vikmeup** [comment]
Added
