### ISSUE TITLE
Remove old DEEZNUTS logo and contract (urgent)

### ISSUE THREAD

**Issue by deeznutscoin** [trustwallet/assets#11797]
**Describe the bug**
We need our old token contract and logo deprecated, deactivated, and removed from your application so users don't continue to get confused. 

**To Reproduce**
Here is the folder for the old token: https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x01921A94e68F8D54F33C5D6f71d6664C35e33269

The contract address for the old token is 0x01921A94e68F8D54F33C5D6f71d6664C35e33269. Please remove it from your repository/deprecate it.

**Comment by Cryptocool1** [comment]
<img width="853" alt="Screen Shot 2021-07-04 at 2 09 40 AM" src="https://user-images.githubusercontent.com/82717856/125736267-ce766bdc-c2d5-41f2-8fb1-c7df8f30bb5a.png">
