### ISSUE TITLE
Please reopen #11439 for us to make payment

### ISSUE THREAD

**Issue by Pierre764** [trustwallet/assets#11809]
Hello cryptomanz!

Thanks for reopening the request yesterday, but it seems that the bot closed it right away before we were able to make a payment for the fee asked.
Please reopen and I'll pay the fee right away.

Many thanks!

Pierre

**Comment by Cryptocool1** [comment]
provide me a number of PR please

**Comment by Pierre764** [comment]
Same as in the topic line ;)

Add DCB token info and logo  PR #11439

Thanks!
