### ISSUE TITLE
Your Bot is out of control!

### ISSUE THREAD

**Issue by SafeBagDev** [trustwallet/assets#11832]
## How can we help ?
# Get that thing under control!

In fact, this whole asset thing is getting out of control.
You ask a question and only get payment reminders by the bot.
You ask to reopen a PR so you can **PAY** and the bot closes it again, instantly.

I wonder how long until projects stop using the TW Assets or create their own, like Bogged did.
And that's my issue.

**Comment by Cryptocool1** [comment]
please create new PR
