### ISSUE TITLE
Trustwallet displaying OLD BOG price incorrectly, by displaying the price of the NEW BOG contract, leading to confusion and scams involving OLD BOG.

### ISSUE THREAD

**Issue by lukebogtools** [trustwallet/assets#12175]
**Describe the bug**
The OLD BOG token ( 0xd7b729ef857aa773f47d37088a1181bb3fbf0099 ), which is worthless, is displaying the price of the New BOG token in Trustwallet

**To Reproduce**
1. Add OLD BOG to your wallet 0xd7b729ef857aa773f47d37088a1181bb3fbf0099 
2. See price displayed as $0.57~ instead of $0.0000001~

**Expected behavior**
The correct price of OLD BOG should be displayed, or no price at all.

**Additional context**
This is leading to several instances of people being paid in OLD BOG and being scammed.

This is also leading to a high number of support requests regarding the old token.

**Comment by cryptomanz** [comment]
OLD BOG status  "abandoned" now

**Comment by cryptomanz** [comment]
https://github.com/trustwallet/assets/pull/12199
