### ISSUE TITLE
Tegridy Tokens (TGDY) Logo Missing

### ISSUE THREAD

**Issue by UWHELOMECH** [trustwallet/assets#12195]
The logo for BEP20 asset Tegridy Token (TGDY, address 0x4763D54b2c22Ac684A7bf7d144e19322593598E3) is missing.  See attached for needed image.

![tt-01](https://user-images.githubusercontent.com/87918955/126888178-c3107288-ed63-40fc-8926-35be11c1db8c.png)

**Comment by cryptomanz** [comment]
can you send me the number of PR ?

**Comment by UWHELOMECH** [comment]
#12218

My apologies.  I recently was added to our coin's administrative team and I was under the impression that the json and logo were submitted along with the fee.  I can see that the PR was not created previously and I just created it (#12218).  I will verify against our transaction history that the fee was paid unless you are able to verify.  Thanks much.

**Comment by cryptomanz** [comment]
send me PR where you paid the fee
