### ISSUE TITLE
Activity Feed

### ISSUE THREAD

**Issue by cliffblank** [trustwallet/assets#1223]
An activity feed pulling in all recent activity associated with an ETH address would be helpful. A similar feature can be found in the Opera mobile app.

![photo_2020-02-12_00-08-56](https://user-images.githubusercontent.com/11810965/74315328-0bcb6400-4d2c-11ea-937d-e81a7298acae.jpg)

**Comment by kolya182** [comment]
Currently under ETH we show all related https://developer.trustwallet.com/blockatlas/transaction-format#contract-call transfers coin, but one difference in case it's token transfer we show it as Smart Contract Call and  https://developer.trustwallet.com/blockatlas/transaction-format#contract-call
If you would like make PR improving display exact direction and asset type was transferred open PR here https://github.com/trustwallet/blockatlas/
