### ISSUE TITLE
Payment made for #11439 DCB token

### ISSUE THREAD

**Issue by Pierre764** [trustwallet/assets#12246]
Hi there,

I made payment when PR was open this morning, the bot has not acknowledged payment yet but shut the PR.
Is this normal?

Please go to PR #11439 and changed payment label, I put screenshot of payment before bot closed the PR ;)

Many thanks !
Pierre!

**Comment by Cryptocool1** [comment]
Payment was not found by the bot; could you provide TXID or date for checking?

**Comment by Pierre764** [comment]
Hi there !

Sure thing.
As per screenshot on PR, TXID
is 6E0C0BB8325C63CE0C9C54F1F358DF6D1DC8DB6DDCE607725F7447E6203657EF

Explorer link is below:
https://binance.mintscan.io/txs/6E0C0BB8325C63CE0C9C54F1F358DF6D1DC8DB6DDCE607725F7447E6203657EF

Thanks for your help!

Pierre.
