### ISSUE TITLE
PR #11439 What next? 

### ISSUE THREAD

**Issue by Pierre764** [trustwallet/assets#12281]
Hello team !

We paid the fee to get our Token listed (PR #11439), answered the questions asked via email, but I can not see our logo and token info up on Trust/pancakeswap.

Please advise what's next

Thanks ;)

**Comment by Cryptocool1** [comment]
Can you answer the questions I asked there? 
thanks

**Comment by Pierre764** [comment]
I did via email.

When I try on the PR, the bot deletes my comment.
I put it here as well

Hi there,

1- DCB, our utility token, will be used on the Decubate platform for
various purposes such as governance rights, staking, and rewards to the
community for their feedback on the different startups we will offer.
See full utility here: https://decubate.gitbook.io/documentation/the-token

2- Please see full token allocation and distribution, including vesting
schedule, at the below link:
https://decubate.gitbook.io/documentation/tokenomics

3- Token Presale took place as follows:

Seed Sale %0.0055 – 50M Tokens (5%)  May-June 2021

Strategic Sale $0.009 - 50M Tokens (5%)  May-June 2021

Private Sale $0.012 - 26.7M tokens (2.67%)  May-June 2021

Public sale: $0.015 – 23.3M tokens (2.33%) 6th of July 2021


4- The token is currently only listed on a DEX, PancakeSwap. See token info
at the following link:
https://pancakeswap.info/token/0xeac9873291ddaca754ea5642114151f3035c67a2


5- Our smart is currently being audited by Haechi labs and the outcome will
be released within the next 2 weeks.

Many thanks!
