### ISSUE TITLE
Hacker Space HKS

### ISSUE THREAD

**Issue by HackerSpaceToken** [trustwallet/assets#12353]
Hello, how is everything? I would like to open a new request for the logo on (Hacker Space), we have updated the update on our website (hackerspace.digital), we have released 2 games since we last spoke... Can I still transfer 250 TWT?

https://bscscan.com/token/0xb8a3c3ca48b49a6868a144517a4c02f3347d7645

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 5000 holder addresses and 10000 transactions, in order to filter out scam tokens.
the fee is 2000 TWT now
