### ISSUE TITLE
Can not create a pull request to add token on Polygon Network to Trust Wallet

### ISSUE THREAD

**Issue by CPIErocket** [trustwallet/assets#12573]
**Describe the bug**
Can not create a pull request to add token on Polygon Network to Trust Wallet

**To Reproduce**
1. Go to https://assets.trustwallet.com/
2. Fork https://github.com/trustwallet/assets repo
3. Input all valid data
4. Click "Check" => See error as image 01 
5. Try "Create Pull Request" => See error as image 02

**Expected behavior**
No error to when check and create pull request add token on Polygon Network to Trust Wallet

**Screenshots**
![image](https://user-images.githubusercontent.com/88322933/128587480-51ddbb40-8e12-4ac3-8556-11e342c463e7.png)

![image](https://user-images.githubusercontent.com/88322933/128587844-5bfaa60c-2fab-487d-a966-5a95fdcec983.png)

**Comment by catenocrypt** [comment]
Fixed, validated, it works now.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/13562139/128838554-e740fead-b13f-4fdb-9500-2fabe71000c8.png">
