### ISSUE TITLE
Last requirement met for DCB Logo & Info to go live  PR #11439

### ISSUE THREAD

**Issue by Pierre764** [trustwallet/assets#12622]
Hello there, 

For PR #11439 , audit contract was missing, we got it this weekend. Please find it attached below.

Kindly get our logo up at your earliest convenience!

Many thanks :)

[[HAECHI AUDIT] Decubate Smart Contract Audit Report.pdf](https://github.com/trustwallet/assets/files/6953465/HAECHI.AUDIT.Decubate.Smart.Contract.Audit.Report.pdf)

**Comment by Cryptocool1** [comment]
Reopened
