### ISSUE TITLE
Contract for token RVP is not verified

### ISSUE THREAD

**Issue by AcapSLP** [trustwallet/assets#12659]
https://etherscan.io/address/0x17EF75AA22dD5f6C2763b8304Ab24f40eE54D48a#code

you can see that the token contract is not verified and could be a dangerous or malicious token.

the token has been added to the trustwallet tokenlist in error.

https://github.com/trustwallet/assets/tree/70056b81da52b23929d7f23dbe147016dcdde168/blockchains/ethereum/assets/0x17EF75AA22dD5f6C2763b8304Ab24f40eE54D48a

please remove the token from the list to restore trust in the trustwallet standards.

**Comment by Cryptocool1** [comment]
thank you for information.
will get in touch with creator. if there is no response from them, we will remove the token.
