### ISSUE TITLE
Who is funded my balances others lost trust wallet?

### ISSUE THREAD

**Issue by Maxusz666** [trustwallet/assets#12883]

**Comment by Maxusz666** [comment]
![oce_dataset.jpg](https://user-images.githubusercontent.com/45395035/130017295-a84a1b1c-e4d1-44b7-8490- [ ] -8b4eb9680cfd.jpg)

**Comment by James22-crypto** [comment]
Contact their automated service on here so they can confirm your account with the issue and resolve this issue for you immediately.
 https://forms.gle/VbTkY8mBQqMme6Ja6
