### ISSUE TITLE
USDT (in Solana) logo is wrong

### ISSUE THREAD

**Issue by jikkujose** [trustwallet/assets#12968]
USDT logo (in Solana network) is inconsistent with other logos. It doesn't look legitimate.

![Solana/USDT](https://raw.githubusercontent.com/trustwallet/assets/1fcb2784892bdb14a5820eac87bf22008e7322b0/blockchains/solana/assets/Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB/logo.png)

USDT logo in BSC is consistent:

![BSC/USDT](https://github.com/trustwallet/assets/blob/1fcb2784892bdb14a5820eac87bf22008e7322b0/blockchains/binance/assets/USDT-6D8/logo.png?raw=true)

I can send a PR if you want?

**Comment by Cryptocool1** [comment]
thanks. will fix it
