### ISSUE TITLE
Oops! We couldn`t find Tezos Account in the Explorer and Lost the balance

### ISSUE THREAD

**Issue by abraham-yusuf** [trustwallet/assets#12967]
whats the problem with my tezos account? why cannot find? i have 4 more tezos in balance but now is cannot check in explorer and lost the balance

[In Explorer](https://blockchair.com/search?q=tz1PtYhbLoQEzEK7JXtC46H2Q1tsn3smR9nG)

**Smartphone:**
 - Device: [Oppo]
 - OS: [Android 11]
 - Trust Wallet Version [1.30.24]

before
![photo_2021-08-21_18-19-02](https://user-images.githubusercontent.com/76843145/130320129-bcd1ba3d-bd81-4475-97c3-e6d5a659585c.jpg)

after -1 hours
![photo_2021-08-21_18-17-52](https://user-images.githubusercontent.com/76843145/130320103-021d7797-5e67-4ce7-b715-c78f092fd328.jpg)

**Comment by abraham-yusuf** [comment]
my wallet is : `tz1PtYhbLoQEzEK7JXtC46H2Q1tsn3smR9nG`

**Comment by vikmeup** [comment]
There was an issue with Tezos node: https://giganode.io, things should work fine now.
