### ISSUE TITLE
GOLD FINCH TOKEN PRICE LIVE SHOW PLZ

### ISSUE THREAD

**Issue by BDCC18** [trustwallet/assets#13032]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BDCC18** [comment]
HOW LONG TIME GFCC LIVE RATE SHOW IN TRUST WALLET?????
HELOO TEAM PLZ UPDATE GOLD FINCH CRYPO CURRENCY [GFCC TOKEN] LIVE PRICE SHOW PLZ

PLZ APROVEL LIVE RATE IN TRUST WALLET GFCC LIVE PRICE/MARKET TRADING LIVE PLZ

COIN PAPRIKA LIVE TRADING LINK
https://coinpaprika.com/coin/gfcc-gold-finch-crypto-currency/

https://coinsbit.io/trade/GFCC_BTC

https://coinsbit.io/trade/GFCC_USDT

**Comment by BDCC18** [comment]
HOW LONG TIME GFCC LIVE RATE SHOW IN TRUST WALLET?????
HELOO TEAM PLZ UPDATE GOLD FINCH CRYPO CURRENCY [GFCC TOKEN] LIVE PRICE SHOW PLZ

PLZ APROVEL LIVE RATE IN TRUST WALLET GFCC LIVE PRICE/MARKET TRADING LIVE PLZ

COIN PAPRIKA LIVE TRADING LINK
https://coinpaprika.com/coin/gfcc-gold-finch-crypto-currency/

https://coinsbit.io/trade/GFCC_BTC

https://coinsbit.io/trade/GFCC_USDT

**Comment by cryptomanz** [comment]
https://community.trustwallet.com/t/where-does-trust-wallet-get-coin-pricing-data-from/333
