### ISSUE TITLE
Add Binemon token (BIN)

### ISSUE THREAD

**Issue by BinemonTech** [trustwallet/assets#13201]
Hello,

I want to add the information and logo of Binemon - symbol "BIN" - BEP20 token on Trust wallet
![256](https://user-images.githubusercontent.com/89788513/131356280-23f2794a-04a6-4d5a-906a-33ceeab65f6e.png)

**Comment by Cryptocool1** [comment]
Hello,
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
