### ISSUE TITLE
New logo is not updated in App

### ISSUE THREAD

**Issue by shawnying** [trustwallet/assets#13234]
Dear Admin,

I uploaded a new logo of MultiVAC Token (bep20), Symbol MTV. 
The PR is merged 5 days ago. But in my iPhone TrustWallet App, the logo is still not updated.
We have three versions of tokens, bep2, bep20, and erc20. Bep20 is inconsistent with the logos of other versions, so I want to change it to the same as the other two.
Could you please help me?

Asset folder:
assets/blockchains/smartchain/assets/0x8aa688AB789d1848d131C65D98CEAA8875D97eF1/

App version:
iOS,  version 6.4(643)

**Comment by Cryptocool1** [comment]
![0F75F1CB-3484-479E-B093-D43A33AC5EC1](https://user-images.githubusercontent.com/82717856/131513670-a51b231e-fba8-41ea-b3c6-0e9c7bce474e.jpeg)
they seem the same

**Comment by shawnying** [comment]
![telegram-cloud-photo-size-5-6156782649440578945-y](https://user-images.githubusercontent.com/1488196/131518614-89873842-4070-4ff5-9f50-30a14935970f.jpg)
Thank you for your reply
I guess it may be caused by the local cache. Is there any way to refresh this logo on my own phone?

**Comment by hewigovens** [comment]
@shawnying try this:
1. backup your wallets
2. delete and re-install Trust
