### ISSUE TITLE
Transfer fee with the wrong memo

### ISSUE THREAD

**Issue by SMLNFT** [trustwallet/assets#13314]
## How can we help ?

I transferred fee with the wrong memo by mistake, can you refund to me or handle manually if  I am able to prove this transaction made by me.

**Comment by Cryptocool1** [comment]
could you provide TXID

**Comment by SMLNFT** [comment]
Thanks. https://explorer.binance.org/tx/E2A6BDB6369D775A710DD2B0A17D0A2014091AA63BBB76F2BF9ED0837051BCA6

**Comment by cryptomanz** [comment]
what is the number of your PR. will put the paid label

**Comment by SMLNFT** [comment]
The old PR number is #13314, but it was closed due to `Low token circulation`. 

I intend to promote our project to satisfy all criteria first,  then pull a new PR.

If I don't need to pull a new PR, please put the paid label. Otherwise, I'll be back and put the new PR here.

Thanks.

**Comment by SMLNFT** [comment]
The old PR number is #13314, but it was closed due to `Low token circulation`. 

I intend to promote our project to satisfy all criteria first,  then pull a new PR.

If I don't need to pull a new PR, please put the paid label. Otherwise, I'll be back and put the new PR here.

Thanks.

**Comment by SMLNFT** [comment]
> what is the number of your PR? will put the paid label



> The old PR number is #13309, but it was closed due to `Low token circulation`.
> 
> I intend to promote our project to satisfy all criteria first, then pull a new PR.
> 
> If I don't need to pull a new PR, please put the paid label. Otherwise, I'll be back and put the new PR number here.
> 
> Thanks.

@cryptomanz It's a pity we could not satisfy all criteria despite our best efforts. The asset is extremely important to us and our team, could you return the asset back to us, please.
