### ISSUE TITLE
logo update on uniswap

### ISSUE THREAD

**Issue by gusiri** [trustwallet/assets#13476]
## How can we help ?

Hello, our PR for a new logo was merged 2 days ago, but uniswap still shows the old logo.

Do you have any idea how long does it usually take for a new logo to show up on uniswap?

Thank you so much.

**Comment by Cryptocool1** [comment]
what is the number of PR?

**Comment by gusiri** [comment]
@Cryptocool1 
Thank you for your quick response. 
This is the PR: https://github.com/trustwallet/assets/pull/13428

**Comment by vikmeup** [comment]
https://github.com/trustwallet/assets/pull/13428#issuecomment-921322332
