### ISSUE TITLE
I can't submit answer to Add Nafty (BEP20) #13659 

### ISSUE THREAD

**Issue by nafty2021** [trustwallet/assets#13755]
in Add Nafty (BEP20) #13659 I  have to submit further details which I. can't do since my. response keeps being deleted by a. bot

**Comment by Cryptocool1** [comment]
Please put the answers here

**Comment by catenocrypt** [comment]
Only the submitter and Trust Wallet maintainers can comment on PRs, to prevent scam comments.
PR #13659 was created by user `naftytoken2021`. If anyone could comment on it, that could be mis-used, so we don't allow.  Sorry, we don't have a way to know if `nafty2021` is the same person, it is a different Github user.  Please use original account.
