### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by nafty2021** [trustwallet/assets#13751]
Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
 • How is the token being distributed? Are you conducting an airdrop?
 • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
 • Is the token listed on a centralized/decentralized exchange?
 • Is a Smart Contract audit completed? Where can we find this information?

_Originally posted by @cryptomanz in https://github.com/trustwallet/assets/issues/13659#issuecomment-922107852_

my responses keep getting deleted by a bot???

**Comment by cryptomanz** [comment]
Try to leave a comment again.
https://github.com/trustwallet/assets/pull/13659#issuecomment-922107852

**Comment by nafty2021** [comment]
same thing keeps happening, these are our answers which keep getting deleted


> Hello,
> Can your answer some questions?
> • What is the purpose of this token? How will it benefit Trust Wallet users?

A: it's a utility token with 4 working platforms 
> • How is the token being distributed? Are you conducting an airdrop?
A: we had a presale on DX sale in July

> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Presale on DXsale
> • Is the token listed on a centralized/decentralized exchange?
Yes on. Bitmart, Hotbit and PancakeSwap
> • Is a Smart Contract audit completed? Where can we find this information?
A: Yes by solidity finance, here's the report: https://solidity.finance/audits/NAFTYv3/

**Comment by nafty2021** [comment]
I tried and it keeps getting deleted by a bot … 

Hello,
Can your answer some questions?
• What is the purpose of this token? How will it benefit Trust Wallet users?
A: it's a utility token with 4 working platforms

• How is the token being distributed? Are you conducting an airdrop?
A: we had a presale on DX sale in July
• Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
Presale on DXsale
• Is the token listed on a centralized/decentralized exchange?
Yes on. Bitmart, Hotbit and PancakeSwap
• Is a Smart Contract audit completed? Where can we find this information?
A: Yes by solidity finance, here's the report: https://solidity.finance/audits/NAFTYv3/
