### ISSUE TITLE
“There’s still white space around the logo, the logo we provided is flush to the edges, it doesnt look like it was updated"

### ISSUE THREAD

**Issue by ash-greninja-poke** [trustwallet/assets#13911]
It seems to be correct in Android but there is white circle around the icon in ios.
[](ur
![photo_2021-09-26_13-19-39](https://user-images.githubusercontent.com/85923042/134798796-25e86608-a3c7-440a-ac61-3671a70622b2.jpg)
l)

**Comment by Cryptocool1** [comment]
Hello, 
You should try to reinstall the app
