### ISSUE TITLE
LOGO does not show correctly

### ISSUE THREAD

**Issue by marcotravel** [trustwallet/assets#14073]
it is problem in showing logo size in trust and does not appear correctly could you please fix this? it seems to have extra width and not round 
thank you
![WhatsApp Image 2021-10-03 at 12 22 51 PM](https://user-images.githubusercontent.com/63541507/135803955-44b8018d-98b8-4377-865e-e45d8d5b417f.jpeg)
nd

**Comment by cryptomanz** [comment]
fixed

**Comment by marcotravel** [comment]
sorry for bothering you I have cleared my catch but the logo has the same problem
