### ISSUE TITLE
LOGO does not show correctly

### ISSUE THREAD

**Issue by marcotravel** [trustwallet/assets#14108]
it is problem in showing logo size in trust and does not appear correctly could you please fix this? it seems to have extra width and not round
thank y
![WhatsApp Image 2021-10-03 at 12 22 51 PM](https://user-images.githubusercontent.com/63541507/136017723-3affdb11-02a8-46dc-8051-71aeccb7f5f8.jpeg)
ou

**Comment by Cryptocool1** [comment]
Hello, can you please open new PR with the full size logo?

**Comment by marcotravel** [comment]
yes sure
