### ISSUE TITLE
Asking about status

### ISSUE THREAD

**Issue by TokenDooit** [trustwallet/assets#14300]
## How can we help ?

@Cryptocool1 

Hi, 

Please check my status below

https://github.com/trustwallet/assets/pull/13225

I have paid for the fee, and now my token already reach the requirement of over 5000 holder and 10000 transfer.
my token is listed on coinmarketcap too.

how is my status now?
because I paid already.

and if the status closed already, what should I do for next process of Add Logo on trustwallet?

please help.

thanks.

**Comment by Cryptocool1** [comment]
reopened
