### ISSUE TITLE
New Token Wrapper for an existing Coin

### ISSUE THREAD

**Issue by pir8radio** [trustwallet/assets#14519]
HI, i see there are requirements to submit an asset here.  my question is, can we bypass the 5000 holders requirement if our primary coin this is a wrapper for exceeds these requirements?    I assume the requirements are to weed out short lived coins and scam coins..   Signum is not going anywhere, the primary Coin has been around since 2014.  Just now creating a wrapper though.  Please let me know..       Primary coin:  https://signum.network        token wrapper: 0x7b0e7e40ee4672599f7095d1ddd730b0805195ba

Thanks guys.

**Comment by Cryptocool1** [comment]
Please create PR , then our team will take a look at your token
