### ISSUE TITLE
Listing Requirements for multi-chain assets

### ISSUE THREAD

**Issue by LHMobie** [trustwallet/assets#14698]
Is there a way to include holder and transaction counts across all blockchains when meeting listing requirements?  Until recently, we've been a Stellar-based asset, but we're now wrapped on Ethereum and BSC chains.  We're creeping up in numbers on Ethereum, and we easily have the numbers on our native chain, but we're still frustratingly short for our ERC20 wrap.

Do we just have to wait things out, or can someone grant an exception and allow a PR?

Project name: Mobie Network
Stellar: MBX
Eth: wMBX

**Comment by Cryptocool1** [comment]
We can make an excemption for that
