### ISSUE TITLE
Migrate asset from TRON to BSC

### ISSUE THREAD

**Issue by triloger** [trustwallet/assets#14768]
Oikos has migrated from the TRON ecosystem to the BSC Network. For more information: Read the official medium post at https://t.co/Gr07QVJHqb
Can the asset be migrated by TW team?

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/2256#issuecomment-637829840_

Fee is PAID, fantastic!  Thanks!

The PR will be merged soon by a maintainer, and then new/updated logos should be visible in Trust Wallet.
Please note that the app caches logos for several days, so if you want to see changes immediately, use a new device, or reinstall Trust Wallet (make sure you have a backup of all your wallets first!).  See the [assets FAQ](https://github.com/trustwallet/assets#faq). 

([1 BNB](https://explorer.binance.org/tx/02E1CE7F420135EBD7123E1CADBB0576423548C7C73DC4CAE1A295C31277C60B))

**Comment by Cryptocool1** [comment]
please create PR with the new token
