### ISSUE TITLE
Two Errors (commit and Pull request

### ISSUE THREAD

**Issue by Speedevs** [trustwallet/assets#1492]
![image](https://user-images.githubusercontent.com/45816964/77031579-4b781200-69a2-11ea-8098-75c9045bc792.png)
Error when Updating Image and cannot retrieve "0xa7c8d7a1c894e51dbb7c680b5b1dbdc845bfbdab" this **commit** showing cannot retrieve commit at this time

**Comment by kolya182** [comment]
Added your coin here https://github.com/trustwallet/assets/commit/95ac8770613ccbb48d7e54e09b167c2a8043d5bc
