### ISSUE TITLE
Add SpeedKingToken Trustwallet

### ISSUE THREAD

**Issue by Speedevs** [trustwallet/assets#1493]
Add SpeedKingToken [ SKT] on TrustWallet

Contract Address: 0xaa5c28be0f1173612ea3fcc9e461ccb7b9390213
Token Name - SpeedKingToken
Ticker- 0xa7c8d7a1c894e51dbb7c680b5b1dbdc845bfbdab
Supply token- 20,000,000 SKT
Decimal- 5

![logo](https://user-images.githubusercontent.com/45816964/77032142-e6252080-69a3-11ea-934b-a9279658d936.png)

**Comment by kolya182** [comment]
Added here https://github.com/trustwallet/assets/commit/95ac8770613ccbb48d7e54e09b167c2a8043d5bc
