### ISSUE TITLE
Add_SDBY_CG_CMC_PRİCE

### ISSUE THREAD

**Issue by sadbabytoken** [trustwallet/assets#15021]
hello Sadbaby Token Coingecko and coinmarketcap are listed. Price is not showing in our Trustwallet wallet, we need your support on this issue
https://coinmarketcap.com/currencies/sadbaby/
https://www.coingecko.com/tr/coins/sadbaby
Thank You
https://bscscan.com/token/0x3ad405ef7aea80ccb41beef0a74510e18feef190

**Comment by sadbabytoken** [comment]
https://bscscan.com/token/0x3ad405ef7aea80ccb41beef0a74510e18feef190

**Comment by Cryptocool1** [comment]
Just wait for now

**Comment by Cryptocool1** [comment]
your token price is available now
