### ISSUE TITLE
Beeuda Token Price not showing in Trustwallet

### ISSUE THREAD

**Issue by beeuda** [trustwallet/assets#15076]
Hello, Beeuda Token is now listed on Coinmarketcap. 
However, the Price is not showing yet in our Trustwallet wallet,  Logo has previously been added
Please is there anything else we need to do? We tried to create a new PR
https://coinmarketcap.com/currencies/beeuda/
https://bscscan.com/token/0x5b7f0c82d342be42c94d789cfc3aae29863d123e

Pls kindly investigate.

Thank you

**Comment by Cryptocool1** [comment]
Just wait for now
