### ISSUE TITLE
Omax Token dollar value is not updating.

### ISSUE THREAD

**Issue by fiaz0419** [trustwallet/assets#15244]
**Describe the bug**

Dollar value for Omax Token is not available.

contract address 

0xeB84be66c8E71f07eA57Cf3b21626d7784F32A7F

PR 

https://github.com/trustwallet/assets/pull/15185

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Cryptocool1** [comment]
Just wait for now
