### ISSUE TITLE
Price not showing for $XCAD

### ISSUE THREAD

**Issue by guidosanchez** [trustwallet/assets#15384]
Hi,
 I'm one of the developers for XCAD Network (BEP20 0x431e0cd023a32532bf3969cddfc002c00e98429d  ERC20 0x7659ce147d0e714454073a5dd7003544234b6aa0). We added the token a couple of months ago and everything looks good however for some reason the price doesn't seem to be showing up even though it appears on bscscan and etherscan.
Is there anything you need from our end in order to have that feature working? Our users have been asking a lot about price on trustwallet and we'd like to help them see it.

**Comment by vikmeup** [comment]
You would need to contact CoinMarketCap team and update contract addresses on their side - then we can make associations between CMC ticker and contract address, currently there is only ZIL address listed under (https://coinmarketcap.com/currencies/xcad-network/).
