### ISSUE TITLE
Price does not show KSHIBA

### ISSUE THREAD

**Issue by solproc** [trustwallet/assets#15492]
PR ref: https://github.com/trustwallet/assets/pull/15448

**Comment by Cryptocool1** [comment]
you should just wait for now

**Comment by solproc** [comment]
Ok, I know need time but never seen these much time. By the way now listing fee is much high.

**Comment by solproc** [comment]
can you please tell me how much time does it take??? We are CMC, coingecko listed. What is the reason for such late?
