### ISSUE TITLE
Market Info Not Available

### ISSUE THREAD

**Issue by defismith** [trustwallet/assets#15560]
## How can we help ?

Hey there, we had our token merged into the repo yesterday ( https://github.com/trustwallet/assets/pull/15487 ) however when we try to look at the market info of the newly added token in the mobile app, it says "Market info not available".

I was looking at this webpage for info https://community.trustwallet.com/t/where-does-trust-wallet-get-coin-pricing-data-from/333 and it says "Note:  If the price information about the coin or token is available at CoinMarketCap and it does not properly show on the app, please let us know.".

The coinmarketcap URL is https://coinmarketcap.com/currencies/floki-rocket/

Any help/direction to get this resolved would be appreciated.

Thanks much!

**Comment by Cryptocool1** [comment]
hello, it's not problem from our side, you should contact the CMC team
