### ISSUE TITLE
Help Updating Logo

### ISSUE THREAD

**Issue by skeeterraw1** [trustwallet/assets#1557]
Update Logo for blockchains/ethereum/assets/0x38894302A6eABea6f2B29B508031d2ed75F0bE22/logo.png
![logo](https://user-images.githubusercontent.com/56848752/77606368-8ca58000-6ed4-11ea-984b-1709adc7a66a.png)

**Comment by kolya182** [comment]
https://github.com/trustwallet/assets/commit/642bdc599b85a32c7c826d0fcf904f67100ec339
