### ISSUE TITLE
CMC is ok but trust wallet does not fetch price

### ISSUE THREAD

**Issue by solproc** [trustwallet/assets#15601]
hello, it's not problem from our side, you should contact the CMC team

_Originally posted by @Cryptocool1 in https://github.com/trustwallet/assets/issues/15567#issuecomment-967594262_

CMC Link: https://coinmarketcap.com/currencies/kittyshiba/

No issue on CMC. If need you contact. I have paid for this service. Its not a free service at all.

**Comment by solproc** [comment]
I have just mailed them with this issue no as reference.

**Comment by Cryptocool1** [comment]
hello, You should wait 1-2 weeks after CMC listing. Adding here to the repo - does not guarantee showing any price. Assets repo is not responsible for the price.

**Comment by bitbd83** [comment]
never seen like this before, after CMC list, it does not take more than 2 days.
