### ISSUE TITLE
Add $ADEX to BSC token list

### ISSUE THREAD

**Issue by AlpineDex** [trustwallet/assets#15836]
{
      "type": "BIP20",
      "address": "0x977b820f07b90d4a120B771b89B4cCD45187da91",
      "name": "Alpine Dex",
      "symbol": "ADEX",
      "decimals": 18,
      "logoURI": "https://www.instagram.com/p/CWWOecKLQ-e/?utm_medium=copy_link"
}

**Comment by cryptomanz** [comment]
Duplicate of #15837

**Comment by AlpineDex** [comment]
PINE and ADEX are not the same token but create by the same developers PINE is a reflection token and ADEX is a governance token both are unique
