### ISSUE TITLE
Add $PINE to BSC token list

### ISSUE THREAD

**Issue by AlpineDex** [trustwallet/assets#15837]
{
"type": "BIP20",
"address": "0xeC5B9074717e467bE06E96091f3D47C6e7871a95",
"name": "Alpine Coin",
"symbol": "PINE",
"decimals": 18,
"logoURI": "https://www.instagram.com/p/CWWOdi9ra2H/?utm_medium=copy_link"
}

**Comment by AlpineDex** [comment]
ADEX and PINE are not the same token but created by the same develpers

**Comment by cryptomanz** [comment]
Please create PR to add a token, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
