### ISSUE TITLE
Coin add

### ISSUE THREAD

**Issue by FrankLucas86** [trustwallet/assets#15925]
Please add $PRIVCY to coin list.

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
