### ISSUE TITLE
Could we please reopen this pull request

### ISSUE THREAD

**Issue by MoonPawToken** [trustwallet/assets#15924]
Could we please reopen this pull request

_Originally posted by @MoonPawToken in https://github.com/trustwallet/assets/issues/7284#issuecomment-974789309_

**Comment by cryptomanz** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 25,000 holder addresses and 50,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .
