### ISSUE TITLE
Add Digital CHF on TrustWallet

### ISSUE THREAD

**Issue by DigitalCHF** [trustwallet/assets#1608]
![IMG_20200328_023835](https://user-images.githubusercontent.com/62738234/77789118-6b43c000-709d-11ea-8694-b7585825e471.jpg)
Error when Updating Image and cannot retrieve "0x0703Fb3CCF77D117Ecbb19774b5f97c5a4875c9D",
this commit showing cannot retrieve commit at this time.

**Add Digital CHF (DCHF) on TrustWallet**
Name : Digital CHF
Symbol : **DCHF**
Contract Address : 0x0703Fb3CCF77D117Ecbb19774b5f97c5a4875c9D
![logo](https://user-images.githubusercontent.com/62738234/77789497-181e3d00-709e-11ea-8a72-e1dd98dbbeb6.png)

**Comment by kolya182** [comment]
Added
