### ISSUE TITLE
TWT LOGO

### ISSUE THREAD

**Issue by henrymark1** [trustwallet/assets#16083]
merge fee bot says 
❌ The links field cannot be empty (where the links are missing ??????)
❌ Low token circulation: no. of holders is 17500, below limit of 25000

and also says As there is no refund, before paying the fee, make sure new tokens fulfill the minimum circulation and other acceptance criteria.

Minimum 25,000 token holders and 50,000 transactions (Airdrop tokens excluded**). This requirement is subject for review based on the project.

Cant we refund If it is less and you will decide we dont have acceptance criteria?

**Comment by Cryptocool1** [comment]
please answer the questions in PR

**Comment by henrymark1** [comment]
The benefit of the token will not only benefit trustwallet users rather the
entire earth because it has do planting of trees across the globe by
assigning 10 trees per holder and also rewarding it's holders with a
whooping 6% reflection from all transactions .

No airdrop is been conducted

It was a presale

We are listed on both centralized exchange and decentralized exchange which
includes pancakeswap feg exchange and coinsbit

The smart contract is audited and this information can be seen clearly in
the website
