### ISSUE TITLE
MDABULHASANk

### ISSUE THREAD

**Issue by sheakhasan926** [trustwallet/assets#16158]
**PR Summary** 
File is being deleted, blockchains/ethereum/assets/0x340eF83Ec8560892168D4062720F030460468656/logo.png. Files should not be deleted in a PR. (Deprecated tokens should be deactivated only.)

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/16144#issuecomment-980547653_

**Comment by cryptomanz** [comment]
when the migration is complete, we are obliged to delete the old contract
