### ISSUE TITLE
Added ERC20 token not showing Rizin (RZN)

### ISSUE THREAD

**Issue by zachzwei** [trustwallet/assets#1632]
**Describe the bug**
Token already merged as per https://github.com/trustwallet/assets/pull/1573
But it is not searchable on the app

**To Reproduce**
1. Search for either name, ticker or contract address but it is not found.
![image](https://user-images.githubusercontent.com/35627271/77984494-4de44f80-7344-11ea-9485-9bcad27d909d.png)

**Expected behavior**
Be able to search the token.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [iPhoneX]
 - OS: [13]
 - Version [7052]

**Additional context**

**Comment by kolya182** [comment]
Checking

**Comment by kolya182** [comment]
Fixed
