### ISSUE TITLE
Update Coin on Trust wallet ( LYS /YEAR )

### ISSUE THREAD

**Issue by YEARLAB** [trustwallet/assets#16527]
Updating Lightyears Coin 
Migrated to Blockchain Base From ERC20 To Bitcoin Fork 
Previous Ticker : LYS 
Current Ticker: YEAR

API : https://explorer.lightyears.io/info
Github: https://github.com/YEARLAB/Lightyears
Website : https://Lightyears.io
Blockchain Explorer : https://explorer.lightyears.io
MARKETCAP: https://coinmarketcap.com/currencies/lightyears

Thank you

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

**Comment by YEARLAB** [comment]
We already on Trust wallet , Just that needed the update as we migrated to our own blockchain .
