### ISSUE TITLE
Asking about migrate SC

### ISSUE THREAD

**Issue by TokenDooit** [trustwallet/assets#16547]
Hi, we have plan to migrate our token to SC V2 on this month, in regards of our old token is already on trustwallet with logo, do we need to repeat register and pay again for new SC logos?

**Comment by Cryptocool1** [comment]
yes, you will need to pay the fee for migration.

**Comment by TokenDooit** [comment]
how much the fee? how is the steps?

**Comment by Cryptocool1** [comment]
> how much the fee? how is the steps?

Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements

**Comment by Cryptocool1** [comment]
the fee is the same

**Comment by TokenDooit** [comment]
Oke Thanks
