### ISSUE TITLE
Upload Logo Token CoronaCrypto ( NCOR )

### ISSUE THREAD

**Issue by CoronaCryptoOfficial** [trustwallet/assets#1747]
Dear Team Trust Wallet
Please Update Logo ConronaCrypto ( NCOR )
Website : http://crypto-virus.io/
Project Name : CoronaCrypto
Token : NCOR
Type : ERC20
Total Supply : 7.739.879.999 NCOR

**Comment by kolya182** [comment]
https://github.com/trustwallet/assets/commit/281a6b7de849e8ec2c2901e6677194de7f9f36fb
