### ISSUE TITLE
Set up logo on Gnosis chain

### ISSUE THREAD

**Issue by best-lucky1030** [trustwallet/assets#17509]
I'd like to upload the logo of my token.
Token name is P8 and it's based on Gnosis chain.
[](https://info.honeyswap.org/#/pair/0x686c626E48bfC5DC98a30a9992897766fed4Abd3)
This is our public token address.
0x772fce4b8e88bd19e86dc92428d242704ac480a0
I tried to find `Gnosis` chain here, but can't find it.
Where can I upload and set up my token logo?

**Comment by best-lucky1030** [comment]
@cryptomanz 
Why did you close my question?
If then, where can I find the solution?

**Comment by Cryptocool1** [comment]
We don’t have Gnosis chain

**Comment by Diogomartf** [comment]
They use the old name for gnosis chain: `xdai`
