### ISSUE TITLE
Implement Merge Fee bot

### ISSUE THREAD

**Issue by kolya182** [trustwallet/assets#1783]
In order to streamline adding new assets to the repository, we enforce small fee to be made in order to review and merge PR.

- [x] Add charging fee process description
- [ ] Define PR merge conditions
    - [ ] PR must be made following submission guidelines, even PR was paid still need to complete guidelines
    - [ ] Payment must be made with in 7 days if not close PR automatically
    - [ ]  Define fee in TWT and BNB
    - [ ] Define memo parameter to specify in transaction
    - [ ] Add `Paid` title to PR after received fully amount
    - [ ] Color code successfully payment in green, not fully paid in yellow, not paid in red (when run /check)
   - [ ] Give PR labels based on payment status, see =>
- [x] Include QR code with embedded memo in bot comment + link to the wallet
- [ ] Make sure process clear and smooth
    * Possible add simple video instruction
- [x] Add bot logo

**Comment by catenocrypt** [comment]
The bot is active, here is the message added to new PRs:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/13562139/78978918-0cf5f300-7b1b-11ea-8c43-4dce8d914f86.png">

Payment status is checked whenever there is a new comment on the PR.
If payment is detected, a review approve is added automatically.
Merging has to be done manually, so it is up to the maintainers to do the merge after payment, or do it without payment, or don't do.  The bot just helps to show the payment status, by creating a review.

A logo has been added.
It remains to be tested live how payment detection works.
