### ISSUE TITLE
No logo on Trust dapp Explorer

### ISSUE THREAD

**Issue by Pierre764** [trustwallet/assets#17914]
Hello there :)

We added our logo to your rep last year but it can't be seen on the explorer page, it only shows up on the asset page (wallet)
How to sort that out, please?

Many thanks, 
Pierre

![Trust 2](https://user-images.githubusercontent.com/87363698/152749529-e4ad56b6-8fd7-4f33-b1cd-bdcf073b88f0.jpg)

![Trust](https://user-images.githubusercontent.com/87363698/152749153-0277560b-f9bf-451a-97af-6032977a1f56.jpg)

**Comment by unanoc** [comment]
Hi @Pierre764!

This is a different type of asset, so you need to add your logo to [assets/dapps](https://github.com/trustwallet/assets/tree/master/dapps) repo.
