### ISSUE TITLE
I PAID FEE

### ISSUE THREAD

**Issue by InfinityTokenINF** [trustwallet/assets#1798]
## How can we help ?

I already Paid the transaction fee for merging, 8DD357CE670EE930E22CDD7F7ABA51EDE7B9B656EBA2C7852D7D6ACDE25895E0 I paid 2000 TWT why it didnt merge at all? please be responsive of this

**Comment by catenocrypt** [comment]
Thank you! As you can see in the PR comments, payment has been acknowledged automatically, and a review added. Review is a condition for merge, but the merge has to be done manually by the maintainers.
