### ISSUE TITLE
DYOR Token - Price Not Showing

### ISSUE THREAD

**Issue by DiscoBurnToken** [trustwallet/assets#18193]
DYOR Token is listed on CoinMarketCap but the price does not show in TrustWallet. We can see volume but the price and market cap both display as "0" 

We recently migrated to a new contract. Does the API need to be updated for our token? What can we do to display the CMC price in TrustWallet?

https://coinmarketcap.com/currencies/dyor-token/ 

https://bscscan.com/token/0x10051147418c42218986cedd0adc266441f8a14f

![DYOR TW](https://user-images.githubusercontent.com/93751858/153959702-5902b8f0-c9a3-448e-8c0c-bd0617a085ac.jpg)

**Comment by Cryptocool1** [comment]
Token prices will only show up within Trust Wallet if the CoinMarketCap (CMC) listing has the correct contract address associated with it.
see https://developer.trustwallet.com/assets/faq

**Comment by Cryptocool1** [comment]
You should create new Pull Request with you new contract, then we will put status abandoned for your old

**Comment by DiscoBurnToken** [comment]
We did create a new Pull Request and the Pull Request was approved and merged.

The contract address listed in this Pull Request matches the Coin Market Cap contract address.

https://github.com/trustwallet/assets/pull/17705

**Comment by DiscoBurnToken** [comment]
Opened new pull request here 

https://github.com/trustwallet/assets/pull/18197
