### ISSUE TITLE
Added icon to ETHENITY ethereum erc20 token but not updated yet

### ISSUE THREAD

**Issue by elenixatzaa** [trustwallet/assets#1823]
Smart contract address: 0xf0bcc10aba434B054cc6ec3c87A57491e9473bac
![logo](https://user-images.githubusercontent.com/63509005/79048523-54b57100-7c26-11ea-9524-400225a3aa78.png)

I have also sent through pull request the info.json
 The website is http://ethenity.airsite.co

**Comment by kolya182** [comment]
You need to pay first
