### ISSUE TITLE
Add token info list

### ISSUE THREAD

**Issue by kolya182** [trustwallet/assets#183]
**Is your feature request related to a problem? Please describe.**
Add token info like:
name
abbreviation
dec
token supply
issuer address
date created

short description
website
link to white-paper (if any)

**Describe the solution you'd like**
Script that parse info about any token and make PR with a changes

**Describe alternatives you've considered**
Adding manually, but time consuming

cc https://github.com/ICEDIUM for proposal

**Comment by erc20devteam** [comment]
Hi @kolya182 is this for ERC20 Tokens on TrustWallet or something different, thanks

**Comment by kolya182** [comment]
> Hi @kolya182 is this for ERC20 Tokens on TrustWallet or something different, thanks

Could be for any token on any network.

**Comment by erc20devteam** [comment]
Thanks @kolya182 it'll be good then. Will try this new feature when available or approved by others.

**Comment by flaviosar** [comment]
Hello @kolya182 I need to add image of new ERC20 token, what do I need to do?

**Comment by ersanyakit** [comment]
Add token info like:
name
abbreviation
dec
**token supply**
issuer address
date created

We can get the details directly on blockchains. But we cannot keep totalsupply data as static. Because there is alot of deflationary tokens available on chains... Deflationary tokens total supply decreasing automatically every transfers...

**Comment by erc20devteam** [comment]
Hi @kolya182 >> I do have a proposal that might reduce the work and will help. On MyEtherWallet Default List they just follow one simple step which is very easy and their application structure is quite simple. They allow to "Create New File" and submit Poll Request. All info such as logo name, address, decimals all are available within a single file.

Link for check on Github >> https://github.com/MyEtherWallet/ethereum-lists/new/master/src/tokens/eth

![image](https://user-images.githubusercontent.com/55205610/67148470-cb9a2e80-f2c1-11e9-9a04-75335206f651.png)

![image](https://user-images.githubusercontent.com/55205610/67148520-23389a00-f2c2-11e9-9125-38879b543323.png)

**Comment by kolya182** [comment]
> Hi @kolya182 >> I do have a proposal that might reduce the work and will help. On MyEtherWallet Default List they just follow one simple step which is very easy and their application structure is quite simple. They allow to "Create New File" and submit Poll Request. All info such as logo name, address, decimals all are available within a single file.
> 
> Link for check on Github >> https://github.com/MyEtherWallet/ethereum-lists/new/master/src/tokens/eth
> 
> ![image](https://user-images.githubusercontent.com/55205610/67148470-cb9a2e80-f2c1-11e9-9a04-75335206f651.png)
> 
> ![image](https://user-images.githubusercontent.com/55205610/67148520-23389a00-f2c2-11e9-9125-38879b543323.png)

So far we have no need in such information, and to keep it even simple we could even fetch from them and populate in our repo once we need it. Thanks you fro proposal.

**Comment by erc20devteam** [comment]
You are welcome @kolya182, happy to know that you are trying to make the application simple. I'm facing some issues of my client token logo, though I've applied successfully and you merged them nicely but now a days the logo, symbol, name is not showing on app search box. Is there any reason of that? Do I need to follow any other instructions or have to submit any other or more info. Thanks in advance for taking time to sort this out.

**Comment by kolya182** [comment]
I need contract addresses of tokens that do no shows up in search

**Comment by erc20devteam** [comment]
Hi dear, sorry for late reply, this is one of some that not showing on TrustWallet

Contract Address: 0x8851b3dda4f8a0a231ff45e8871b7003142d83dc
https://github.com/trustwallet/assets/pull/388

Lot's more, can you see this is available or not, I can't see on my device. Thanks.

**Comment by kolya182** [comment]
> 0x8851b3dda4f8a0a231ff45e8871b7003142d83dc

I see the issue, will fix it.

**Comment by erc20devteam** [comment]
Actually this is not only one, lot's more, may be this is happening after last modification that came aboard on new application system. Please solve this, one last question, if this get ok, will be applicable for all other contract that already merged perfectly. It'll be great then, Thanks @kolya182

**Comment by erc20devteam** [comment]
Dear @kolya182 , here is a list of all my clients token application that merged successfully and all application passed the process after apply. But they are still not showing on TrustWallet Search Box. Can you please check and solve the issue. Thanks.

Poll # >> Contract Address

https://github.com/trustwallet/assets/pull/280 >> 0xb0b18830491097b5cfb0b6131c2ebf683fada891

https://github.com/trustwallet/assets/pull/307 >> 0x92b7e4409dcf8c439f313ed1f05fdc0550d18ddd

https://github.com/trustwallet/assets/pull/341 >> 0xaa5c28be0f1173612ea3fcc9e461ccb7b9390213

https://github.com/trustwallet/assets/pull/380 >> 0xee8a2ecd3f7edadc01ccf0731111c294b883f60e

https://github.com/trustwallet/assets/pull/382 >> 0x2976ac3d0bb67c6307a73df852c61c14cdda9863 [Logo: https://raw.githubusercontent.com/trustwallet/assets/eacff53fe138a4fcf95b473f969a13e7958836c6/blockchains/ethereum/assets/0x2976ac3d0bb67c6307a73df852c61c14cdda9863/logo.png]

https://github.com/trustwallet/assets/pull/385 >> 0x42e9d6798bb9ede0aeedaacb6e07756266dad67d

https://github.com/trustwallet/assets/pull/408 >> 0x9025f9a59694dd939739e05beb2502a567e8326f

https://github.com/trustwallet/assets/pull/427 >> 0x8f2fc2ab67d61d30eb3478a4f9396ab1ca90ba21

https://github.com/trustwallet/assets/pull/492 >> 0xd967d9f941cd316ab238d3ee761f80b7caec7819

https://github.com/trustwallet/assets/pull/493 >> 0xa79e0012bb3379f8509a5ab49cab7e6abb49701d

https://github.com/trustwallet/assets/pull/498 >> 0x00ea6f91b00e080e816f1bb2fad71b0fe1528983

https://github.com/trustwallet/assets/pull/501 >> 0x2a73cb91ed8983398f83082c093ac306cac209ff

It'll be a great help if you solve the issue and help us and our client. Thanks again.

**Comment by vikmeup** [comment]
Not necessary at the moment, closing
