### ISSUE TITLE
Я заплатил 1000 TWT, чтобы загрузить логотип

### ISSUE THREAD

**Issue by antoniosqzy** [trustwallet/assets#1834]
Я заплатил 1000 TWT за загрузку логотипа, пожалуйста, обновите логотип

**Comment by kolya182** [comment]
Зачем создавать это сообщение если можно прочитать, что было отвеченно в комментарии к PR.

**Comment by antoniosqzy** [comment]
тогда после чего?

**Comment by antoniosqzy** [comment]
Должен ли я отправить ретракт?

**Comment by kolya182** [comment]
О чем этот токен ?

**Comment by antoniosqzy** [comment]
да токен используется для голосования на нашем предстоящем обмене

**Comment by antoniosqzy** [comment]
can you update logo?
