### ISSUE TITLE
ontology private key import

### ISSUE THREAD

**Issue by roccomuso** [trustwallet/assets#18616]
Could you guys allow to import Ontology private key?  (like for Solana)

**Comment by kissanakaen** [comment]
You can send your personal key to my email, I will check it. kissanakarn1234@gmail.com

**Comment by Kaktus259** [comment]
Хуйтебе на ворота

сб, 5 мар. 2022 г., 20:47 kissanakaen ***@***.***>:

**Comment by tyntyn1** [comment]
@roccomuso @kissanakaen @hexorx

**Comment by Selfcare-Trustwallet** [comment]
Contact our support Team and state all your issue, Email: Trustwalletselfcare@consultant.com

**Comment by Selfcare-Trustwallet** [comment]
> Could you guys allow to import Ontology private key?  (like for Solana)
> 

Contact our support Team and state all your issue, Email: Trustwalletselfcare@consultant.com
