### ISSUE TITLE
Token info not being shown on trust wallet

### ISSUE THREAD

**Issue by pwnedev** [trustwallet/assets#18650]
Our token isn't showing the price in trust wallet for some reason.

Our asset link: https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets/0x40B165Fd5dDc75ad0bDDc9ADd0adAbff5431a975

Also is it possible to update the logo/info or does it require extra fees?

Thanks in Advance!

**Comment by Cryptocool1** [comment]
Hello, if you want to update your logo, you should create Pull Request and pay the fee for updating.

**Comment by pwnedev** [comment]
@Cryptocool1 Ok thanks for the info! We don't want to update it yet because we'll change some more stuff. 

It would be nice to have the current info being shown tho. It's tracked on CMC but it doesn't show the price in trust wallet. Why is that?

**Comment by Yuxanju** [comment]
You will have to synchronize your wallet and then you debug it

**Comment by pwnedev** [comment]
@Yuxanju What exactly do you want me to debug? It isn't syncing with coinmarketcap, and it's happening with everyone that owns my token

**Comment by Yuxanju** [comment]
You have to synchronize your hard wallet and then you debug it. I can get
you a encrypted ellipal link. All you have to do is to follow the link till
you get to synchronize wallet and you click on it

**Comment by Yuxanju** [comment]
Have you debug your wallet

**Comment by pwnedev** [comment]
Hey @unanoc, the issue still persists. Any news about what might be causing it or when it can be solved?

**Comment by unanoc** [comment]
@pwnedev it's gonna be fixed soon
