### ISSUE TITLE
ADD Groundcoin (GC) token logo Trust wallet

### ISSUE THREAD

**Issue by hyun999com** [trustwallet/assets#1891]
ADD Groundcoin (GC) token logo Trust wallet

Token Name: Groundcoin
Token Symbol: GC
Token Decimals: 18
Token Initial Supply: 10,000,000,000
Token Contract: 0x157207df36cf1803399cca15cad867fd54514fde

![0x157207df36cf1803399cca15cad867fd54514fde](https://user-images.githubusercontent.com/43489017/79559296-16570080-80c3-11ea-9be9-06b8d426bbdf.png)

**Comment by kolya182** [comment]
Please create PR and pay fees

**Comment by hyun999com** [comment]
where sir ? please guide me

**Comment by hyun999com** [comment]
How much fee ?

**Comment by kolya182** [comment]
You will see message from our bot

**Comment by hyun999com** [comment]
https://github.com/trustwallet/assets/pull/1880

Processing BNB 0.5 2020-04-19 19:41:26 주소:bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098
Memo:1879

https://explorer.binance.org/tx/2A73EF831015E0492DDD00E80BCE05BC7CC659C45B255BD0647F8060C6DB89A0

**Comment by hyun999com** [comment]
please update logo trust wallet

**Comment by hyun999com** [comment]
Please update logo already provide payment sir 

ADD Groundcoin (GC) token logo Trust wallet

Token Name: Groundcoin
Token Symbol: GC
Token Decimals: 18
Token Initial Supply: 10,000,000,000
Token Contract: 0x157207df36cf1803399cca15cad867fd54514fde


![0x157207df36cf1803399cca15cad867fd54514fde](https://user-images.githubusercontent.com/43489017/79871010-660a3480-8401-11ea-8fa8-bda8c49d2e2d.png)
