### ISSUE TITLE
Remove Our erc20 Token CoinVisa from Trust wallet .

### ISSUE THREAD

**Issue by coinvisa** [trustwallet/assets#1892]
Remove Our erc20 Token CoinVisa from Trust wallet ..move to stellar platform 

Token Name	: CoinVisa
Symbol		: CVS
Decimals	: 18
Total Supply	: 1,000,000,000 CVS
Contract Address: 0xdb56448fe2635f7912287cd619e7ed3d93180f25

check announced here
https://etherscan.io/token/0xdb56448fe2635f7912287cd619e7ed3d93180f25
 https://www.facebook.com/CoinVisaExchange/posts/2309320949362181

![logo-media-cta-250x250](https://user-images.githubusercontent.com/53531127/79576646-3eedf300-80e1-11ea-9357-06c61c5eda86.png)

**Comment by kolya182** [comment]
Removed and added popup notification for your users
