### ISSUE TITLE
The trust wallet team doesn’t go by policy 

### ISSUE THREAD

**Issue by BerylBit** [trustwallet/assets#19055]
There has been countless of times where new tokens under 10k holders and have not met other requirements set by the trust wallet policy for logo listing but yet gets listed on trust wallet logo.. 

This is ridiculous, I have countless of evidence of many tokens that got listed without even coming close to met the policy requirements yet it gets listed..

I have sent in my pull request for a token logo listing on trust wallet hoping I may get listed since I over qualify then the other pervious tokens that have been listed and my only short coming is being 5k less in holders (just a reminder other tokens trust wallet team listed were at 4-6k) yet my pull request gets rejected due to the fact of not having enough holders.. I don’t understand is there some type of extra pay I have to pay or talk to someone to get listed like the other tokens? Because I’m curious how they have low liquidity, no audit and yet get listed I’m really interested. Thanks trust wallet team this is so professional(sarcasm).

**Comment by Cryptocool1** [comment]
Hello, we don't disclose or discuss our external policy and we have right to reject any token.
