### ISSUE TITLE
ADD Groundcoin (GC) token logo Trust wallet

### ISSUE THREAD

**Issue by hyun999com** [trustwallet/assets#1915]
ADD Groundcoin (GC) token logo Trust wallet

Token Name: Groundcoin
Token Symbol: GC
Token Decimals: 18
Token Initial Supply: 10,000,000,000
Token Contract: 0x157207df36cf1803399cca15cad867fd54514fde
![0x157207df36cf1803399cca15cad867fd54514fde](https://user-images.githubusercontent.com/43489017/79681921-e54e0b80-823b-11ea-9885-c8d48f087302.png)

**Comment by kibumkim5779** [comment]
코인 상장날짜를 알려주세요
