### ISSUE TITLE
Remove Monetas Logo On Trustwallet

### ISSUE THREAD

**Issue by monetas26** [trustwallet/assets#19363]
Please Remove Montas logo on Trustwallet, Please remove only logo.

Do as early as possible

Referance PR No - #19359

**Comment by monetas26** [comment]
Remove Only Logo, Do not remove any other information

**Comment by Cryptocool1** [comment]
What is the purpose?

**Comment by Cryptocool1** [comment]
can you send me the official announcement?

**Comment by monetas26** [comment]
Yes ,

Official Announcement Will Find it On Our Website, and also we have listed
new address on latoken exchange , Coingecko,Conmarketcap

and new contract change announcement is mentaion in whitepaper


Can You Change or Update New Contract Address Instead  Old Contract Address

https://monetasglobal.com/

**Comment by monetas26** [comment]
Please Reply Us

**Comment by Cryptocool1** [comment]
You should create new PR adding new contract, and then we will put status abandoned to your old contract

**Comment by monetas26** [comment]
Ok, will do that.

Thank You

**Comment by monetas26** [comment]
Yes I will Create New PR :- #19372

Please Check and Revert Me
