### ISSUE TITLE
Non-deposit of currency in Volt Trust

### ISSUE THREAD

**Issue by Kamranwew70** [trustwallet/assets#19466]

**Comment by Gddefuh** [comment]
Hi 
I have bitcoin after transfering they don't show 
The logo. Would you please help me to solve this problem

**Comment by RrezaRashedi** [comment]
https://github.com/trustwallet/assets/issues/19466#issue-1190774963

**Comment by RrezaRashedi** [comment]
> ## How can we help ?
> 
> 
> 

Yeeeaaaa please

**Comment by Gddefuh** [comment]
Hi
I have bitcoin after transfering they don't show
The logo. Would you please help me to solve this problem

**Comment by ahmed1107** [comment]
> Hi I have bitcoin after transfering they don't show The logo. Would you please help me to solve this problem

is this sorted now?

**Comment by Gddefuh** [comment]
> > Hi I have bitcoin after transfering they don't show The logo. Would you please help me to solve this problem
> 
> is this sorted now?

Yes it's stored

**Comment by naser5319** [comment]
Nice   good

**Comment by bradmatson** [comment]
I cannot see my assets for public viewing

**Comment by Gddefuh** [comment]
What nice? I still have that problem

**Comment by bradmatson** [comment]
I need to check whether I'm the owner and master of this block chain pkease

**Comment by Ramos199200** [comment]
Hello

**Comment by Ramos199200** [comment]
Sorry
