### ISSUE TITLE
Add Dabb Doge(BEP20) info&logo#3

### ISSUE THREAD

**Issue by Tdeveloper2022** [trustwallet/assets#19491]
Hello 
I tried several times to create pr for updating info & logo for Add Dabb Doge(BEP20) info&logo but it dose not work.
please help me  to create trust wallet assets pr .
thank you

**Comment by cryptomanz** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details
