### ISSUE TITLE
 Add Dabb Doge (BEP20) #19493 

### ISSUE THREAD

**Issue by Tdeveloper2022** [trustwallet/assets#19498]
Hello
thank you but there is no price for DDoge and not even any chart & also it dose not link to cmc 
![WhatsApp Image 2022-04-04 at 4 16 29 AM(2)](https://user-images.githubusercontent.com/102908556/161535890-2db08ca7-69ff-400b-97b9-6d45751c079b.jpeg)
 !
please fix it for us

**Comment by unanoc** [comment]
![telegram-cloud-photo-size-2-5359722867757004879-y](https://user-images.githubusercontent.com/24758309/161672325-3152d7b5-0183-4b19-9f86-04bf63f25ad0.jpg)
![telegram-cloud-photo-size-2-5359722867757004880-y](https://user-images.githubusercontent.com/24758309/161672336-9e20610c-3ef7-454b-86c8-04541a1e9c15.jpg)
