### ISSUE TITLE
ADD Nise Chain (STO) token logo Trust wallet

### ISSUE THREAD

**Issue by nisechain** [trustwallet/assets#1973]
ADD Nise Chain (STO) token logo Trust wallet

Token Name: Nise Chain
Token Symbol: STO
Token Decimals: 18
Token Initial Supply: 9,680,000,000 STO
Token Contract: 0x72a8e0b56ae249537a2636c5ecac0f03b60d7dc5

![0x72a8e0b56ae249537a2636c5ecac0f03b60d7dc5](https://user-images.githubusercontent.com/64248623/80222001-c698ac00-8663-11ea-8d03-f516aeecbb58.png)

**Comment by nisechain** [comment]
payment is done
https://explorer.binance.org/tx/BE2B3A4DFE5F41ED7531C1C191A8D614690412D1909503A27348AE994D237D37

Yes, send 1 BNB . Hash : BE2B3A4DFE5F41ED7531C1C191A8D614690412D1909503A27348AE994D237D37

**Comment by nisechain** [comment]
when logo appear sir

**Comment by kolya182** [comment]
https://github.com/trustwallet/assets#why-i-dont-see-my-token-in-search-after-pr-was-merged
