### ISSUE TITLE
Are we going to have to pay for this again? Please advise, we urgently need to know what we must do

### ISSUE THREAD

**Issue by GOMAFinance** [trustwallet/assets#19867]
Are we going to have to pay for this again? Please advise, we urgently need to know what we must do

I've paid, and also sent through questions. If there is anything we need to do or do the push request again please let us know urgently 

_Originally posted by @GOMAFinance in https://github.com/trustwallet/assets/issues/19812#issuecomment-1101181174_

**Comment by andrezud** [comment]
Isso é scam. Projeto sem nexos.
