### ISSUE TITLE
Please submit the correct information, invalid information will cause the issue to close

### ISSUE THREAD

**Issue by Mehrnazibi** [trustwallet/assets#20053]
Please submit the correct information, invalid information will cause the issue to close

_Originally posted by @jz2120100058 in https://github.com/justswaporg/justlists/issues/2744#issuecomment-1107691617_

**Comment by zoroinu** [comment]
Dear team,
We would like to send the holder and transfers information for you to check manually.
Please help me take a look.
Best regards !

**Comment by zoroinu** [comment]
Total Supply: 1,000,000,000,000,000 ZORO
Holders: 17,738 addresses
Transfers: 80,917

**Comment by zoroinu** [comment]
Dear team,

Looking forward to your feedback.
