### ISSUE TITLE
Scammer company

### ISSUE THREAD

**Issue by AsgharSibil** [trustwallet/assets#20095]
@cryptomanz @hexorx @corymsmith 
Hello
According to Trust Wallet's basic rules, no token that has not been audited can load the logo on that platform.
Please review the WOJ project again.
The Woj Token project has not been audited, and the company's developers have been duping you. They sent another smart contract to The eNebula company for auditing, which went off without a problem. However, the smart contract they deployed is another smart contract. You may validate my speech using the documentation accessible at The eNebula and the contract deployed on the bscscan. They have been able to defraud thousands of individuals due to this, and the acceptance of the logo on the Trust Wallet platform verifies the ongoing operation of these fraudsters.
Please remove these scammer's token logos from the Trust Wallet platform.
Please have a look.
Best Regards
Webamooz

eNebula company auditing report : 
https://drive.google.com/file/d/1Vu3Az7KTJ_9OIjYTxHyMigkKGDi9blsZ/view

Token deployed on Bscscan : 
https://bscscan.com/address/0x55f96c7005d7c684a65ee653b07b5fe1507c56ab#code

**Comment by AsgharSibil** [comment]
im talking about this project 

https://github.com/trustwallet/assets/pull/14062

please check this scam project

**Comment by cryptomanz** [comment]
hello, what's the issue? how did they deceive you?

**Comment by AsgharSibil** [comment]
![fake functions](https://user-images.githubusercontent.com/91069721/165203042-ae934c07-8354-4f48-a036-407ea4d2c93d.png)

This picture is the audited smart contract function.
Try to find one of these functions on deployed smart contract. 
You cant find these functions cause they deployed another smart contract.

**Comment by AsgharSibil** [comment]
They deceive you, not me.

**Comment by AsgharSibil** [comment]
@cryptomanz 
I hope I was able to convey my meaning completely.
if you need more information, let me know

**Comment by cryptomanz** [comment]
thank you for this info, we will take a look at this project

**Comment by AsgharSibil** [comment]
Thank you very much; the Persian Crypto Community will be grateful to you and your team for your kindness.

**Comment by AsgharSibil** [comment]
@cryptomanz 
Hello sir
Did you check that?
We are waiting for your answer .
