### ISSUE TITLE
tezos validators list update request (after new requirements were applied)

### ISSUE THREAD

**Issue by atorrente75** [trustwallet/assets#2017]
## How can we help ?

The new requirements for validators were applied with too little notice.
We had also expressed doubts to which we awaited answers:

https://github.com/trustwallet/assets/pull/1971#issuecomment-620542630

Btw, we decreased the minimum delegation from 10 to 0 and notified the change to baking bad.
Now both of our addresses are compliant.
Could you please put them back on the validators list?

tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA -> TezoSteam
tz1STeamwbp68THcny9zk3LsbG3H36DMvbRK -> StakingTeam

tnks
A.

**Comment by kolya182** [comment]
> ## How can we help ?
> The new requirements for validators were applied with too little notice.
> We had also expressed doubts to which we awaited answers:
> 
> [#1971 (comment)](https://github.com/trustwallet/assets/pull/1971#issuecomment-620542630)
> 
> Btw, we decreased the minimum delegation from 10 to 0 and notified the change to baking bad.
> Now both of our addresses are compliant.
> Could you please put them back on the validators list?
> 
> tz1LLNkQK4UQV6QcFShiXJ2vT2ELw449MzAA -> TezoSteam
> tz1STeamwbp68THcny9zk3LsbG3H36DMvbRK -> StakingTeam
> 
> tnks
> A.

Please read this https://github.com/trustwallet/assets#tezos.
