### ISSUE TITLE
memo 2014

### ISSUE THREAD

**Issue by Niuupeak** [trustwallet/assets#2021]
## How can we help ?

by mistake ill transfer 0.99BNB so what to do

**Comment by kolya182** [comment]
We will refund the extra you paid.

**Comment by Niuupeak** [comment]
plz refund the extra paid

my BNB address
bnb14kktnh6n20efy4kfh0u5xy38rw53j8q5gkzuzv

**Comment by Niuupeak** [comment]
sir NO,  0.4BNB sir
only extra BNB
