### ISSUE TITLE
[Dapp icon] 1inch Dapp icon is missing in dapps folder

### ISSUE THREAD

**Issue by ivanKis** [trustwallet/assets#20526]
https://assets-cdn.trustwallet.com/dapps/1inch.exchange.png
![image](https://user-images.githubusercontent.com/74901463/169571232-51f5d6dc-f782-4024-bdda-3eb292fd1ae1.png)

iOS app screenshot DeFi section on Discovery:
<img width="381" alt="image" src="https://user-images.githubusercontent.com/74901463/169571380-cfe70d13-781e-4ba4-8293-14e5a34940c6.png">

**Comment by ArtemGoryunov** [comment]
no need
