### ISSUE TITLE
Add Asset Check Result Error

### ISSUE THREAD

**Issue by 0x3639** [trustwallet/assets#20899]
## How can we help ?

I'm trying to add the wZNN logo to the assets repo (https://github.com/trustwallet/assets/tree/master/blockchains/smartchain/assets) I'm using this tool to do so (https://assets.trustwallet.com/).  I've completed all the requested information but when I select Create Pull Request I get an error below.   

"number of holders not checked.  Please check it manually."  

The BSCscan address is here: https://bscscan.com/token/0x84b174628911896a3b87fa6980d05dbc2ee74836  We have 1600 holders and > 35,000 Transactions.  Many holder remove their tokens from BSC and bridge to the native network.  Or they own the native asset ZNN through centralized exchanges.  

So looks like we don't meet the minimum threshold of holders:  https://developer.trustwallet.com/assets/requirements.

**Is there any way to submit this pull request without 10,000 token holders?**  wZNN has done $158M in volume on pancakeswap since August 24, 2021.

**Comment by Cryptocool1** [comment]
hello, you should meet the requirements.

**Comment by 0x3639** [comment]
This is great news.  I’m unable to complete the form and Create a Pull request with the tool at https://assets.trustwallet.com. I get the following error:

"number of holders not checked. Please check it manually."

How can I bypass this error and submit the pull request with the provided tool?

**Comment by Cryptocool1** [comment]
You should have 10.000 holders, please create PR once this criteria completed
