### ISSUE TITLE
Add Terra 2.0

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/assets#20968]
Follow the Terra Classic - Terra 2.0 split:

- `terra` becomes Terra Classic --> update logos, set deprecated
- `terrav2` add new Terra 2.0 asset

See official logos here: https://docs.terra.money/docs/migration/exchange-migration.html#logos-and-assets

**Comment by cryptomanz** [comment]
https://github.com/trustwallet/assets/pull/20666

**Comment by cryptomanz** [comment]
https://github.com/trustwallet/assets/pull/20970

**Comment by catenocrypt** [comment]
Solved by #20970
