### ISSUE TITLE
Asset PR completed 2 weeks ago. Still not available in wallet.

### ISSUE THREAD

**Issue by headline-design** [trustwallet/assets#21229]
We successfully completed a PR to support Algorand ASA integration in Trust Wallet approx. 2 weeks ago. Can I get a timeline of when we can expect to see the token go live in the wallet? Thank you 

Completed PR: https://github.com/trustwallet/assets/tree/master/blockchains/algorand

**Comment by covain** [comment]
Tokens of type `ALGORAND` are not yet supported in trust app

**Comment by headline-design** [comment]
> Tokens of type `ALGORAND` are not yet supported in trust app

Could you please elaborate on when we can expect the integration to be complete? It's been approximately 3 weeks already with no clear time frame given. Thank you.

**Comment by mohammadj44** [comment]
@mohammadj44#`My Public Address to Receive SOL ExQu5EgsxWriCkhP5xS6kUoCTXD98nStssYTnpbiMRkx

> > Pay me via Trust Wallet: https://link.trustwallet.com/send?coin=501&address=ExQu5EgsxWriCkhP5xS6kUoCTXD98nStssYTnpbiMRkx`

**Comment by covain** [comment]
These guys might know better when ALGORAND token type support is to be added: @ArtemGoryunov @vcoolish

**Comment by vcoolish** [comment]
we don't have plans to support it in near future.
@hewigovens

**Comment by chibong** [comment]
@headline-design to clarify: at Consensus I said I would look into what the status was of the PR review. I did not commit to support Algorand ASAs outright as I thought the issue you were flagging was lack of PR review, not net new network support.

**Comment by headline-design** [comment]
> @headline-design Apologies for any misunderstanding. To clarify: at Consensus I said I would look into what the status was of the PR review. I did not commit to support Algorand ASAs outright as I thought the issue you were flagging was lack of PR review, not net new token support.

Hi Eric, at Consensus we were specifically talking about the mobile Wallet integration. You said it was already possible to add Algorand assets to the mobile wallet, which is why we have been working towards that end. You said specifically, that because Algorand is integrated that ASAs were supported as well. What would the purpose of a PR be if it just lives on GitHub and is not added to the mobile wallet? Why would we pay $700 dollars to put an ASA on a GitHub list? There is no value to that if it's not available in the mobile wallet.

**Comment by headline-design** [comment]
> @headline-design as mentioned above we can’t say the exact release date for that

But you can confirm that it's coming?
