### ISSUE TITLE
Question on token asset listing acceptance guidelines

### ISSUE THREAD

**Issue by gjj** [trustwallet/assets#21499]
## How can we help?

Wanted to ask if the `Minimum 10,000 token holders and 15,000 transactions` requirement is solely based on the ERC-20 or EVM-based version of the token?

To provide some some context:

* [DeFiChain](https://defichain.com) is a fork of Bitcoin (and therefore not EVM-based), and we have a native DeFiChain token (DFI)
* On our native chain, the DFI token would definitely meet those requirements (e.g. verifiable on [DeFiScan](https://defiscan.live))
* We recently had an ERC-20 and BEP-20 representation of the DFI token (and is traded on several exchanges, including Bybit and Kucoin)
* However, EVM-based on-chain transactions would fall short of that particular requirement if only the ERC-20 or BEP-20 transactions/unique holders are considered

Will the team consider our native blockchain's (i.e. not EVM-based) unique holders and transactions for the asset listing process given that we also have the ERC-20 & BEP-20 representation of the token?

The purpose of this is really to have the DFI token logo on existing Uniswap pools e.g. [DFI/USDT](https://v2.info.uniswap.org/pair/0x9e251daeb17981477509779612dc2ffa8075aa8e) since assets are pulled from here.

Thanks a lot!

**Comment by Snowflakes747** [comment]
How do I import multiple token of dogecoin

**Comment by Wayde31** [comment]
> ## How can we help?
> Wanted to ask if the `Minimum 10,000 token holders and 15,000 transactions` requirement is solely based on the ERC-20 or EVM-based version of the token?
> 
> To provide some some context:
> 
> * [DeFiChain](https://defichain.com) is a fork of Bitcoin (and therefore not EVM-based), and we have a native DeFiChain token (DFI)
> * On our native chain, the DFI token would definitely meet those requirements (e.g. verifiable on [DeFiScan](https://defiscan.live))
> * We recently had an ERC-20 and BEP-20 representation of the DFI token (and is traded on several exchanges, including Bybit and Kucoin)
> * However, EVM-based on-chain transactions would fall short of that particular requirement if only the ERC-20 or BEP-20 transactions/unique holders are considered
> 
> Will the team consider our native blockchain's (i.e. not EVM-based) unique holders and transactions for the asset listing process given that we also have the ERC-20 & BEP-20 representation of the token?
> 
> The purpose of this is really to have the DFI token logo on existing Uniswap pools e.g. [DFI/USDT](https://v2.info.uniswap.org/pair/0x9e251daeb17981477509779612dc2ffa8075aa8e) since assets are pulled from here.
> 
> Thanks a lot!

**Comment by Mex505** [comment]
How much assets do I have in my account what is the value in cash dollars
