### ISSUE TITLE
Issue of add contract and show price 

### ISSUE THREAD

**Issue by inmefinance** [trustwallet/assets#21677]
Good day great team 
Our token listing on cmc and cg 
And you can check links through 

https://coinmarketcap.com/currencies/inme-swap-v2/

https://www.coingecko.com/en/coins/inme-swap

But till now price not show app on trust wallet app 
Can help us ?

0xba1063bb72c58d1bde32674fad22174f46837c72

Also we have another issue when our customer add contract not fill for them the info automatically 
They must enter manual 
Kinds REGRDS 
Co founder inme swap

**Comment by Cryptocool1** [comment]
Did you create the Pull request for adding the token?

**Comment by inmefinance** [comment]
Yes
But add the token it’s not part from show price on trust wallet

**Comment by Cryptocool1** [comment]
What is number of your PR?

**Comment by inmefinance** [comment]
We was have old contract and migrate for new one old one have normally show up price but on the new migrate contract price now show up in the trust wallet app
Other places working well

**Comment by Cryptocool1** [comment]
You should create PR with your new contract address

**Comment by inmefinance** [comment]
I did 
And my pr 
21678

**Comment by inmefinance** [comment]
![8966197D-9AAE-4678-AF49-5D38363389DB](https://user-images.githubusercontent.com/107762597/181439110-2b1e5542-7b46-41c9-86b0-4acb500c4e91.jpeg)


This the answer from cmc REGRDS track price

**Comment by Cryptocool1** [comment]
The PR is incorrect, you should follow the instructions I sent and create new PR, and the you can pay the fee.

**Comment by inmefinance** [comment]
but am not speak about listing or add logo I am speak about different case now


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptocool1** [comment]
What case?

**Comment by inmefinance** [comment]
Can check out the photos please

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptocool1** [comment]
You can send the photos here

**Comment by inmefinance** [comment]
![CDA46392-6BBE-417B-9317-A59574741CE5](https://user-images.githubusercontent.com/107762597/181440429-2e06b462-080d-47e6-85fc-0cb938c4428c.jpeg)
![69C0A387-0591-4EE7-9408-07383CB24DD3](https://user-images.githubusercontent.com/107762597/181440438-25777593-c5cc-438f-aeab-2a58401b9642.jpeg)

**Comment by inmefinance** [comment]
Since yesterday it’s not show up price or track data

**Comment by inmefinance** [comment]
On trust wallet app

**Comment by Cryptocool1** [comment]
Because you didn’t create the PR for adding the token. You need to create PR, pay the fee, and if you met our requirements we can accept your token. And then you will see your token and the price on TW app

**Comment by inmefinance** [comment]
But it’s was show before 
I didn’t pay or create pr before and price was show normally 
Because to create pr I must have 10,000 holders and more than 15,000 transfer 
So the price was show normally with our pay fees

**Comment by inmefinance** [comment]
It’s mean we don’t refuse to pay the fees but we need to be sure we are eligible to listing or not before pay the fees
