### ISSUE TITLE
Price not show up 

### ISSUE THREAD

**Issue by inmefinance** [trustwallet/assets#21676]
Good day great team 
Our token listing on cmc and cg 
And you can check links through 

https://coinmarketcap.com/currencies/inme-swap-v2/

https://www.coingecko.com/en/coins/inme-swap

But till now price not show app on trust wallet app 
Can help us ?

0xba1063bb72c58d1bde32674fad22174f46837c72

Also we have another issue when our customer add contract not fill for them the info automatically 
They must enter manual 
Kinds REGRDS 
Co founder inme swap

**Comment by inmefinance** [comment]
Why close with out give answer or fix issue ?

**Comment by Cryptocool1** [comment]
You did the duplicate
