### ISSUE TITLE
there is reports that the price for SPKY is not showing for users on trust wallet. can you please look into this?

### ISSUE THREAD

**Issue by wrennstigator** [trustwallet/assets#21782]
there is reports that the price for SPKY is not showing for users on trust wallet. can you please look into this?

_Originally posted by @wrennstigator in https://github.com/trustwallet/assets/issues/21301#issuecomment-1186010073_

**Comment by Cryptocool1** [comment]
Hello, we are taking the price from CoinMarketCap

**Comment by wrennstigator** [comment]
this unfortunately is not happening. our CoinMarketCap listing is: https://coinmarketcap.com/currencies/spooky-shiba-new/ and there is no price in trust wallet, just a logo.

**Comment by Cryptocool1** [comment]
we will take a look at this

**Comment by Cryptocool1** [comment]
fixed
