### ISSUE TITLE
Token Listing Requirements Review 

### ISSUE THREAD

**Issue by Kofro** [trustwallet/assets#21818]
> As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
> See the criteria at : https://developer.trustwallet.com/assets/requirements .

We meet this requirement @cryptomanz1 @catenocrypt @Iamdeadlyz @covain 

https://www.digifinex.io/en-ww/trade/USDT/AAPT 

https://chainlinkecosystem.com/ecosystem/aaptitude

https://coinmarketcap.com/currencies/aaptitude/historical-data/

![Screenshot_20220805-000802.png](https://user-images.githubusercontent.com/10164925/182868232-0c6ccec3-146a-4864-8a52-7d22fd113ff5.png)

![Screenshot_20220805-000632.png](https://user-images.githubusercontent.com/10164925/182868260-7c030693-41a3-43d2-af44-d119b07a1b30.png)

https://i.imgur.com/fWEZq7U.png

_Originally posted by @Kofro in https://github.com/trustwallet/assets/issues/21811#issuecomment-1205312760_

**Comment by cryptomanz1** [comment]
You have only 3300 holders, please come back to us when all criteria are met.

**Comment by Kofro** [comment]
> You have only 3300 holders, please come back to us when all criteria are met.

Most of our holders are not on BSC, they are on CEX. But they are asking for the logo to be fixed on their TrustWallet app and on AMMs that use this repo.
