### ISSUE TITLE
Please Update Learno (LRT) token LOGO TO trust wallet

### ISSUE THREAD

**Issue by LearnoCoin** [trustwallet/assets#2197]
Please Update Learno (LRT) token LOGO TO trust wallet
Please Update this logo ..Previous Some Upper portal is cut .
Please this logo 

![0x7194BB18C95c638F9b9604C2f20064B66A0de8fE](https://user-images.githubusercontent.com/65890231/83061282-5b833080-a07a-11ea-947a-43448e601dbd.png)

**Comment by kolya182** [comment]
Already added

**Comment by LearnoCoin** [comment]
Please check it ..Upper Portal is cut .two ear .
![WhatsApp Image 2020-05-28 at 12 08 26 AM](https://user-images.githubusercontent.com/65890231/83061695-0d226180-a07b-11ea-974a-159b34b9cb38.jpeg)

**Comment by LearnoCoin** [comment]
![WhatsApp Image 2020-05-28 at 12 10 58 AM](https://user-images.githubusercontent.com/65890231/83062143-d13bcc00-a07b-11ea-90ba-7a0631405b7e.jpeg)


check sir Upper ear cut.show it
