### ISSUE TITLE
Please Update Learno (LRT) token LOGO TO trust wallet

### ISSUE THREAD

**Issue by LearnoCoin** [trustwallet/assets#2200]
Please Update Learno (LRT) token LOGO TO trust wallet
Update this sir Urgent

Token Name : Learno
Token Symbol : LRT
Token Supply : 1,000,000,000 LRT
Token Contract Address : 0x7194BB18C95c638F9b9604C2f20064B66A0de8fE

![0x7194BB18C95c638F9b9604C2f20064B66A0de8fE](https://user-images.githubusercontent.com/65890231/83147182-f3355d00-a114-11ea-9548-10d04282844b.png)

**Comment by LearnoCoin** [comment]
Previous Some Upper portal is cut .
Update this sir Urgent

**Comment by kolya182** [comment]
Updated

**Comment by LearnoCoin** [comment]
thank you sir
