### ISSUE TITLE
Add Insula logo to Trustwallet

### ISSUE THREAD

**Issue by Calum-Insula** [trustwallet/assets#2209]
<img width="82" alt="Squared Logo" src="https://user-images.githubusercontent.com/65359532/83273797-d3f60880-a1c4-11ea-8b42-378c48a9a64b.png">

I have submitted a pull request to add our logo but it has not been approved yet. I have added the logo again here for ease. 

Coin: Insula Token
Contract Address: 0x697ef32b4a3f5a4c39de1cb7563f24ca7bfc5947
Supply: 1,049,675.602077199999701949

**Comment by catenocrypt** [comment]
PR number?  I can't see any PR (open or close) with 'insula'.

**Comment by Calum-Insula** [comment]
Apologies it seems the pull request did not submit. I have created a fork with the logo in the correct location in the folder structure but this is not appearing as a branch (which I need it to in order to submit a PR). Can you advise on how to do this?

**Comment by Calum-Insula** [comment]
Issue has been resolved
