### ISSUE TITLE
Stacking option for bep20 token

### ISSUE THREAD

**Issue by yenky** [trustwallet/assets#22144]
*Is your feature request related to a problem? Please describe.**
- I would like to have a stacking option for ENG CRYPTO Token in a trust wallet. The ENG team has their stacking system and we want to have a stacking
option in the trust wallet. This is not a problem, it's a requirement or a suggestion.
https://bscscan.com/token/0x8a505d5cb3db9fcf404c0a72af3df8be4efb707c

**Describe the solution you'd like**
ENG CRYPTO has their stacking plan like other coins and we want to implement it with trust wallet, So all stacking will be done by trust wallet and
there can be a stacking fee for every users that will go to Trust wallet.

**Describe alternatives you've considered**
Alternatives They are doing their own standalone system already but it would be much better with trust wallet and then We can provide web services for other
token to start their stacking system on trust wallet for BEP20 Tokens

**Additional context**
Please try to get my point and if it required any more explanations i can answer or explain any questions related to this Stacking option

Thank you

**Comment by yenky** [comment]
Hi @cryptomanz1 & @hewigovens 
You guys are doing a great job with trust wallet , may i know how to do this feature with trust wallet.
I want to add a stacking system under ENG CRYPTO Token. I would like to explain more in detail and this will be the best feature in trust wallet because there are Lots of users who are using trust wallets and they love to stack in their favorite token so if trust wallet give this option to tokens that would be great.

Thank you

**Comment by hewigovens** [comment]
How does the staking work? It's standard alone chain or a dapp on bsc?

**Comment by Cryptocool1** [comment]
close because of inactivity

**Comment by yenky** [comment]
Hi [Cryptocool1](https://github.com/Cryptocool1)
I want to reopen this thread , I'm sorry for late reply

Thank you

**Comment by yenky** [comment]
Can we please open this issue because i need to fix it asap.

Thank you
