### ISSUE TITLE
Please add assets for IOTA(MIOTA) token to TrustWallet

### ISSUE THREAD

**Issue by aleks-rad** [trustwallet/assets#22192]
It is currently not possible to find the token IOTA(MIOTA) by name. If you add a token by contract number (0xd944f1D1e9d5f9Bb90b62f9D45e447D989580782), the logo is not displayed. Please add assets for IOTA(MIOTA) token. Perhaps only the developers of the project can do this, so I will mention here @domschiener

**Comment by cryptomanz1** [comment]
https://github.com/trustwallet/assets/pull/22263

**Comment by Seifollahi23** [comment]
0x67AB2De66a7494a96Ea47E66Ae7e9275E80703A0
