### ISSUE TITLE
We have upgraded the contract

### ISSUE THREAD

**Issue by LiteUSD** [trustwallet/assets#22201]
Old LITE contract: 0x4a846d300f793752ee8bd579192c477130c4b369
New LITE contract: 0x3ef3f6cf9f867a33c4109208a6bd043a9ef0e091

We have upgraded the contract. 
Please replace the old contract.

Add LITE (BEP20) #21880

**Comment by Cryptocool1** [comment]
hello, please create Pull Request with new contract

**Comment by LiteUSD** [comment]
The new contract needs 10000 reserved addresses to pull requests? Need to donate TWT again?

**Comment by LiteUSD** [comment]
@Cryptocool1

**Comment by Cryptocool1** [comment]
Hello, yes, you need to pay the fee
