### ISSUE TITLE
Add logo of my projekt token

### ISSUE THREAD

**Issue by openartstudio** [trustwallet/assets#22629]
## How can we help ?

Hello. How Can I add logo of my projekt token?
I have file:
0x6daA1e9CDFe153974761709a091d5665eABC3619.png

Regards
Jacek Kolodziejczak

**Comment by cryptomanz1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/assets/repository_details

**Comment by openartstudio** [comment]
> Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you. See https://developer.trustwallet.com/assets/repository_details

Ok I did it https://github.com/trustwallet/assets/pull/22639 on https://assets.trustwallet.com/
What now? I have to pay? What time my token will be add to TrustWallet?
