### ISSUE TITLE
Setup a notification about STORM token swap

### ISSUE THREAD

**Issue by zachzwei** [trustwallet/assets#2270]
**Is your feature request related to a problem? Please describe.**
See: https://blog.stormtoken.com/token-swap-technicality-19211f23c9b9
The STORM token swap has just been initialized and the swap start date is set for June 8th, 2020

**Describe the solution you'd like**
Show a popup notification when user access the STORM token wallet.
Suggested message:
"The STORM token swap starts on June 8th, 2020."
Learn more: https://blog.stormtoken.com/token-swap-technicality-19211f23c9b9

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by kolya182** [comment]
@zachzwei Will work on this

**Comment by zachzwei** [comment]
Found this article about the token swap:
https://help.stormx.io/hc/en-us/articles/360048712853-StormX-Token-Swap-User-Guide
Also a video for doing it on Trust Wallet:
https://www.youtube.com/watch?v=2cTWdHeNolk
