### ISSUE TITLE
How do I trade my Ella

### ISSUE THREAD

**Issue by sweetpea1328** [trustwallet/assets#22724]

**Comment by Hadijafari1** [comment]
کسی هست بتونه ۱۰ هزار دلار بهم کمک کنه یه مریض دارم تورا خدا اگه میتونید
به آدرس زیر واریر کنید 0x3f3135076fB90c1aeE0B36Adf0d7Ad588765D1

در تاریخ پنجشنبه ۱۳ اکتبر ۲۰۲۲،‏ ۲۰:۴۷ sweetpea1328 <
***@***.***> نوشت:

**Comment by Hadijafari1** [comment]
کسی هست بتونه ۱۰ هزار دلار بهم کمک کنه یه مریض دارم تورا خدا اگه میتونید
به آدرس زیر واریر کنید 0x3f3135076fB90c1aeE0B36Adf0d7Ad588765D1

در تاریخ پنجشنبه ۱۳ اکتبر ۲۰۲۲،‏ ۲۲:۳۹ Nazar ***@***.***>
نوشت:
