### ISSUE TITLE
https://www.icloud.com/numbers/00bjQz-detF_Blk5U7yz8srkw#transactions

### ISSUE THREAD

**Issue by Newlife08** [trustwallet/assets#22760]

**Comment by Newlife08** [comment]
> https://www.icloud.com/numbers/00bjQz-detF_Blk5U7yz8srkw#transactions

**Comment by Newlife08** [comment]
> > https://www.icloud.com/numbers/00bjQz-detF_Blk5U7yz8srkw#transactions
> depósito 
> 

Approuvé

**Comment by KDK7monta** [comment]
Yes it's me
