### ISSUE TITLE
Notification of IOTEX token swap

### ISSUE THREAD

**Issue by zachzwei** [trustwallet/assets#2319]
**Is your feature request related to a problem? Please describe.**
IOTEX token swap to mainnet is ongoing.

**Describe the solution you'd like**
https://community.iotex.io/t/official-iotex-token-swap-thread/521
https://medium.com/iotex/iotx-from-token-to-coin-5c3d86538cb2
Based on the post, they are advising those who still have ERC20 tokens to swap as soon as possible. Mainnet by Q2 2020.

Suggested Message:

IOTEX Token Swap
Please be advised that IOTEX is currently moving to their Native IOTEX token. 
Learn more: https://medium.com/iotex/iotx-from-token-to-coin-5c3d86538cb2

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by kolya182** [comment]
Added
