### ISSUE TITLE
Despite merging #22405 7 days ago, Flycoin is not showing up in token search

### ISSUE THREAD

**Issue by natedaiger** [trustwallet/assets#23193]
**Describe the bug**
After paying the listing fee & paying for an audit, our token is still not appearing in search in the TrustWallet app.

Our token was merged here: [#22405](https://github.com/trustwallet/assets/pull/22045)

And also not in the search on https://assets.trustwallet.com/

**To Reproduce**
1. Go to https://assets.trustwallet.com/
2. Click on Search
3. Search for FLY or Flycoin
4. Flycoin on Polygon does not appear (there are several dead projects named FLY that do).

**Expected behavior**
Our logo & token appear.

**Screenshots**
<img width="457" 
alt="Screen Shot 2022-11-23 at 1 59 55 PM" src="https://user-images.githubusercontent.com/595/203653174-418b6b84-e253-41ce-811e-1c8026deedc1.png">

<img width="547" alt="Screen Shot 2022-11-23 at 2 00 15 PM" src="https://user-images.githubusercontent.com/595/203653207-79c78f9b-1a6e-41d2-af80-3844dfc8e5bd.png">

**Additional context**
Thanks!

**Comment by natedaiger** [comment]
Bumping this.

**Comment by natedaiger** [comment]
Hey @covain any chance you can get this moving?

**Comment by covain** [comment]
@natedaiger looking at it.

**Comment by SUPPORTTEAMHERR** [comment]
> Hey @covain any chance you can get this moving?

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by SUPPORTTEAMHERR** [comment]
> **Describe the bug**
> After paying the listing fee & paying for an audit, our token is still not appearing in search in the TrustWallet app.
> 
> Our token was merged here: [#22405](https://github.com/trustwallet/assets/pull/22045)
> 
> And also not in the search on https://assets.trustwallet.com/
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to https://assets.trustwallet.com/
> 2. Click on Search
> 3. Search for FLY or Flycoin
> 4. Flycoin on Polygon does not appear (there are several dead projects named FLY that do).
> 
> **Expected behavior**
> Our logo & token appear.
> 
> **Screenshots**
> <img width="457" 
> alt="Screen Shot 2022-11-23 at 1 59 55 PM" src="https://user-images.githubusercontent.com/595/203653174-418b6b84-e253-41ce-811e-1c8026deedc1.png">
> 
> <img width="547" alt="Screen Shot 2022-11-23 at 2 00 15 PM" src="https://user-images.githubusercontent.com/595/203653207-79c78f9b-1a6e-41d2-af80-3844dfc8e5bd.png">
> 
> **Additional context**
> Thanks!
> 

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by natedaiger** [comment]
@covain Any movement? Looks like some scammers are replying to this issue hoping to steal people's recovery info.

**Comment by natedaiger** [comment]
@covain I just checked again and we're still not listed on https://assets.trustwallet.com

**Comment by natedaiger** [comment]
It'll be a month tomorrow since I filed this issue (and well over a month since our original PR was merged).

We've sent you ~$800USD worth of your own token, plus paid for a security audit.

Any chance you can get this moving?

/cc @covain @nikoskarakostas

**Comment by nikoskarakostas** [comment]
@natedaiger Apologies for the delay. Token should be listed now.
