### ISSUE TITLE
❌  ❌  low token circulation: number of holders is 3296, below limit of 10000

### ISSUE THREAD

**Issue by sandybradley** [trustwallet/assets#23206]
**Describe the bug**
10000 is an arbitrary number to pick. Why??

**To Reproduce**
Adding FOLD token:
https://assets.trustwallet.com/

0xd084944d3c05CD115C09d072B9F44bA3E0E45921
![image](https://user-images.githubusercontent.com/29037794/203767373-80d4a522-f42a-4f2b-ad2a-aa4c55bd79e0.png)

**Expected behavior**
To be able to add token without arbitrary bias.

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/assets/requirements .

**Comment by sandybradley** [comment]
Thank you for responding :)
I appreciate filters are required for removing scam tokens. Can you tell me how you have arrived at these thresholds?
Manifold has been around over 2 years with very active development. They are one of a handful of block builders on ethereum. I think you should reconsider these numbers.


![image](https://user-images.githubusercontent.com/29037794/203914956-826ef95e-e386-4c3d-accb-c0f389b9dfbe.png)
https://www.mevboost.org/

[github.com/manifoldfinance/](https://github.com/manifoldfinance/)
