### ISSUE TITLE
0349998773

### ISSUE THREAD

**Issue by 0349998773** [trustwallet/assets#23276]

**Comment by 0349998773** [comment]
![image](https://user-images.githubusercontent.com/109808162/205218250-5598e90e-a078-4041-965d-4f8c7b474baa.jpeg)

**Comment by spartacus2690** [comment]
در تاریخ جمعه ۲ دسامبر ۲۰۲۲،‏ ۸:۳۰ 0349998773 ***@***.***>
نوشت:
