### ISSUE TITLE
700.00 TWT have been successfully [burned](https://explorer.binance.org/tx/A7044D0AC3FE7C3E5A8F43D077F803BC7AA148B3E0FEE40AFBE19852A1B0D25F).

### ISSUE THREAD

**Issue by Vicen811226** [trustwallet/assets#23315]
700.00 TWT have been successfully [burned](https://explorer.binance.org/tx/A7044D0AC3FE7C3E5A8F43D077F803BC7AA148B3E0FEE40AFBE19852A1B0D25F).

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/23169#issuecomment-1323499827_

**Comment by Vicen811226** [comment]
> Vicen811226

**Comment by Vicen811226** [comment]
https://github.com/trustwallet/assets/issues/23315#issue-1475984990

**Comment by Vicen811226** [comment]
#
[nft-logo-2000.8c962c50fdfea4dada27.png.pdf](https://github.com/trustwallet/assets/files/10152047/nft-logo-2000.8c962c50fdfea4dada27.png.pdf)

**Comment by Vicen811226** [comment]
Rom

**Comment by Vicen811226** [comment]
![nft-icon-2000 5649759e472d56d60c76](https://user-images.githubusercontent.com/101701160/205587998-ebe11b32-8d25-499e-a80b-60bc20ae8a81.png)

**Comment by Vicen811226** [comment]
[Coinbase_Inc_-_KY_Money_Transmitter_License_-_No_expiration.pdf](https://github.com/trustwallet/assets/files/10152066/Coinbase_Inc_-_KY_Money_Transmitter_License_-_No_expiration.pdf)

**Comment by Vicen811226** [comment]
[nft-icon-2000.5649759e472d56d60c76.png.pdf](https://github.com/trustwallet/assets/files/10152070/nft-icon-2000.5649759e472d56d60c76.png.pdf)

**Comment by Vicen811226** [comment]
[Coinbase_Inc_-_KY_Money_Transmitter_License_-_No_expiration.pdf](https://github.com/trustwallet/assets/files/10152081/Coinbase_Inc_-_KY_Money_Transmitter_License_-_No_expiration.pdf)

**Comment by Vicen811226** [comment]
![nft-logo bb498f4118344c67b997be800b9a2df2](https://user-images.githubusercontent.com/101701160/205588498-aced03da-8e80-4bdc-a69e-bdb2aca4dd53.svg)

**Comment by Vicen811226** [comment]
[Uploading Coinbase-Exchange-Overview-Oct-2021.pdf…]()

**Comment by Vicen811226** [comment]
![descarga](https://user-images.githubusercontent.com/101701160/205588645-f900dcfa-ba81-4d9f-8023-07c5569a4179.png)

**Comment by Vicen811226** [comment]
[nft-icon-2000.5649759e472d56d60c76.png.pdf](https://github.com/trustwallet/assets/files/10152094/nft-icon-2000.5649759e472d56d60c76.png.pdf)

**Comment by Vicen811226** [comment]
![nft-logo bb498f4118344c67b997be800b9a2df2](https://user-images.githubusercontent.com/101701160/205588785-24c61950-3160-45a9-9138-21187cf6a52c.svg)

**Comment by Vicen811226** [comment]
![Uploading nft-logo-2000.8c962c50fdfea4dada27.png…]()

**Comment by Vicen811226** [comment]
https://github.com/trustwallet/assets/issues/23315#issue-1475984990

**Comment by Vicen811226** [comment]
Egg

**Comment by Vicen811226** [comment]
Rome

**Comment by Vicen811226** [comment]
Se

**Comment by Vicen811226** [comment]
Gracias

**Comment by Vicen811226** [comment]
Génesis

**Comment by carlexos** [comment]
>         700.00 TWT have been successfully [burned](https://explorer.binance.org/tx/A7044D0AC3FE7C3E5A8F43D077F803BC7AA148B3E0FEE40AFBE19852A1B0D25F).
> 
> _Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/23169#issuecomment-1323499827_
>       

Quote  reply
