### ISSUE TITLE
Update a logo that was pulled wrong in the trust wallet, I will explain my request

### ISSUE THREAD

**Issue by Danillo17** [trustwallet/assets#2332]
https://etherscan.io/token/0xbb1fa4fdeb3459733bf67ebc6f893003fa976a82 

updade logo
![xpat](https://user-images.githubusercontent.com/35893026/84396215-a6518c00-abd4-11ea-8ac2-4c78f126ece9.png)

and rename to Bitnation (XPAT) .
if you notice is the logo of this token below called patron, I believe that the error occurred in the creation of the trust wallet because the names are similar, that is, it is not an update request, it is an exceptional request
https://etherscan.io/token/0xF3b3Cad094B89392fcE5faFD40bC03b80F2Bc624

**Comment by kolya182** [comment]
https://github.com/trustwallet/assets/pull/2330#issuecomment-642916138
