### ISSUE TITLE
Trust wallet imported wrong logo 

### ISSUE THREAD

**Issue by Danillo17** [trustwallet/assets#2334]
Sorry, but i have try and explain again.

this case is exceptional because it is that the trust itself imported the logo in the creation of the app, so I understand that the fee is not necessary.

but if they still understand the lack of cause that they at least leave without the wrong logo, I still saw it on the app.

https://etherscan.io/token/0xbb1fa4fdeb3459733bf67ebc6f893003fa976a82

updade logo
xpat

and rename to Bitnation (XPAT) .
if you notice is the logo of this token below called patron, I believe that the error occurred in the creation of the trust wallet because the names are similar, that is, it is not an update request, it is an exceptional request
https://etherscan.io/token/0xF3b3Cad094B89392fcE5faFD40bC03b80F2Bc624

**Comment by kolya182** [comment]
You see it for this reason https://github.com/trustwallet/assets#why-do-i-still-see-old-logo-in-trust-wallet-after-uploaded-new-one

Here is what you need to do
1. Create PR uploading your logo

We can't process your request to change token name for reasons:
1. Token name embedded in smart contract
2. Your new proposed name is totally different compare to existing

**Comment by Danillo17** [comment]
We don t want rename, Sorry If you understood another thing, i Will try again
