### ISSUE TITLE
 Please read this, Just remove wrong logo that trust wallet made

### ISSUE THREAD

**Issue by Danillo17** [trustwallet/assets#2336]
https://github.com/trustwallet/assets/issues/2335#issue-637360377

Please read this, Just remove wrong logo that trust wallet made

**Comment by Danillo17** [comment]
![IMG_20200611_215654](https://user-images.githubusercontent.com/35893026/84453592-96669600-ac2e-11ea-8859-0762c81fba64.jpg)


Here the proof, print trust wallet, wrong logo another token PAT

**Comment by Danillo17** [comment]
Repair two mustaches, almost the same logo.
Something its wrong

**Comment by kolya182** [comment]
Already told you, stop spamming

**Comment by Danillo17** [comment]
@kolya182 Sorry If you understood How spam.

Now i see clear cash

**Comment by Danillo17** [comment]
![Screenshot_2020-06-11-22-13-18-844_org telegram messenger](https://user-images.githubusercontent.com/35893026/84454385-ca42bb00-ac30-11ea-9aa8-6d46c1bc1bf5.jpg)

**Comment by kolya182** [comment]
Stop it

**Comment by Danillo17** [comment]
Without logo, ok thanks.

@kolya182 to update do i need open a pr, right?

**Comment by Danillo17** [comment]
I Will stop bother you, now we  have to create a PR if understood right.

Bye, good night

**Comment by Danillo17** [comment]
I Will stop bother you, now we  have to create a PR if understood right.

Bye, good night @kolya182
