### ISSUE TITLE
Incorrect APR calculation for Terra Classic

### ISSUE THREAD

**Issue by iicc1** [trustwallet/assets#23379]
**Describe the bug**
Trustwallet displays a staking APR of 300-600% while the actual value is less than 20%. This confuses users since they expect more rewards with that APR.

**To Reproduce**
1. Go to 'Terra Classic (LUNC)'
2. Click on 'Stake'
3. Click on 'Stake' again
4. See the incorrect APR in most validators

**Expected behavior**
The staking APR of Terra Classic should be 16%.

**Comment by cryptomanz1** [comment]
Could you send a screenshot and version app

**Comment by iicc1** [comment]
It's version 6.57.1 for Android. It looks like this bug is quite common since we are Terra Classic validators and many users come to us every day asking about the Trustwallet APR value

Screenshot:
![image](https://user-images.githubusercontent.com/13121233/207665891-a2664944-0417-4fd2-a9cf-a49c8797cd1c.png)

**Comment by vcoolish** [comment]
update your app

**Comment by CraftyDlx** [comment]
This issue also persists on iOS, latest version and latest version of the TrustWallet app. There is no update in the Apple store available yet. Did you fix this error on the iOS app as well?

**Comment by CraftyDlx** [comment]
Issue still not fixed for iOS. It's known for months now that this error persists. You're going for the award for the most sloppy and ignorant dev team in crypto world?
