### ISSUE TITLE
### PR Summary

### ISSUE THREAD

**Issue by Shai69bb** [trustwallet/assets#23374]
### PR Summary
Files OK: 2
Token in PR: **BEP2** 0x4E5b0d5633fAC752ffd01Ec626aA303957ddea53
Symbol: **DTO** decimals: 18
Links: [Logo](https://raw.githubusercontent.com/DjTitus/assets/br1214-070610/blockchains/binance/assets/0x4E5b0d5633fAC752ffd01Ec626aA303957ddea53/logo.png) [Info](https://raw.githubusercontent.com/DjTitus/assets/br1214-070610/blockchains/binance/assets/0x4E5b0d5633fAC752ffd01Ec626aA303957ddea53/info.json) [Website]() [Explorer](https://explorer.binance.org/asset/0x4E5b0d5633fAC752ffd01Ec626aA303957ddea53)
Tags: 
Token check error: 
failed to get logo dimensions: failed to decode config: png: invalid format: not a PNG file
❌ missing required fields: website field
❌ at least 2 links are required, 1 present. Add as many as you can: twitter, github, telegram, reddit, etc
❌ at least 1 tag is required
❌ number of holders not checked: please, check it manually
❌ missing required fields: description

<span style="padding: 5px; background-color: rgb(32,32,32);"><img src="https://raw.githubusercontent.com/DjTitus/assets/br1214-070610/blockchains/binance/assets/0x4E5b0d5633fAC752ffd01Ec626aA303957ddea53/logo.png" style="max-width: 64px; border-radius: 48%;" width="48" height="48"/></span>

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/23373#issuecomment-1350449808_

**Comment by Shai69bb** [comment]
Do I need to fix all of those issues listed above in order for this to pass?

**Comment by cryptomanz1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/assets/requirements
See https://developer.trustwallet.com/assets/repository_details
