### ISSUE TITLE
the logo having white borders need to be removed 

### ISSUE THREAD

**Issue by intuzpro** [trustwallet/assets#2348]
please remove the white borders from the logo 
thanks 

_Originally posted by @kolya182 in https://github.com/trustwallet/assets/pull/2346#issuecomment-643479368_

**Comment by intuzpro** [comment]
![WhatsApp Image 2020-06-13 at 12 50 06 AM](https://user-images.githubusercontent.com/66847225/84546147-af944300-ad11-11ea-9668-3dd91b9d3ce3.jpeg)

we need the logo without the white borders

**Comment by kolya182** [comment]
Please read requirements before
