### ISSUE TITLE
Trust wallet logo approval issue

### ISSUE THREAD

**Issue by yenky** [trustwallet/assets#23488]
## How can we help ?

Hi Trust wallet team  https://github.com/trustwallet

I have a issue here with approving one token logo. Token has nice liquidity and they are doing good and it's on Polygon Blockchain. We have paid the fee and submitted all the documents. Now issue /reason got raised that it should be on cmc listed but CMC says it should be trust wallet listed. I don't know what to do and all the users are waiting for trust wallet to get it done so we can go ahead with CMC.

And if this is the conditions then there are lots of token getting list every day on trust wallet without CMC so what process we should follow and how to make a report about it or how to get the di list from trust wallet because its not fair with trust wallet customers. 

Let me send you the list of token which should get de-active from trust wallet as per the rules.
ARTC -
https://www.dextools.io/app/en/bnb/pair-explorer/0xea6c8badd1682ede63883947589ea8df68842442

CGB -
https://www.dextools.io/app/en/bnb/pair-explorer/0xbfb2daf6cbef301f93ac18240ab2b3603e601119

There are many more so please let me know how they got approved with same thing. Also please let me know what process we need to do to make complain about this.

We have been asked from cmc to get logo done from trust wallet and you are asking us to get the cmc , so we are confused what to do.

Thank you

**Comment by yenky** [comment]
@Crypter2021 @Cryptoastio @Cryptocool1

**Comment by Cryptocool1** [comment]
We have ready send you our requirements. 
https://developer.trustwallet.com/assets/requirements
 one back to us once all criteria are met!

**Comment by yenky** [comment]
Hi @Cryptocool1 
Thank you for responding but i just want to know why this double behavior with my PR . I think i deserve to know about this thing. When there are lots of token getting done on trust wallet without CMC then how come suddenly this rules jumped for my PR.
Thank you
