### ISSUE TITLE
is there any way to know who made the previous submission?

### ISSUE THREAD

**Issue by danillodev** [trustwallet/assets#2352]
is there any way to know who made the previous submission?
I ask why there was a token with the wrong logo, just because the name was similar.

I would like to know who did it in a previous period because it does not seem to have been by chance.

regardless of the cause if it was someone real or not it would be good to know

And the curious thing is that it had the logo of a token with a similar name, so i'm trying to find the way. I believe it was an automatic command from the initials of the token in the programming code of the trust. whether or not it was just looking for clarification.
I think it was a different period of management than how things are now in the trust.
I want to make it clear, I don't want to change the rules. now it is a mixture of curiosity to know how it happened in the past.
I respect you and I don't want to change anything for now

Best Regards.

**Comment by kolya182** [comment]
Be specific about coin you ask

**Comment by danillodev** [comment]
About Pangea Arbitration Token

i found two things
https://github.com/trustwallet/assets/blob/0a1ef5da14621fdf8a46e17da6ca9d0b2662d3a3/blockchains/ethereum/blacklist.json - this link with practically daily change called blacklist I suppose they are the tokens that have no image.

https://github.com/trustwallet/trust-api/blob/a41d2da25221940e9a672683e15abf22a4af210f/src/common/tokens/contracts.ts - this is a 2018 import with tokens existing at the time with export const contracts
committed on 10 Aug 2018 

maybe the x of the question is there, because there are 2 tokens called patron in the same period, they were automatically pulled or even the responsible ones of the other token went up without looking at the contract and only the acronym, if there is no way to know.

being one of those things that I cited better to close the case and I will not bother on this subject because it is increasingly difficult to understand the origin.
and yes, when I need to update something again I will open a PR normally as it should be in the normal procedure. I do respect it and I know how hard all of you are to maintain the quality of the system, sorry about anything.

Best Regards

[test.pdf](https://github.com/trustwallet/assets/files/4775669/test.pdf)

**Comment by kolya182** [comment]
Make PR, will review
