### ISSUE TITLE
trustwallet/assets

### ISSUE THREAD

**Issue by uzogoduyah** [trustwallet/assets#23576]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mariuszok12** [comment]
Mariusz

**Comment by Usernamethoma** [comment]
@uzogoduyah We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9
