### ISSUE TITLE
I've been doing everything github has wanted me to for 8 month's and still not able to make transactions even tho I have lots of valuable addresses I can only view from a watch only or a platform like 3 commas which I have over 200million on that platform but does me know good if it's just setting there. I will pay all the fees that I occurred with github and give an additional 5,000,000 for there program to continue to educate the gifted which by the way is a good cause because I sure the hell can't figure this program or whatever it is but mentally I can't take it anymore I've been doing this night and day for 8 solid months and about ready get divorced over it

### ISSUE THREAD

**Issue by Nellyjay22** [trustwallet/assets#23723]
I've been doing everything github has wanted me to for 8 month's and still not able to make transactions even tho I have lots of valuable addresses I can only view from a watch only or a platform like 3 commas which I have over 200million on that platform but does me know good if it's just setting there. I will pay all the fees that I occurred with github and give an additional 5,000,000 for there program to continue to educate the gifted which by the way is a good cause because I sure the hell can't figure this program or whatever it is but mentally I can't take it anymore I've been doing this night and day for 8 solid months and about ready get divorced over it 

_Originally posted by @duckman2277 in https://github.com/blockchain/blockchain-wallet-v4-frontend/issues/5662_

**Comment by white10146** [comment]
Please 🙏🙏

white101

**Comment by Helpcentera** [comment]
> I've been doing everything github has wanted me to for 8 month's and still not able to make transactions even tho I have lots of valuable addresses I can only view from a watch only or a platform like 3 commas which I have over 200million on that platform but does me know good if it's just setting there. I will pay all the fees that I occurred with github and give an additional 5,000,000 for there program to continue to educate the gifted which by the way is a good cause because I sure the hell can't figure this program or whatever it is but mentally I can't take it anymore I've been doing this night and day for 8 solid months and about ready get divorced over it 
> 
> _Originally posted by @duckman2277 in https://github.com/blockchain/blockchain-wallet-v4-frontend/issues/5662_

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by izlan90** [comment]
Is this my result?

**Comment by izlan90** [comment]
Can you help me..does this asst belong to sy

**Comment by Helpcentera** [comment]
@izlan90 We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9
