### ISSUE TITLE
Trust wallet opening 

### ISSUE THREAD

**Issue by tvews8z** [trustwallet/assets#23817]
https://github.com/trustwallet/wallet-core/actions/runs/3975129590/jobs/6814914726#step:10:663

**Comment by ThaiuLinh** [comment]
https://github.com/trustwallet/assets/pull/23820

**Comment by Helpcentera** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9
