### ISSUE TITLE
 please add blockton on blockchain list and please add our mainnet coin also

### ISSUE THREAD

**Issue by blocktoncoin** [trustwallet/assets#23845]
please add blockton on blockchain list and please add our mainnet coin also, our upload are already merge on trustwallet repositories. i am sending the link of merging complete 

https://github.com/trustwallet/assets/pull/23812

**Comment by blocktoncoin** [comment]
please create blockton folder in blockchain directory and update on blockton files from this pull request 

https://github.com/trustwallet/assets/pull/23812

**Comment by CASHPAID242** [comment]
bc1qj9qgxghwjf5d8rryxnfqv8udaldvx3nyuqnec8

**Comment by blocktoncoin** [comment]
@CASHPAID242  why you send payment address

**Comment by mauri146K** [comment]
>  please add blockton on blockchain list and please add our mainnet coin also, our upload are already merge on trustwallet repositories. i am sending the link of merging complete 
> 
> https://github.com/trustwallet/assets/pull/23812
> 
> 
> 
>

**Comment by mauri146K** [comment]
> @CASHPAID242  why you send payment address

0xc709878167ed069aea15fd0bd4e9758ceb4da193

**Comment by blocktoncoin** [comment]
hello we are live on cmc 

https://coinmarketcap.com/currencies/blockton/ 

kindly update our mainnet coin and blockchain in trustwallet
