### ISSUE TITLE
How can I blacklist our old toke?

### ISSUE THREAD

**Issue by advexon** [trustwallet/assets#2387]
We updated our token to a new token after changing some codes in the contract. I couldn't blacklist our previous token. Is there any tutorial or explanation of blacklisting token?
0x1cdca6811e2ef23d6099d09d2754211d3c7b5af1 this is the contract of our old token. The logo was updated by me and I am the owner of the contract.

**Comment by kolya182** [comment]
What is the new contract address ?

**Comment by kolya182** [comment]
@kolya182 Old contract depreciation procedure will be adde in next couple of days,
