### ISSUE TITLE
glance robot erosion entry upon garment language quiz collect outdoor setup harvest pencil measure jazz wrestle happy mushroom tray table project pencil toast curtain

### ISSUE THREAD

**Issue by OlawaleSC23** [trustwallet/assets#24166]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Bspring305** [comment]
دستگاه: redmi pro10
سیستم عاملandroid13
مرورگر chrome 
نسخه [ 22]
