### ISSUE TITLE
Need PR #24394 merged to complete Migration. Please help.

### ISSUE THREAD

**Issue by PEEPScoin** [trustwallet/assets#24450]
Hello, payment was sent. 

https://explorer.binance.org/tx/BF76147CA139852854B79F48B4539C35DD23889AD4A05F4AED9F9C21DA32CB9A

The People's Coin (PEEP$)  has officially migrated our token smart contract and needs to update our TrustWallet GitHub as well so it sources appropriately for TW and CB Wallet users alike, among all other things that connect with TW; as you can see in this email thread, we worked with you to add our previous token smart contract to the TW GitHub. Hopefully the info provided below is what you need to help us, but please let us know if there is anything else we need to provide so we can submit it ASAP. 

Updated Token Smart Contract: 0x5919DeA604631016c15c805e3D948A0384879892

Updated Token Smart Contract on Ethersca.io: 
https://etherscan.io/token/0x5919DeA604631016c15c805e3D948A0384879892

OLD Token Smart Contract page on Etherscan.io that is already updated with "Token Migration Announcement"  and the link to the updated Etherscan.io page: 
https://etherscan.io/token/0xe1030b48b2033314979143766d7dc1f40ef8ce11

Link to "Token Migration Announcement" as listed on Etherscan.io: https://medium.com/@PeepsChamp/the-peoples-coin-official-smart-contract-migration-re-launch-316bd4a5fd54

We airdropped all holders their exact same value of tokens prior to officially Re-Launching on June 16, 2023. We still have the same mission statement, but have not only grown, but also instituted several improved features, initiatives, and functionality for the project as we continue to grow.

Additional Info:

LinkTree: https://linktr.ee/thepeoplescoin

Website : https://thepeoplescoin.money/

Telegram:[ https://t.me/thepeoplescoinofficial](https://t.me/thepeoplescoinofficial)

Twitter: https://twitter.com/ThePeoples_Coin

Facebook: https://www.facebook.com/groups/thepeoplescoin1

CoinMarketCap: (updating in progress) https://coinmarketcap.com/currencies/the-peoples-coin/

CoinGecko: (updating in progress) https://www.coingecko.com/en/coins/the-people-coin

Github: https://github.com/PEEPScoin

Uniswap: https://v2.info.uniswap.org/token/0x5919dea604631016c15c805e3d948a0384879892

View on Dextools.io: https://www.dextools.io/app/en/ether/pair-explorer/0xfdd0f179ae8f71e55a5aa5c39b336dda63fb17d7

![Logo](https://user-images.githubusercontent.com/86336210/227111001-bf8fe1f9-ab32-47ff-a7b7-20d991fcdbe3.png)

_Originally posted by @PEEPScoin in https://github.com/trustwallet/assets/issues/24394#issuecomment-1480619846_

**Comment by Cryptocool1** [comment]
Hello, I asked you to create new PR and sent you instructions because your pull request was incorrect
