### ISSUE TITLE
JESUSisLORD LUNC Validator on Android not showing up as "active"

### ISSUE THREAD

**Issue by ChristopherWHarris** [trustwallet/assets#24520]
Hi my Luna Classic (LUNC) validator was just added to Trust Wallet yesterday with my pull request merged. However it shows up as "inactive" in the list on Android mobile. It shows up as "active" on Trust Wallet on iphone. 

I have reloaded the app, restarted my phone, cleared cache but my validator still appears as "inactive" on Trust Wallet Android. This is a problem as people won't select my validator if it is shown as inactive.

Despite being listed as inactive, I tested by delegating numerous times and my stake through Trust Wallet Android to JESUSisLORD was successful and is collecting rewards. So I am wrongly appearing in the inactive list.

My validator is active you can see on the list at #16 here https://terraclassic.stakebin.io/terra/validators

Could you please fix this problem so I can be on the active list and advise me?

Regards, Christopher
JESUSisLORD LUNC Validator

![Screenshot_20230331-090100_Trust Wallet](https://user-images.githubusercontent.com/127362366/229036302-8977bde8-83cf-4dab-944f-a1ba4a2b184e.jpg)

**Comment by Cryptocool1** [comment]
@vcoolish

**Comment by vcoolish** [comment]
will be fixed in next release

**Comment by ChristopherWHarris** [comment]
@vcoolish thank you very much!
