### ISSUE TITLE
I paid 2 days ago to add my logo to uniswap but I cant see it yet?

### ISSUE THREAD

**Issue by ferrocker** [trustwallet/assets#2484]
## How can we help ?

Logo paid 2 days ago but not added yet to uniswap

Ethereum token
Contract Number:
0x8266897d3044a030f1fca81f18c9ad2daf9e5f09
![Ethereum Token logo](https://user-images.githubusercontent.com/36880928/85721654-68f5ff80-b6a6-11ea-9a7b-5cb58dba2c2e.png)

**Comment by catenocrypt** [comment]
Please provide payment TXID, or the number of the PR to which it was paid, or at least the token name!

**Comment by catenocrypt** [comment]
PR #2464

**Comment by ferrocker** [comment]
TOKEN NAME: ETHEREUMtoken
CONTRACT ID: 0x8266897d3044a030f1fca81f18c9ad2daf9e5f09

PAYMENT TX ID:
https://explorer.binance.org/tx/332710EE6A186406D5ECE038F64AA9EB33F33518B4D9BC233BF88EE2FBFCEAA3
memo 2464

**Comment by ferrocker** [comment]
Just add the logo as soon as possible, thanks

**Comment by ferrocker** [comment]
Why you guys take too long to answer

**Comment by ferrocker** [comment]
Answer me, or where I can go to put a complaint about this

**Comment by ferrocker** [comment]
3 days is a lot of time, why you doing this

**Comment by ferrocker** [comment]
Are you going to answer or you going to steal my payment?

**Comment by ferrocker** [comment]
> PR #2464

Can you help me?

**Comment by ferrocker** [comment]
I did what you said yesterday, I provided you the tx payment ID and the
logo, why ylu haven't added the logo to my token yet?

**Comment by catenocrypt** [comment]
I can only repeat previous advice:
Please follow correct submission guidelines.
https://community.trustwallet.com/t/how-to-submit-a-new-token-asset/3863/2

Your previous pull request was unusable, due to: not created from latest, contained many other changed, logo wrong size.
Please create a new, fresh PR.  You will not need to pay again, payment to PR #2464 can be moved over.

Please don't create the same issue in different repositories.

https://github.com/trustwallet/assets/pull/2464

**Comment by ferrocker** [comment]
if you not goint to help me please refund me my payment

**Comment by ferrocker** [comment]
nooooo way, pay again?

**Comment by ferrocker** [comment]
thats nonesessss

**Comment by ferrocker** [comment]
men!!! this company is turning scam!!!!

**Comment by ferrocker** [comment]
SCAMMERREEEEESSSSSSSSSSSSSSSSSSSS

**Comment by catenocrypt** [comment]
> nooooo way, pay again?

No, you misread it.  Please read it again.

**You will not need to pay again**

<img width="221" alt="image" src="https://user-images.githubusercontent.com/13562139/85900508-40821880-b800-11ea-977b-ab883c92ae2a.png">

Please notice the 'not' word.

https://github.com/trustwallet/assets/issues/2484#issuecomment-650259802

**Comment by ferrocker** [comment]
My mistake sorry, Now I'm trying to create another pulling request but it
don't let me because a previous one are still there

**Comment by catenocrypt** [comment]
@ferrocker , please provide a BNB/TWT address for refund payment (I think the address you sent from is an exchange address, I cannot return there).
