### ISSUE TITLE
Add Ethwidget (EWDG2) token LOGO TO trust wallet 

### ISSUE THREAD

**Issue by Ethwidget-project** [trustwallet/assets#2523]
Add Ethwidget (EWDG2) token LOGO TO trust wallet 

Token Name : Ethwidget 
Token Symbol : EWDG2
Token Supply : 7,300,000 EWDG2
Token Contract Address : 0xB08F303E5e30d8bd50cB991dB07A55C506e61F23

![0xB08F303E5e30d8bd50cB991dB07A55C506e61F23](https://user-images.githubusercontent.com/67558206/86016524-7f9eac80-ba40-11ea-8933-5842e33c8d39.png)

**Comment by Ethwidget-project** [comment]
already payment is done sir 9E423AFDA4F784C5E192780E3C51911BB1D7C9836CFAC43F6697DD5C100E2317

**Comment by zachzwei** [comment]
merged
https://github.com/trustwallet/assets/pull/2519

**Comment by Ethwidget-project** [comment]
when display logo sir
