### ISSUE TITLE
Merge-fee-bot issue

### ISSUE THREAD

**Issue by Cryptocool1** [trustwallet/assets#25604]
Merge-fee-bot issue

Issues: 
• there are no requests for payment from the bot.
• doesn’t check new pull requests(no messages from him)
• doesn’t add a label about payment

**Comment by Cryptocool1** [comment]
example https://github.com/trustwallet/assets/pull/25595
(no messages from the bot)

**Comment by Cryptocool1** [comment]
example of expected behavior: https://github.com/trustwallet/assets/pull/25452

**Comment by cryptomanz1** [comment]
resolved
