### ISSUE TITLE
Merged PR -but no logo update

### ISSUE THREAD

**Issue by Amirahmspwrr** [trustwallet/assets#25694]
Hello dear support team 

I created a PR regarding to update info&logo for a token , it's merged but the new logo and information not added yet , how can we fix it ? #25687 is the pr number

**Comment by white10146** [comment]
You really need to re merged them again and make sure you upload an appropriate logo in a good other and make sure you follow their instructions.. Thanks

**Comment by Amirahmspwrr** [comment]
Sure i can make a new PR , but i doubt if admins merge it . It requires 500 TWT fee each time. @Cryptocool1 can i make a new PR? And you whitelist me from paying the fee again?

**Comment by Cryptocool1** [comment]
Please update your app. Everything looks good from our side
