### ISSUE TITLE
Update &  Accept Our erc20 Token CoinVisa from Trust wallet

### ISSUE THREAD

**Issue by coinvisa** [trustwallet/assets#2609]
Update &  Accept Our erc20 Token CoinVisa from Trust wallet
Support erc20 token .

Token Name	: CoinVisa
Symbol		: CVS
Decimals	: 18
Total Supply	: 1,000,000,000 CVS
Contract Address: 0xdb56448fe2635f7912287cd619e7ed3d93180f25

![logo-media-cta-250x250](https://user-images.githubusercontent.com/53531127/79576646-3eedf300-80e1-11ea-9357-06c61c5eda86.png)

**Comment by zachzwei** [comment]
Please follow this guide to properly submit a new asset.
https://community.trustwallet.com/t/how-to-submit-a-new-token-asset/3863/2
