### ISSUE TITLE
Add Miraz token Token logo to Trust wallet

### ISSUE THREAD

**Issue by mirazuno** [trustwallet/assets#2622]
Add Miraz token Token logo to Trust wallet

Token Name : Miraz token
Token Symbol : MRZ
Total Supply: 1,000,000 MRZ
Decimals: 18
Token Contract: 0xe571519185098b2f4914ca973d48c090426d69ee

![0xe571519185098b2f4914ca973d48c090426d69ee](https://user-images.githubusercontent.com/67769027/86564571-11983f00-bf84-11ea-9d96-6317b57c50ce.png)

**Comment by zachzwei** [comment]
Please follow this guide to submit the new asset.
https://community.trustwallet.com/t/how-to-submit-a-new-token-asset/3863/2
