### ISSUE TITLE
closed PR without conclusion

### ISSUE THREAD

**Issue by Brag2gr8** [trustwallet/assets#26412]
Requested a refund for #3800 but PR got closed without merging token and without refunding back my money

**Comment by Brag2gr8** [comment]
this is the unresolved transaction. https://explorer.bnbchain.org/tx/3301F00EFDF3D52911366C582EF953D3C757CD08DDFD9C8B7F29BBB5FEC3F893

can I get my token back??

**Comment by Cryptocool1** [comment]
We do not make a refund. You should follow our instructions

**Comment by Brag2gr8** [comment]
@Cryptocool1 Did you check the PR or you just closed my request because you have the power to. Back when I opened the PR didn't see anything like "We do not make a refund". why bringing that up now??
