### ISSUE TITLE
BOBC has the wrong decimals

### ISSUE THREAD

**Issue by belactriple9** [trustwallet/assets#26566]
The [BOBC](https://github.com/trustwallet/assets/blob/be525d1a31d5263a3f7143dd2cefdeaeea24b9bb/blockchains/smartchain/assets/0xCE6bD1833BD077f62B2c1F9a777bB829801d6811/info.json#L5) token reports 16 decimals here but [should have 18](https://bscscan.com/address/0xCE6bD1833BD077f62B2c1F9a777bB829801d6811#readContract#F3)

**Comment by Cryptocool1** [comment]
Hello, thank you for letting us know. We will fix it.
