### ISSUE TITLE
AirDAO (AMB) icon update

### ISSUE THREAD

**Issue by ohhmygithub** [trustwallet/assets#26563]
Trust Wallet support AirDAO (https://airdao.io/) as a custom chain with its native AMB token.
Layer 1, EVM compatible blockchain AMB-NET which was previously known as Ambrosus (https://ambrosus.io/).

Network Name: AMB-NET, AirDAO, etc.
RPC URL: https://network.ambrosus.io
Chain ID: 0x414e
Explorer: https://airdao.io/explorer/

The issue is that Trust Wallet doesnt load brand icon of AirDAO as a default icon for AMB-NET and AMB token.

<img width="377" alt="issue" src="https://github.com/trustwallet/assets/assets/79647053/d68f9c78-dde1-40fb-aafc-40f09ef1c955">

Can you update icon with this:

https://airdao.io/static/media/logo-symbol.db2ba0bcf692b6a44f6a594360924168.svg

I also attached them as PNG and JPEG files.

![AirDAO](https://github.com/trustwallet/assets/assets/79647053/8ea8bbd7-eb15-4fe7-83cb-36cb103da2db)
![AirDAO](https://github.com/trustwallet/assets/assets/79647053/4f01b680-71d9-4dc0-9d85-dad6633c3b8d)

**Comment by Wadey9111** [comment]
Update

**Comment by joaung77** [comment]
0x610a68c731ed54e3070146023cb6527f6b6819e03dc3f8acfca192c7a9fb1d35

**Comment by joaung77** [comment]
0x47a6Ce8609fC95C3871e161349d846e09AB69bb3

**Comment by jenyabb** [comment]
К

**Comment by Billiej88** [comment]
> Trust Wallet support AirDAO (https://airdao.io/) as a custom chain with its native AMB token. Layer 1, EVM compatible blockchain AMB-NET which was previously known as Ambrosus (https://ambrosus.io/).
> 
> Network Name: AMB-NET, AirDAO, etc. RPC URL: https://network.ambrosus.io Chain ID: 0x414e Explorer: https://airdao.io/explorer/
> 
> The issue is that Trust Wallet doesnt load brand icon of AirDAO as a default icon for AMB-NET and AMB token.
> 
> <img alt="issue" width="377" src="https://private-user-images.githubusercontent.com/79647053/273847978-d68f9c78-dde1-40fb-aafc-40f09ef1c955.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjU0NjUsIm5iZiI6MTcwNTA2NTE2NSwicGF0aCI6Ii83OTY0NzA1My8yNzM4NDc5NzgtZDY4ZjljNzgtZGRlMS00MGZiLWFhZmMtNDBmMDllZjFjOTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEzMTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNzM2NzFhNjUzMWQ0N2RlMDg5NjVlZjVmYWFmZWU1NjAxMGU4ZTM4YzQ1YTNlZjBmN2ZlY2I2Y2QwNTdlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uUjkChOLDvrooiDzxMz_ivVk06i-BFopVqMWx_3ZWUk">
> Can you update icon with this:
> 
> https://airdao.io/static/media/logo-symbol.db2ba0bcf692b6a44f6a594360924168.svg
> 
> I also attached them as PNG and JPEG files.
> 
> ![AirDAO](https://private-user-images.githubusercontent.com/79647053/273846180-8ea8bbd7-eb15-4fe7-83cb-36cb103da2db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjU0NjUsIm5iZiI6MTcwNTA2NTE2NSwicGF0aCI6Ii83OTY0NzA1My8yNzM4NDYxODAtOGVhOGJiZDctZWIxNS00ZmU3LTgzY2ItMzZjYjEwM2RhMmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEzMTI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMGQ2MzJiODlmYzg2ZmFlNzQ0OWE5ZWYwMzQ1NGQ1NDJmMjliY2Y1OWI1NjE2NjJjMzZjYTEyNWRlZWIyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d624ftt2TV6VWULzZh6LwYmmifQdRc3p2pLMtFEm2q0) ![AirDAO](https://private-user-images.githubusercontent.com/79647053/273846212-4f01b680-71d9-4dc0-9d85-dad6633c3b8d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNjU0NjUsIm5iZiI6MTcwNTA2NTE2NSwicGF0aCI6Ii83OTY0NzA1My8yNzM4NDYyMTItNGYwMWI2ODAtNzFkOS00ZGMwLTlkODUtZGFkNjYzM2MzYjhkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQxMzEyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTMwZmIzZjZmMTFlZjQyMjVkNDU0OGEzNDMyMGE5ZDc1NTIyYmY5NTJhZWNhZTM5OTE3Y2QwNDVjNjExM2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bKpiPKo-qwiwZJMclVD1kTwiFS3DbVsiSdoSjNPC9b4)

**Comment by Cryptocool1** [comment]
for logo update please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details
