### ISSUE TITLE
How to relist a token, merge-fee-bot delete my comment

### ISSUE THREAD

**Issue by freeffect** [trustwallet/assets#26680]
Some time ago, the BAS(0x40ffafcd7415ed2f7a902312407181140ad14e68) icon could be displayed on pancakeswap, but now it cannot be displayed. If I want to solve this problem, what steps need to be performed and should I resubmit the PR? I left a comment at https://github.com/trustwallet/assets/pull/20619, but merge-fee-bot deleted my comment. How should I solve this problem?

**Comment by Cryptocool1** [comment]
I see you don’t have enough holders to be listed on Trust Wallet. 
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

**Comment by b1u3h4t** [comment]
Now all criteria are met! Please reused the fee. This is origin PR: https://github.com/trustwallet/assets/pull/20619

**Comment by cryptomanz1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by freeffect** [comment]
I create new PR. https://github.com/trustwallet/assets/pull/26775. Please reuse the fee. Thanks.

**Comment by freeffect** [comment]
@Cryptocool1 Please check https://github.com/trustwallet/assets/pull/26775.
