### ISSUE TITLE
Unizen $ZCX Logo Update

### ISSUE THREAD

**Issue by BojanPi** [trustwallet/assets#26806]
Could you please provide an official announcement about rebranding?

_Originally posted by @Cryptocool1 in https://github.com/trustwallet/assets/issues/26411#issuecomment-1815617536_

The ticket is closed again, very fast, we couldn't even reply. Please open a ticket so i can provide info you asked. Thank you.

**Comment by BojanPi** [comment]
https://twitter.com/unizen_io/status/1719103300820459969

https://www.unizen.io/blog/post/unveiling-unizen-stratosphere-v2-a-pinnacle-of-decentralized-finance-and-trading

Also, please refer to CMC, we have updated our logo with them (GoinGeco as well): 
![logo128px](https://github.com/trustwallet/assets/assets/102355982/18c68ff4-f270-47ec-98fe-b1fdfb3a3904)
https://coinmarketcap.com/currencies/unizen/

**Comment by Hsenaai** [comment]
Could you please provide an official announcement about rebranding?

**Comment by BojanPi** [comment]
Hi sir, are those links i've posted not enough? You have it linked here, from our Blog where we've unveiled our new look (V2 stratosphere)

**Comment by BojanPi** [comment]
Any updates? Anything else is needed from us?

**Comment by Cryptocool1** [comment]
thank you for information you provided, we will update your logo soon

**Comment by cryptomanz1** [comment]
#26411 Done
