### ISSUE TITLE
Unizen $ZCX Logo Update

### ISSUE THREAD

**Issue by BojanPi** [trustwallet/assets#26805]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions, in order to filter out scam tokens.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .

_Originally posted by @Cryptocool1 in https://github.com/trustwallet/assets/issues/26411#issuecomment-1737716400_
            
-----------------------------------------------------------------------------------------
hi there sir, since this is far from a new token/project, and we're asking only to update the logo (no way to scam anyone in any way possible) - can we skip the number of holders req? Especially since we have ~140k of transactions (without transaction on Polygon).

 If you do 2min research on us, you'll see that we have business deals with a lot of recognized projects in crypto, and also that we have constant releases along with very vibrant community

Waiting on your feedback, and thank you in advance!

Bojan

**Comment by Cryptocool1** [comment]
Reopened
