### ISSUE TITLE
Dear Trust Team, I have a small request.

### ISSUE THREAD

**Issue by misterbig19707** [trustwallet/assets#27049]
## How can we help ?

This morning, to my delight, I discovered that my submitted pull request: https://github.com/trustwallet/assets/pull/27026 has been successfully approved. Once again, thank you for your recognition. However, I also noticed that the logo with a white background does not display well in the wallet and PancakeSwap. This is evidently an oversight on our part, as we did not fully consider this issue. Therefore, we have created a new logo and hope you can assist us in replacing it. Your help is greatly appreciated.

![logo](https://github.com/trustwallet/assets/assets/151210071/58347ff5-5a8c-4346-abdf-94a46a348e77)

**Comment by Cryptocool1** [comment]
If you want to make any updates you can create a Pull Request for that
