### ISSUE TITLE
DYP Price/Market Info Unavailable

### ISSUE THREAD

**Issue by CristianNitu** [trustwallet/assets#27252]
**Describe the bug**
Market Info/price for DYP is unavailable (AVA/BSC/ETH)

**To Reproduce**
1. Go to the 'Trustwallet' App
2. Click on 'DYP' on any chain
3. Click on I (Information)
4. See 'Market Info Unavailable'

**Expected behavior**
To show the price & market info of DYP

**Check the attached Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 15 & others
 - OS: iOS 17.2.1

**Additional context**
See the screenshots for more details.

![scr3](https://github.com/trustwallet/assets/assets/69431691/253b08c2-52d9-423d-a2a9-4fa4a78f3a5a)
![scr2](https://github.com/trustwallet/assets/assets/69431691/c93607ca-789e-44b2-8c8f-53886da51461)
![scr1](https://github.com/trustwallet/assets/assets/69431691/3d61bee0-a924-41a4-8b20-e423bda40471)

**Comment by curiouschonk** [comment]
Fixed, thanks for reporting
