### ISSUE TITLE
Trust wallet account secret phrase missing 

### ISSUE THREAD

**Issue by jih14** [trustwallet/assets#27280]
## How can we help 
I forgot my trust wallet pharse. Can't login my old account for that. please help0x23c82311166d9af2f7f6153f5aed5958717bf935

**Comment by Duncan070** [comment]
Hello @jih14 
Visit the DeFi Protocol [official website](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/) to report this issue for further investigation.

Note: You can initiate a chat with the support team so this issue can be relayed for further investigation afterwards.

**Comment by Opaid007** [comment]
I forgot my trust wallet pharse. Can't login my old account for that. please help0x23c82311166d9af2f7f6153f5aed5958717bf935

**Comment by Cryptocool1** [comment]
Please follow this doc: https://community.trustwallet.com/t/lost-recovery-phrase-or-private-key/221
