### ISSUE TITLE
BASE network tokenlist support

### ISSUE THREAD

**Issue by call-by** [trustwallet/assets#27306]
**Is your feature request related to a problem? Please describe.**
We're using TrustWallet token list API to fetch the token lists, and for Ethereum mainnet, Polygon, Binance etc, there's a `tokenlist.json` file which contains all the tokens supported.
But noticed for the BASE network, only individual assets are available, but not comprehensive tokenlist.json file.

**Describe the solution you'd like**
Could you please add a `tokenlist.json` file for the BASE network as well?

**Comment by Maxzybx** [comment]
Good

**Comment by Siya8080** [comment]
توکن بدین بهم

**Comment by Bspring305** [comment]
لطفاً

در تاریخ جمعه ۲ فوریهٔ ۲۰۲۴،‏ ۲۰:۲۰ Siyavash Talati <
***@***.***> نوشت:
