### ISSUE TITLE
دریافت توکن

### ISSUE THREAD

**Issue by Siya8080** [trustwallet/assets#27336]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Siya8080** [comment]
من بیتکن دارم به ارزش ۶۳ هزار دلار
ولی چون نمیتونم کیف پول دیجیتالم رو شارژ کنم نمیتونم پول انتقال رو واریز کنم کسی میتونه بهم کمک کنه
![0BB30B63-C854-423D-9957-006DE0ECEA4F](https://github.com/trustwallet/assets/assets/155111088/2031a432-f98b-4741-a207-2e2e8cff50fb)

**Comment by Bspring305** [comment]
سلام متوجه منظورتون نشدم. البته امیدوارم این یک دروغ آپریل نباشه.چون تا اون
موقع خیلی مونده و زود شروع کردین!! 😂😇
لطفاً اگه از کیف پول etherwallet سردرمیارین منم کمک کنید برای برداشت
اتریومم. ممنونم که وقت گذاشتین و مطالعه کردین.

در تاریخ جمعه ۲ فوریهٔ ۲۰۲۴،‏ ۲۳:۴۷ Siyavash Talati <
***@***.***> نوشت:

**Comment by Siya8080** [comment]
What does April's joke mean? I sent a screenshot so that you can understand that I am not lying. I have to pay 64 dollars to transfer this money to TrustVolt.

**Comment by Bspring305** [comment]
Lol.

در تاریخ دوشنبه ۲۶ فوریهٔ ۲۰۲۴،‏ ۲۳:۰۸ Siyavash Talati <
***@***.***> نوشت:
