### ISSUE TITLE
add EASTERN LIGHT CAPITAL (ELC) token logo on trust wallet

### ISSUE THREAD

**Issue by andersonnetlink** [trustwallet/assets#2733]
add EASTERN LIGHT CAPITAL (ELC) token logo on trust wallet

ERC20 TOKEN NAME : EASTERN LIGHT CAPITAL
ERC20 TOKEN SYMBOL: ELC
ERC20 TOKEN SUPPLY:190,000,000
ERC20 TOKEN CONTRACT ADDRESS: 0x9577daade444ce9b53026abbfd4aa45bd4a7fdec
ERC20 TOKEN CONTRACT URL: https://etherscan.io/token/0x9577daade444ce9b53026abbfd4aa45bd4a7fdec

![0x9577daade444ce9b53026abbfd4aa45bd4a7fdec](https://user-images.githubusercontent.com/68225766/87386171-80e1e480-c5bd-11ea-859d-76c2e91eff38.png)

**Comment by zachzwei** [comment]
Please follow this guide to submit the asset properly.
https://community.trustwallet.com/t/how-to-submit-a-new-token-asset/3863
