### ISSUE TITLE
We do not plan to add this chain

### ISSUE THREAD

**Issue by sheenhx** [trustwallet/assets#27384]
We do not plan to add this chain

_Originally posted by @Cryptocool1 in https://github.com/trustwallet/assets/issues/27357#issuecomment-1931918217_

Can we get a refund?

Is there any reason for rejection?

**Comment by Cryptocool1** [comment]
Hello, there is no refund, you could see this info as first message from the bot. The reason for rejection is we do not plan to add your blockchain for now.
