### ISSUE TITLE
RIN Token Doesn't Appear in Search, Delisted Reliable Index hasn't disappeared from search.

### ISSUE THREAD

**Issue by lavimalik** [trustwallet/assets#275]
**Describe the bug**
The delisted RELIABLE INDEX 0x4bf62424385ddcd858535caa1878e512314a9aeb Still Shows up in Search.

The newly listed (since about a week) RIN TOKEN 0x2da95f7e0093ce7dc9d9ba5f47b655108754b342 Doesn't Show up in search while adding custom token.

This creates confusion with RIN Token users, please remove RELIABLE INDEX asap and add RIN Token in search ASAP.

The RELIABLE INDEX has already been removed from this repository and RIN TOKEN has already been added to this repository but the search hasn't been updated since a week for some reason!

**To Reproduce**
1. Open Trust Wallert
2. Add Custom Token
3. Search for RIN
4. Reliable Index Shows Up

**Expected behavior**
Instead of Reliable Index, RIN Token should show up.

This is a serious issue affecting an important cryptocurrency project and creating confusion among users. Please Solve ASAP!

**Comment by lavimalik** [comment]
@kolya182 is there any update regarding this bug?

**Comment by lavimalik** [comment]
@kolya182 Old Reliable Index Token logo has been removed but it still shows up, is it possible to remove it and de list it completely as soon as possible so that it doesn't show up in search anymore?

Thanks!

**Comment by kolya182** [comment]
Let me jump on this

**Comment by kolya182** [comment]
@lavimalik Let me tweak search results, due to many tokens with same name and symbol matching your token it can be problematic find exactly what you looking for.

**Comment by kolya182** [comment]
![IMG_5751](https://user-images.githubusercontent.com/3277207/66802487-7204bf00-eed1-11e9-884c-36d20441fd88.jpg)
