### ISSUE TITLE
Paid to have Phoenix added to Chains

### ISSUE THREAD

**Issue by Fluffynorth** [trustwallet/assets#27545]
## How can we help ?

I paid the 500 TWT to have Phoenix added to chains and devs closed pull request without checking the pr or the transaction. So either they return the 500 TWT or need to do what they were paid to do. Pretty shady way of doing business. Was submitted https://github.com/trustwallet/assets/pull/27530
And txn is https://explorer.binance.org/tx/2CABD7B44F7247852D13A22F0638BDC311BB65ADBD75A3BDAF7F662C44FB838E

**Comment by Cryptocool1** [comment]
Your PR was closed with message to create new one, because you did it wrong. You can create new PRusing my instructions and then you fee will be reused.
