### ISSUE TITLE
500.00 TWT have been successfully [burned](https://explorer.binance.org/tx/2C98B5C2C29FCCC13F556EC3AE96B8D904ECD0C257659D5703C089B4CF22EEB5).

### ISSUE THREAD

**Issue by bricsmine** [trustwallet/assets#27590]
500.00 TWT have been successfully [burned](https://explorer.binance.org/tx/2C98B5C2C29FCCC13F556EC3AE96B8D904ECD0C257659D5703C089B4CF22EEB5).

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/27561#issuecomment-1981957643_

**Comment by Cryptocool1** [comment]
hi, please see my last comment in PR

**Comment by bricsmine** [comment]
I did not find a message. please guide me

**Comment by cryptomanz1** [comment]
https://github.com/trustwallet/assets/pull/27561#issuecomment-1983070276
