### ISSUE TITLE
> We are airdropping. It may take 3 days. Please do not close this pr

### ISSUE THREAD

**Issue by bricsmine** [trustwallet/assets#27604]
> We are airdropping. It may take 3 days. Please do not close this pr

Hello, we do not accept airdropped tokens. Please see our documentation for adding assets. 
cone back to us once you get real holders

_Originally posted by @Cryptocool1 in https://github.com/trustwallet/assets/issues/27574#issuecomment-1987352065_
            

Hello. In AirDrop, we only invite users to Telegram groups. Free tokens are not paid at all. New members make purchases by reading our documents. Our purchase address is available in the sent contract address. You can check our usdt address.

**Comment by Cryptocool1** [comment]
Hello, as I said in your PR we do not accept any airdropped tokens. Please refer to our documentation https://developer.trustwallet.com/listing-new-assets/requirements
