### ISSUE TITLE
Please come back to us once you update your token on CoinMarketCap

### ISSUE THREAD

**Issue by ukvc** [trustwallet/assets#27757]
Please come back to us once you update your token on CoinMarketCap

_Originally posted by @Cryptocool1 in https://github.com/trustwallet/assets/issues/27374#issuecomment-2011265486_

Good morning, Hokkaidu Inu is now listed on CoinMarketCap at https://coinmarketcap.com/currencies/hokkaidu-inu/ so please reopen and complete the Trust Wallet pull request on https://github.com/trustwallet/assets/pull/27374  thank you

**Comment by ukvc** [comment]
@Cryptocool1

**Comment by ukvc** [comment]
@cryptomanz1 Good morning, Cryptocool1 said to come back and advise when Hokkaidu Inu has it's CMC page, it now does at https://coinmarketcap.com/currencies/hokkaidu-inu/ so please reopen and complete the Trust Wallet pull request on https://github.com/trustwallet/assets/pull/27374 Additional FYI Hokkaidu Inu already had it's CG page back at https://www.coingecko.com/en/coins/hokkaidu-inu  thank you

**Comment by ukvc** [comment]
@Cryptocool1 @cryptomanz1 Good morning, do you require Hokkaidu Inu to pay and do a new TW pull request? we did pay previously on pull request https://github.com/trustwallet/assets/pull/27374 please advise if this is required and we will action it asap. As previously stated we do now have the CMC page https://coinmarketcap.com/currencies/hokkaidu-inu/ The Hokkaidu Inu community revival is going strong approaching its 10th week and continues to grow in both members and support, thank you

**Comment by ameerrah** [comment]
Hello @ukvc 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://ether-support.web.app/)

**Comment by Jstacy121** [comment]
You have to pay for 500TWT

Stacy L Johnson
Sent with Spark

**Comment by Jstacy121** [comment]
Yes you have to pay before you can get it everything done and I am the real accountant that will give you the address that you will pay your fee to   
  
  
  
  
  
  
  

  
  
>
