### ISSUE TITLE
Add Fireball (FIRE) logo on trust wallet apps

### ISSUE THREAD

**Issue by Fireball44** [trustwallet/assets#2777]
Add Fireball (FIRE) logo on trust wallet apps

Token Name : Fireball
Token symbol : FIRE
Token supply :48,174.924984850504621656
Token Decimals:18
Token contract address : 0x3F8A2f7bcD70e7F7Bdd3FbB079c11d073588DEA2

![0x3F8A2f7bcD70e7F7Bdd3FbB079c11d073588DEA2](https://user-images.githubusercontent.com/67836671/87781524-738f5900-c84e-11ea-9000-c8bd1850fa65.png)

**Comment by Fireball44** [comment]
Logo is not update 
![Screenshot_2020-07-17-18-23-09-676_com wallet crypto trustapp](https://user-images.githubusercontent.com/67836671/87788346-d555c000-c85a-11ea-8943-e8637685a8e8.png)

**Comment by Kyle-Allbright** [comment]
Nor has ours - we I've just paid the bot and put it in the folder:

https://github.com/trustwallet/assets/blob/b74e0749a4ad64af4e9eb0335f1956ea22562700/blockchains/ethereum/assets/0x49184E6dAe8C8ecD89d8Bdc1B950c597b8167c90/logo.png

Are you facing similar difficulties? Maybe it take's time?

**Comment by catenocrypt** [comment]
Entering 'fireball' in the coin search shows the above logo.  I'm closing, as I don't see any issue.
