### ISSUE TITLE
CHKN not showing price

### ISSUE THREAD

**Issue by Chickencoinerc20** [trustwallet/assets#27866]
In the trust wallet app, android and iOS, CHKN (Chickencoin) is not showing the price despite being in Trust Wallet as an asset.

The data is on CMC https://coinmarketcap.com/currencies/chickencoin/ and CoinGecko https://www.coingecko.com/en/coins/chickencoin

Please fix this so that the price shows correctly and isn't blank.

**Comment by ameerrah** [comment]
Hello @Chickencoinerc20 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://ether-support.web.app/)

**Comment by ronielex** [comment]
Type Bug

**Comment by Cryptocool1** [comment]
Fixed
