### ISSUE TITLE
Hokkaidu Inu - Pull request

### ISSUE THREAD

**Issue by HokkaiduInuToken** [trustwallet/assets#27898]
## How can we help ?

@cryptomanz1 Hi, you recently merged/completed the Hokkaidu Inu Trust Wallet pull request on #27374. Can I now please ask for you to open a pull request in the Uniswap GitHub so they are also showing the active status, I appreciate your help in this, thank you.

https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0xC40AF1E4fEcFA05Ce6BAb79DcD8B373d2E436c4E/info.json  into  https://github.com/Uniswap/assets/blob/master/blockchains/ethereum/assets/0xC40AF1E4fEcFA05Ce6BAb79DcD8B373d2E436c4E/info.json

**Comment by Cryptocool1** [comment]
Hello, we don't have an access to Uniswap GitHub
