### ISSUE TITLE
Do not sebd tokens to these guys. They're scammers.

### ISSUE THREAD

**Issue by Fluffynorth** [trustwallet/assets#27924]
https://github.com/trustwallet/assets/pull/27921 look here for yourselves they steal your funds and close your PR without doing anything. Then won't return your funds for no services provided for the fee they require. I have submitted a report to github over the misuse and the evidence is being reviewed by github team.

**Comment by Cryptocool1** [comment]
Hello we have no plans to add your chain at the moment. As you can see at the first message from the bot there is no refund
