### ISSUE TITLE
Jay-Cat 

### ISSUE THREAD

**Issue by Jaycat66** [trustwallet/assets#27991]
https://looksrare.org/collections/0x495f947276749Ce646f68AC8c248420045cb7b5e?utm_source=looksrare_app&utm_medium=app&utm_campaign=app

**Comment by bani68** [comment]
در تاریخ پنجشنبه ۱۸ آوریل ۲۰۲۴، ۰۸:۵۷ MarvelousJarvis <
***@***.***> نوشت:
