### ISSUE TITLE
Price missing for VinuChain (VC) - BSC - 0x2bf83d080d8bc4715984e75e5b3d149805d11751

### ISSUE THREAD

**Issue by ElemontCapital** [trustwallet/assets#28006]
Hi team,

The price is not being displayed for VinuChain (VC) on BSC, 0x2bf83d080d8bc4715984e75e5b3d149805d11751
Shows as $0.

The price is available on:
- BscScan: https://bscscan.com/token/0x2Bf83D080d8Bc4715984e75E5b3D149805d11751
- CMC: https://coinmarketcap.com/currencies/vinuchain/
- CG: https://www.coingecko.com/en/coins/vinuchain

If you could please fix

Thanks

**Comment by Cryptocool1** [comment]
Hi, can you please make the screenshot?
 I see the price of your token on my device

**Comment by ElemontCapital** [comment]
I cleared cache but still shows $0

[Image]



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ElemontCapital** [comment]
I cleared cache but still shows $0
![image](https://github.com/trustwallet/assets/assets/85147617/e69f88cf-1ba5-4579-9124-813cc5e1f954)

**Comment by curiouschonk** [comment]
<img width="284" alt="image" src="https://github.com/trustwallet/assets/assets/146854853/d311fdd5-c962-48f3-a600-67d59e685399">


Resolved, thanks for reporting.

**Comment by OGKARMANFT** [comment]
Bug
