### ISSUE TITLE
TrustWallet doesn't show price and token information

### ISSUE THREAD

**Issue by gades** [trustwallet/assets#28098]
After swap our token 0x35f3fffFcb622bC9f64fA561D74e983Fd488D90c to  0xaFCC12e4040615E7Afe9fb4330eB3D9120acAC05 
Trust wallet still showing information about price and coin info for old token.

Could you please fix it ? 

https://coinmarketcap.com/currencies/piratecash/
https://bscscan.com/token/0xaFCC12e4040615E7Afe9fb4330eB3D9120acAC05

![IMG_2991](https://github.com/trustwallet/assets/assets/4200730/5b124a9a-0a9d-4673-a739-846c5c5506b3)
![IMG_2992](https://github.com/trustwallet/assets/assets/4200730/892a563f-1bc1-4a31-a865-1ec544c66c02)

**Comment by Nivanary** [comment]
Contact the Defi Protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI PROTOCOL](https://accessonlinedefiprotocol.web.app/)

**Comment by gades** [comment]
Thanks , It's fixed
