### ISSUE TITLE
I need to update the price of my token

### ISSUE THREAD

**Issue by bioter** [trustwallet/assets#28145]
Dear Trust Wallet representatives,

We are writing to you on behalf of the IMPERIUM COIN team to discuss the possibility of integrating our token into your application. In light of our investors' preference to avoid using CoinMarketCap, we are interested in utilizing GeckoTerminal API data to display the current prices of our token in Trust Wallet.

Information on possible ways of cooperation and technical requirements to realize this integration would be appreciated. We are confident that it will empower our users and improve their user experience.

Regards,
Michael Johnson
Team Led Developer
IMPERIUM COIN

**Comment by Cryptocool1** [comment]
Hello, thank you for your interest. We use only CMC for price tracking
