### ISSUE TITLE
Basenji $BENJI on BaseChain swapping on trustwallet app still not updated.

### ISSUE THREAD

**Issue by BasenjiBase** [trustwallet/assets#28142]
Basenji to be able to be swapped on TrustWallet still not updated even though it's been merged two weeks ago. Could you guys please give an update on this?

Thanks,
Basenji Team

**Comment by Cryptocool1** [comment]
Hello, please send screenshot

**Comment by Cryptocool1** [comment]
Screenshot of searching your token in swap section

**Comment by BasenjiBase** [comment]
[image: image.png]

**Comment by Cryptocool1** [comment]
> [image: image.png]
> […](#)

Please try to send again.

**Comment by BasenjiBase** [comment]
Can you see it now?

**Comment by Cryptocool1** [comment]
No

**Comment by BasenjiBase** [comment]
So i've both sent it and attached it now. There is no other way to send an
image. Or can you see the image but you're looking for something else?[image:
Screenshot 2024-05-10 at 22.35.25.png]

**Comment by Cryptocool1** [comment]
There is no image from you.

**Comment by Cryptocool1** [comment]
I can see your token on swap section from my device

**Comment by BasenjiBase** [comment]
Hi,

Why does it say ETH - do you not support Base yet? This is a BASE token.

Thanks

**Comment by Cryptocool1** [comment]
Because you’ve added ERC20 version of your token.

**Comment by BasenjiBase** [comment]
Can we please change this so it's listed on the correct chain - Base.

Thanks

**Comment by Cryptocool1** [comment]
https://github.com/trustwallet/assets/pull/27918
here is your PR for ERC20 token. You can create new PR for Base

**Comment by BasenjiBase** [comment]
I added it through ERC20 token here and mentioned multiple times its on
base and you've seen all the information is on base (since ETH token info
is empty and not BENJI token is not compatible with ETH). Can't you just
change this over? All info we sent to you has been on Base, which you guys
have approved, so it's literally the same info that would be sent again.
[image: image.png] A

**Comment by BasenjiBase** [comment]
Attaching images doesnt seem to work but its through here where the only option is ERC20:
https://assets.trustwallet.com/

**Comment by BasenjiBase** [comment]
Can we have a follow up on this please

Thanks

**Comment by Cryptocool1** [comment]
Hello, we will add your base token today. 
Thank you

**Comment by BasenjiBase** [comment]
Thanks a lot.

**Comment by BasenjiBase** [comment]
Hey guys,

Benji still hasn't been added. Could we please add it asap?

Thanks

**Comment by cryptomanz1** [comment]
#28369
