### ISSUE TITLE
Price for IMPCOIN

### ISSUE THREAD

**Issue by bioter** [trustwallet/assets#28193]
Hello, My name is William Som, and I am the Team Lead Developer at IMPERIUM COIN. We are pleased to inform you that our token is now listed on CoinMarketCap.
Could you please clarify when the price of our token will start to appear in users' wallets?
Thank you in advance for your cooperation.
Best regards,William Som
Team Lead Developer, IMPERIUM COIN

**Comment by Cryptocool1** [comment]
Hello, please send CoinMarketCap link

**Comment by bioter** [comment]
https://coinmarketcap.com/currencies/imperium/

**Comment by Cryptocool1** [comment]
Thanks , we will enable the price soon.

**Comment by bioter** [comment]
I'm sorry, how long before the price comes out approximately. Our buyers complain that there is no value and sell the coins.

**Comment by Cryptocool1** [comment]
fixed
