### ISSUE TITLE
Transfer not receive to reciver

### ISSUE THREAD

**Issue by Waleedkgf098** [trustwallet/assets#28264]
Hello team
On 29 march 2024 time 09:58:46 am i was send 200 usdt trust wallet to my binance account and transection Hash ( 0x179a9bdd42d95b2fbb021af0dd2c83146a18a0391acdaabed3971c469699cf59 ) please solve my problem in binance not received but in trust wallet show me transfer successful.
![Screenshot_2024-05-24-04-35-54-95_08800057d42e3b72e31ae4fd4c41ba57](https://github.com/trustwallet/assets/assets/170683408/73b7fe3c-86ba-4913-970b-3357c1c12a86)

**Comment by navidferi7** [comment]
Wrong
