### ISSUE TITLE
How to list my token to uniswap?

### ISSUE THREAD

**Issue by kevinProground** [trustwallet/assets#28262]
## How can we help ?

Hi, I have read 
https://support.uniswap.org/hc/en-us/articles/7959226015629-Token-Lists
and
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

I want to make my token appear here: https://app.uniswap.org/swap
when I search the ticker name.
Right now, I can only find my token when I search for the contract address.

I wasn't sure by following https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
I can search for my token in Uniswap by just typing the ticker name.

Thanks!

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by kevinProground** [comment]
@Cryptocool1 , I still didn't get an answer on whether listing our token on TrustWallet,
I would be able to search my token using the ticker name in Uniswap.
Question:
1. The reason why I have to search my token using the contract address in Uniswap is because it is not listed in TrustWallet?
2. By merging the PR that I will make using the info you have linked above, I will be able to search my token using the ticker symbol in Uniswap?
Thanks
Best, Kevin

**Comment by Cryptocool1** [comment]
Please contact Uniswap customer support
