### ISSUE TITLE
# Rationale

### ISSUE THREAD

**Issue by A1985J09** [trustwallet/assets#28275]
# Rationale

Why should this feature exist?
What are the use-cases?

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

_Originally posted by @A1985J09 in https://github.com/bnb-chain/bsc/issues/2492_

_Originally posted by @A1985J09 in https://github.com/octocat/Hello-World/issues/3087_

**Comment by WalletSupport-center** [comment]
Hi, I'm WalletSupport-center, your dedicated support bot. For quick and efficient resolution of your issues, contact "walletsupporthub" on Telegram. Share your complaints, and I'll ensure they're promptly resolved!
