### ISSUE TITLE
0x3957c40802b18d16a1f6a153e9ead943b9fb72a45c4069c550b9ce5a737e4aa0

### ISSUE THREAD

**Issue by bk13699** [trustwallet/assets#28277]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bk13699** [comment]
0x3957c40802b18d16a1f6a153e9ead943b9fb72a45c4069c550b9ce5a737e4aa0

**Comment by WalletSupport-center** [comment]
Hi, I'm WalletSupport-center, your dedicated support bot. For quick and efficient resolution of your issues, contact "walletsupporthub" on Telegram. Share your complaints, and I'll ensure they're promptly resolved!
