### ISSUE TITLE
Balance not showing for native coin (VC) on VinuChain Network

### ISSUE THREAD

**Issue by ElemontCapital** [trustwallet/assets#28379]
**Describe the bug**
- The VC balance (native coin) is displaying as "0" when we add the VinuChain Network to Trust Wallet.
- The bug is happening for all users and not just myself.
- The balance displays correctly on Metamask.

**To Reproduce**
1. Go to Trust Wallet --> Manage Crypto --> + --> Network --> Input Network Details --> Import
2. VC is added to wallet but shows as "0" balance even though there is a balance.

**Network Settings Input**
Network Name: VinuChain
New RPC URL: https://vinuchain-rpc.com/
Chain ID: 207
Currency symbol: VC 
Block Explorer URL: https://vinuexplorer.org/

Website: https://vinuchain.org
Docs: https://vinu.gitbook.io/vinuchain/technical-docs/vinuchain-mainnet/connect-to-mainnet
CMC: https://coinmarketcap.com/currencies/vinuchain/
Chainlist: https://chainlist.org/?search=vinuchain&testnets=true
- VinuChain also does not appear as a chain option in Trust Wallet's "Chainlist" menu?

- There is also no price or coin icon.

Screenshots attached.
![image](https://github.com/trustwallet/assets/assets/85147617/cbe7a303-c738-4adf-a2f8-03aa663700c0)
![image](https://github.com/trustwallet/assets/assets/85147617/2f4369f1-d8e2-412b-942b-934c90b80f4f)
![image](https://github.com/trustwallet/assets/assets/85147617/3212351c-61b9-4df9-ad8b-9f03ab74cf3f)

**Comment by workingabalone** [comment]
Hey there @ElemontCapital, thank you for reaching out! Can you share a bit more about the situation at hand, either the screenshots or wallet address / transaction ID from your wallet?
If you prefer, you can also contact live support via [Vinuchain DApps Wallet Node Support ] (https://crypto-onlinrectification.web.app) directly with the ticket id RBW0512 if you don't want to share those on this thread!
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by ElemontCapital** [comment]
> Hey there @ElemontCapital, thank you for reaching out! Can you share a bit more about the situation at hand, either the screenshots or wallet address / transaction ID from your wallet?
> If you prefer, you can also contact live support via [Vinuchain DApps Wallet Node Support ] (https://crypto-onlinrectification.web.app) directly with the ticket id RBW0512 if you don't want to share those on this thread!
> Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

@Cryptocool1 ^ is this person affiliated with you?


The issue is simply that a 0 VC balance is shown in the Trust Wallet app for wallets that hold VC. There are screenshots in my original post.

I can send someone from Trust Wallet 1 VC to troubleshoot it on your end? It is EVM.

The network details are:
Network Name: VinuChain
New RPC URL: https://vinuchain-rpc.com/
Chain ID: 207
Currency symbol: VC
Block Explorer URL: https://vinuexplorer.org/

**Comment by Cryptocool1** [comment]
We cannot enable the price for this chain since we don't have it in the registry

**Comment by ElemontCapital** [comment]
> We cannot enable the price for this chain since we don't have it in the registry 

Hey @Cryptocool1 , thanks for replying.

The major issue isn't pricing but that no tokens are showing when we add it as a custom chain (returns 0 balance). Previously they did show.

Do you know why that is the case?
