### ISSUE TITLE
Request to add Va$il

### ISSUE THREAD

**Issue by degan19** [trustwallet/assets#28400]
**Token Name**: Va$il
**Symbol**: V$L
**Decimals**: 18
**Contract Address**: 0x9bfC9529844A0F3Db85b91c8581ce7eB517C781d
**Description**: The future of crypto
**Website**: https://soundexpert.wixsite.com/my-site-1
**Explorer**: https://bscscan.com/token/0x9bfc9529844a0f3db85b91c8581ce7eb517c781d
**Logo**: [[Provide a link to the logo image hosted online, must be a 256x256 PNG]](https://github.com/degan19/assets/blob/master/blockchains/smartchain/assets/0x9bfC9529844A0F3Db85b91c8581ce7eB517C781d/logo.png)
**Social Profiles**: do not have

**Comment by cryptomanz1** [comment]
As per our policy, there is a minimum requirement of 10,000 holder addresses and 15,000 transactions.
See the criteria at : https://developer.trustwallet.com/listing-new-assets/requirements .
