### ISSUE TITLE
Aave (LEND) token not displaying properly in trust wallet 

### ISSUE THREAD

**Issue by sirsoth** [trustwallet/assets#2843]
Aave (LEND) token not displaying properly in trust wallet

1. Go to trust wallet tokens section
2. Click on '+' button
3. search for LEND
4. Instead of appearing Aave name as in:
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x80fB784B7eD66730e8b1DBd9820aFD29931aab03/info.json
It appears as EthLend Token

And the logo is the Ethereum one instead of:
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x80fB784B7eD66730e8b1DBd9820aFD29931aab03/logo.png

**Expected behavior**
It should be showing the correct name and icon as pointed before

**Screenshots**

![image](https://user-images.githubusercontent.com/5862694/88157942-4ef70080-cc03-11ea-992b-a2136e0d9202.png)

**Desktop (please complete the following information):**
Android 10
Trust wallet 1.12.3 - Any update available

**Smartphone (please complete the following information):**
Xiaomi mi 8

**Comment by catenocrypt** [comment]
I understand token 0x80fB784B7eD66730e8b1DBd9820aFD29931aab03 is the/one problematic, however, I see no issue with that.  Could you try again?

Here is what I see when searching for 'LEND':
<img width="336" alt="image" src="https://user-images.githubusercontent.com/13562139/88162577-ca5fae80-cc11-11ea-8234-56097051f2bf.png">

And here for AAVE:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/13562139/88162617-d8153400-cc11-11ea-90dc-0a924eaf0e01.png">

If there is something wrong, please identify it clearly.

**Comment by sirsoth** [comment]
Hi @catenocrypt it seems the logo is properly displayed in your app, but the name is still incorrect as stated in:
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x80fB784B7eD66730e8b1DBd9820aFD29931aab03/info.json

![image](https://user-images.githubusercontent.com/5862694/88162923-de071700-cc09-11ea-9045-06b025af01a7.png)

I tested in a newly installed trust wallet app and it shows properly the image as in yours, but the name is still a problem, it should be Aave LEND instead of EthLend LEND also it should be possible to search for it using 'Aave' apart.

Using your image Im highlighting the issue: 

![image](https://user-images.githubusercontent.com/5862694/88163372-79988780-cc0a-11ea-8711-8756c0d52faf.png)


It should be showing 'Aave' instead as pointed in:
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0x80fB784B7eD66730e8b1DBd9820aFD29931aab03/info.json

And apart from that when searching for Aave it should appear of course (I guess this will be fine when the name is properly updated)

**Comment by catenocrypt** [comment]
OK, thanks for the clarification.
The `EthLend` name is not in the asset repsitory, I'm trying to pinpoint where is it coming from, why the info.json is not used. 
But etherscan.io also displays EthLend 

https://etherscan.io/token/0x80fB784B7eD66730e8b1DBd9820aFD29931aab03
<img width="187" alt="image" src="https://user-images.githubusercontent.com/13562139/88164633-ace01400-cc14-11ea-87c4-209544a727e8.png">

**Comment by sirsoth** [comment]
Yes, that name is probably been fetched from the contract, but as we rebranded to Aave we updated the name everywhere, in Ethescan we also added a notifcation of the rebrand within the token page. 

Same way in sources as coinmarketcap and coingecko displaying it as Aave:
https://coinmarketcap.com/currencies/aave/
https://www.coingecko.com/en/coins/aave

In this case would be just matter of fetching the correct info from the info.json file and that would solve this

**Comment by vikmeup** [comment]
@prazd will will make those changes

**Comment by prazd** [comment]
@sirsoth Is it ok now?
![image](https://user-images.githubusercontent.com/34573846/88201091-b9359280-cc4f-11ea-95e1-d7da68c37606.png)

**Comment by sirsoth** [comment]
Hi guys! Thanks a lot for the help, it looks perfect now!
