### ISSUE TITLE
I am confused way i can't withdraw from my trust wallet account it's just closing it self

### ISSUE THREAD

**Issue by zwanski2019** [trustwallet/assets#28445]
## How can we help ?

i have updated the application and it's the same issues i don't know if anyone have encounters
![Uploading Screenshot_20240609-195209_Trust Wallet.jpg…]()
 this kind of problem before what is the solutions plz

**Comment by Shai69bb** [comment]
Working on a resolution to fix this problem

**Comment by zwanski2019** [comment]
what is the solution #10416
