### ISSUE TITLE
Merge-fee-bot deleting my answers to questions

### ISSUE THREAD

**Issue by CurlyBracketEffect** [trustwallet/assets#28474]
Hi @cryptocool1, I am trying to respond to the questions you asked, but every time I do the Merge-fee-bot deletes it immediately with no reason why. I am not sure how to proceed besides opening a related issue. Can you please advise me on how to proceed?

**Comment by CurlyBracketEffect** [comment]
Related to https://github.com/trustwallet/assets/pull/28413

**Comment by Cryptocool1** [comment]
Hello, You can't comment because you are not PR creator , Please ask JBScaled to do it
