### ISSUE TITLE
cant found coins

### ISSUE THREAD

**Issue by Luckymmd** [trustwallet/assets#28536]
hello im sara im send 1300 dolars in my wallet and i swap this dolars for other coins after this im changed my phone and i lost my old phone now i cant find me coins and i forget the coin names my new value is 570 dolars pls help me to find my other mony

**Comment by Ramon44-lab** [comment]
> hello im sara im send 1300 dolars in my wallet and i swap this dolars for other coins after this im changed my phone and i lost my old phone now i cant find me coins and i forget the coin names my new value is 570 dolars pls help me to find my other mony

Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker110
