### ISSUE TITLE
Make lists name tolerant

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/assets#2861]
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/blacklist.json -> blocklist
https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/blacklist.json -> allowlist  

I suggest to look into other directories as well. 

It is important to notify @prazd before merging to master, so we can also make some changes on projects that are using lists.

**Comment by catenocrypt** [comment]
Isn't **allow**/**deny** the standard naming (deny, not block)?

**Comment by catenocrypt** [comment]
What is the exact order of changed not to break?  Maybe do all renames, and keep the old-name-files as well, until BE is updated, then rename the old-name-files?

**Comment by EnoRage** [comment]
We will need to firstly make changes on our side, than update it here
