### ISSUE TITLE
blockchains/base/tokenlist.json is not updated

### ISSUE THREAD

**Issue by artiffine-vojtech** [trustwallet/assets#28637]
GM, our token on BASE was added to the repository by this merged PR [#28363](https://github.com/trustwallet/assets/pull/28363#event-13019556353)

The PR allows projects to update blockchains/base/assets/{{token_address}}/info.json only and add an icon, but any change in file `blockchains/base/tokenlist.json` is not allowed. How can this file be updated? I can see many coins being accepted and merged into the repo, but the main token list never gets updated. 

How can this `tokenlist.json` file be updated? Do you think we should make a separate PR, is it automatic or does your team update it from time to time by hand? 

Thanks!

**Comment by Cryptocool1** [comment]
Hi, why would you need to make any changes to tokenlist?

**Comment by artiffine-vojtech** [comment]
Hi @Cryptocool1, Uniswap states that to update token information (such as logos), it has to be made through this TrustWallet repository. 

Source: https://docs.uniswap.org/contracts/v1/guides/token-listing#token-details-and-assets

> Token Details and Assets
> Token information (including decimals, symbol, name, etc.) is pulled from token contracts directly. Logo images are pulled from TrustWallet. If you'd like your token logo updated make a pull request into the TrustWallet assets repo https://github.com/trustwallet/assets.

So to update Uniswap, we have added the token to this repository, but we need this change to be also reflected in the `blockchains/base/tokenlist.json` file, which if I understand correctly should be a list of all the tokens listed in this repository.

**Comment by Castro1g** [comment]
![Screenshot_2024-07-07-20-51-05-167](https://github.com/trustwallet/assets/assets/175095728/0fabefac-4bb2-4e49-9bc0-e137d89e2f73)

**Comment by Castro1g** [comment]
@/()??

**Comment by rychnovsky** [comment]
Hi @Cryptocool1 any update on this? Thanks!

**Comment by cryptomanz1** [comment]
Hello,
You can create new PR and add your token to the tokenlist, we will review it

**Comment by artiffine-vojtech** [comment]
Thanks, PR created: https://github.com/trustwallet/assets/pull/28715
