### ISSUE TITLE
Add EYE Network (BEP20) #27846

### ISSUE THREAD

**Issue by yenky** [trustwallet/assets#28643]
## How can we help ?

Hi @Cryptocool1 @cryptomanz1

We are listed on CMC : https://coinmarketcap.com/currencies/eye-network/ . Please try to approve logo over Trust Wallet.
PR : 27846 [ We paid already for this ]

Thank You

**Comment by Cryptocool1** [comment]
Hello, that is only preview page, this token is not listed on CoinMarketCap. 
feel free to come back to us once CMC lissting is done

**Comment by yenky** [comment]
Hi @Cryptocool1 @cryptomanz1 ,
Please check it again its listed and not a preview page. 
We are listed on CMC : https://coinmarketcap.com/currencies/eye-network/ . Please try to approve logo over Trust Wallet.
PR : 27846 [ We paid already for this ]

Thank you

**Comment by yenky** [comment]
Hi @Cryptocool1 @cryptomanz1 ,

I'm very sorry to bother you again but we need to get this update for logo. 
Please try to update logo for EYE NETWORK token, its been few days that eye is listed over cmc and we are waiting for response from your. 
 https://coinmarketcap.com/currencies/eye-network/

Thank you
