### ISSUE TITLE
JJ8EK

### ISSUE THREAD

**Issue by Dragankamil6** [trustwallet/assets#28674]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
Thank you for posting @Dragankamil6
