### ISSUE TITLE
Witdraw

### ISSUE THREAD

**Issue by Kcsiochi** [trustwallet/assets#28683]

**Comment by Kcsiochi** [comment]
How i know how much my asset and how to withdraw?

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
Thank you for posting @Kcsiochi
