### ISSUE TITLE
I want to my files from assets

### ISSUE THREAD

**Issue by EvinTokenGH** [trustwallet/assets#28686]
Hi team,

I uploaded my files to trustwallet assets to show my token's logo and info in trust wallet but files dublicated.

I want to delete my all files from there and start from beginning.

I can see my files ( 2 info.json, 2 logo.png) but delete file button is passive.

How i can delete them ? 

Thanks

**Comment by Cryptocool1** [comment]
Hello, 
You need to create new branch and delete old one
