### ISSUE TITLE
EYE NETWORK TOKEN LOGO 

### ISSUE THREAD

**Issue by yenky** [trustwallet/assets#28745]
## How can we help ?

Hi @Cryptocool1 @cryptomanz1

We are listed on CMC : https://coinmarketcap.com/currencies/eye-network/ . Please try to approve logo over Trust Wallet.
PR : 27846 [ We paid already for this ]

Thank You

**Comment by yenky** [comment]
Hi @Cryptocool1 @cryptomanz1

Please try to update the logo. 

We are listed on CMC : https://coinmarketcap.com/currencies/eye-network/ . Please try to approve logo over Trust Wallet.
PR : 27846 [ We paid already for this ]

Thank you

**Comment by yenky** [comment]
Hi @Cryptocool1 @cryptomanz1 ,

I'm very sorry to bother you again but we need to get this update for logo.
Please try to update logo for EYE NETWORK token, its been few days that eye is listed over cmc and we are waiting for response from your.
https://coinmarketcap.com/currencies/eye-network/

Thank you

**Comment by yenky** [comment]
Hi @Cryptocool1 @cryptomanz1 [ EYE Network (BEP20) https://github.com/trustwallet/assets/pull/27846 ]

It's been three days, and we are still waiting for the logo to get updated in our trust wallet. Is it a normal process to get it done? Please try to respond with how many days it's going to take until we get it done. 
We tried to check the time line, and once we got to know, once it got a CMC listing, it should appear in trust wallet anytime, but it's been 3 days now and we got no response from trust wallet PR team.

https://coinmarketcap.com/currencies/eye-network/

Thank you

**Comment by yenky** [comment]
Hi @Cryptocool1 @cryptomanz1

Kindly try to check this issue. It's been many days now, and I don't understand why no one is even trying to give me 5 minutes of this issue. PR is paid, everything is done, and CMC is listed. We are still waiting and trying to reach you guys. Please, we are requesting that you guys update the EYE NETWORK logo in Trust Wallet. We are attaching here both screenshots for EYE, screenshots from Trust Wallet, and screenshots from CMC Portal.

OLD PR : [ EYE NETWORK BEP 20 : 27846] EYE Network (BEP20) https://github.com/trustwallet/assets/pull/27846
![image_123986672(3)](https://github.com/user-attachments/assets/2fe99627-b59d-428d-8e9f-907b780a5856)
![image_123986672(2)](https://github.com/user-attachments/assets/89c3c752-26ae-444d-935d-56ba6aee652e)


Thank you

**Comment by Cryptocool1** [comment]
Hello, please try to update your app
![IMG_7809](https://github.com/user-attachments/assets/aa943982-fdea-474e-bc49-ae132b3a4aa5)
