### ISSUE TITLE
Bug: Updated CMC link doesn't work for XCN @ Base

### ISSUE THREAD

**Issue by al-onyxprotocol** [trustwallet/assets#28768]
# What's up?

Recently we merged XCN @ Base https://github.com/trustwallet/assets/pull/28626

Previously, the XCN @ Ethereum and XCN @ BSC had old CMC link: `"url": "https://coinmarketcap.com/currencies/chain/"`.

Currently, CMC has updated the link to `"url": "https://coinmarketcap.com/currencies/onyxcoin/"` and redirects from `/chain/` to `/onyxcoin/`.

In the PR for adding XCN @ Base, we set the updated link. But it doesn't work. The Trust Wallet app doesn't show the price for XCN @ Base and doesn't have CMC and other links for 

# Possible resolution

What's the best way to resolve this?

* Is it a Trust Wallet bug and devs can resolve this?
* Is it a CMC bug and we create a request to CMC?
* Or it's the best to make PR to update CMC link to the old one?

![image](https://github.com/user-attachments/assets/4879ee1a-4301-4124-8f2f-d4a1a6efa62b)

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Thanks for posting @al-onyxprotocol

**Comment by al-onyxprotocol** [comment]
> This issue has been preview on the Pull Requests. To resolve, Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/) Thanks for posting @al-onyxprotocol

It's a scam.

**Comment by tawhidnazari57** [comment]
[export-token-0x8822fb3a068489ab24afbea77be8fc8c17456a50.csv](https://github.com/user-attachments/files/16353982/export-token-0x8822fb3a068489ab24afbea77be8fc8c17456a50.csv)
[export-advanced-filtered-1721493673843.csv](https://github.com/user-attachments/files/16353983/export-advanced-filtered-1721493673843.csv)
[export-token-0x000000000000000000000000000000000000800a.csv](https://github.com/user-attachments/files/16353984/export-token-0x000000000000000000000000000000000000800a.csv)
[export-token-0xc2132d05d31c914a87c6611c10748aeb04b58e8f.csv](https://github.com/user-attachments/files/16353985/export-token-0xc2132d05d31c914a87c6611c10748aeb04b58e8f.csv)
[export-token-0x64afdf9e28946419e325d801fb3053d8b8ffdc23.csv](https://github.com/user-attachments/files/16353986/export-token-0x64afdf9e28946419e325d801fb3053d8b8ffdc23.csv)

**Comment by al-onyxprotocol** [comment]
Hey @Cryptocool1 @cryptomanz1

Please suggest how we can fix it.

**Comment by curiouschonk** [comment]
Fixed, thanks for reporting this

<img width="359" alt="image" src="https://github.com/user-attachments/assets/1b555a11-8b3a-4c82-9a63-8fedb3fbe723">
