### ISSUE TITLE
Verum Coin (VERUM) price at Trust Wallet apps

### ISSUE THREAD

**Issue by verumcoin** [trustwallet/assets#28784]
**Describe the bug**
Verum Coin (VERUM) token hasn`t price and chart information like other tokens

Verum Coin direct link to the CMC
https://coinmarketcap.com/currencies/verum-coin/

**To Reproduce**
1. Go to Trust Wallet app
2. Open Verum Coin (VERUM) information screen
3. See error "No price data available" at the bottom of the screen

**Expected behavior**
Price data and chart must be available

**Screenshots**
![image](https://github.com/user-attachments/assets/d691ffa5-efba-404b-b858-74c57857d240)

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - OS: iOS

**Comment by verumcoin** [comment]
Hello @Cryptocool1 @cryptomanz1

Can you give any updates for this topic, please?

Best regards

**Comment by curiouschonk** [comment]
Hi @verumcoin 

https://coinmarketcap.com/currencies/verum-coin/
https://coinmarketcap.com/dexscan/bsc/0x1e368ab040837bf76c4a9f6a9bc98d755b64babe/
https://coinmarketcap.com/dexscan/bsc/0xa42d67b37a234f7da5f7a495e430dc2cd17182f4/
https://coinmarketcap.com/dexscan/bsc/0x5e5e307882c762c62623af9ee8bb3007badb0b01/

Based on the pricing data of CoinMarketCap, it is only based on centralized exchanges. And, the liquidity of the pairings in decentralized exchanges are too low. 

Please have at least one pair (either `VERUM/WBNB` `VERUM/USDT` `VERUM/USDC`) with 2% of your market cap so the users can freely trade without the need of going through a CEX. Feel free to re-open this issue when you meet the condition.

cc @Cryptocool1 @cryptomanz1

**Comment by verumcoin** [comment]
Hello, @curiouschonk

Verum Coin listed at top 25 exchange XT.com:
https://www.xt.com/en/trade/verum_usdt

Can you review this issue with Verum Coin price in the Trust wallet app again, please?

Thank you in advance!

cc @Cryptocool1 @cryptomanz1

**Comment by curiouschonk** [comment]
After conducting another review, we have identified instances of plagiarism in your Verum Coin (VERUM) document and project. As a result, we will not proceed with the pricing data and will flag your asset information in our repository.

Metadata shows the document was created on 2024-04-11T10:36:13+02:00

<img width="1453" alt="image" src="https://github.com/user-attachments/assets/8c162768-c074-435b-a116-47e1bb9622cd">

<img width="1689" alt="image" src="https://github.com/user-attachments/assets/7137f269-19cc-4729-baec-6317f4199702">

<img width="1767" alt="image" src="https://github.com/user-attachments/assets/64e4c1a3-d70d-40e7-aaf5-06c5428e8b2c">

<img width="1769" alt="image" src="https://github.com/user-attachments/assets/1dcbd3b8-1060-404a-a1fa-2a90e615affb">

<img width="1579" alt="image" src="https://github.com/user-attachments/assets/d353d256-c0f3-4235-b468-7976c17c4b96">

---

https://github.com/trustwallet/assets?tab=readme-ov-file#disclaimer
