### ISSUE TITLE
Price and token information is not showing, please update

### ISSUE THREAD

**Issue by FlickerFKRPRO** [trustwallet/assets#28855]
@Cryptocool1, @cryptomanz1: Hello, thank you for the merge

Can you tell please , how we can open price data for the FKRPRO Token inside Trust Wallet app?

Now we can`t see any information and price. We have pages at CMC or CG where data can be fetched from.

Thank you in advance!
![WhatsApp Image 2024-07-30 at 11 31 40 AM](https://github.com/user-attachments/assets/f4644bcd-4926-44d3-8178-188e113025f8)
![WhatsApp Image 2024-07-30 at 11 30 44 AM](https://github.com/user-attachments/assets/2e005d60-5b12-4181-af82-7973b45dbd07)

**Comment by mosesojero** [comment]
Hello please approve

**Comment by piratepete21** [comment]
Assurityvand security .. long term

**Comment by curiouschonk** [comment]
Fixed, thanks for the heads up @FlickerFKRPRO 

<img width="358" alt="image" src="https://github.com/user-attachments/assets/b362cc9c-f8a5-4dd4-8783-76322d871871">

<img width="354" alt="image" src="https://github.com/user-attachments/assets/d08477d8-35dd-471f-b6c5-f3a5130a25cf">
