### ISSUE TITLE
Can't find my NeyroAI token in the asset search

### ISSUE THREAD

**Issue by robertBrown377** [trustwallet/assets#28869]
Hello, an hour ago our token was tokenized, but the token does not show up in the asset search. And the price for the token is not displayed
Contract address: 0xA74FD910a6dcC844bA42839108A7A72AAA2EE2c24
Symbol:NeyroAI NAI

**Comment by robertBrown377** [comment]
@Cryptocool1 
@cryptomanz1

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Support](https://accessonlinedefiprotocol.web.app/)
Regards.

**Comment by robertBrown377** [comment]
It's no resolved. You send me, scam link

> This issue has been RESOLVED.

**Comment by robertBrown377** [comment]
@Cryptocool1  please check, price not tracking

**Comment by Cryptocool1** [comment]
Hello, we will enable your price soon, thanks.

**Comment by Cryptocool1** [comment]
Hello, please send your CoinMarketCap link

**Comment by robertBrown377** [comment]
https://coinmarketcap.com/currencies/neyroai/

**Comment by robertBrown377** [comment]
Please check

**Comment by robertBrown377** [comment]
Our investors are outraged as to why our price doesn't show up

**Comment by Cryptocool1** [comment]
Hello, 
we've decided to delist your token do to 
- low DEX liquidity yet it has a high price
- plagiarism

**Comment by robertBrown377** [comment]
@Cryptocool1, Hello, what makes you think it's plagiarized?
It's our token, with its own ecosystem.

**Comment by robertBrown377** [comment]
What do we need for you to add us to the asset list, what documents do we need for this ?
