### ISSUE TITLE
Price and Logo Update

### ISSUE THREAD

**Issue by jmorris101** [trustwallet/assets#28950]
## How can we help ?

The old QDX token on BEP20 (contract: 0x9e3a9F1612028eeE48F85cA85f8Bed2f37d76848) is still displaying on Trust Wallet with active price feeds. However, the new QDX token on BEP20 (contract: 0x08BC237aA00F275b758542c9F5c125b568bc390A) is not showing a price or sourcing data, although the logo is now visible.

CoinMarketCap link: https://coinmarketcap.com/currencies/quidax/
CoinGecko link: https://www.coingecko.com/en/coins/quidax

Please assist in resolving this issue.

**Comment by Macmyhub** [comment]
code was not open []()

**Comment by jmorris101** [comment]
see pull request 28945 and 28936

DO i need to do anything @Macmyhub

**Comment by cryptomanz1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details

**Comment by jmorris101** [comment]
@cryptomanz1 This is not a new coin. Coin already added to Trustwallet  but price not showing.
