### ISSUE TITLE
Remove CMC mapping

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/assets#2898]
Currently assets repo contains a mapping json file for token mapping for CoinMarketCap API.  This file is updated periodically from CMC API, with some exceptions added, and committed to repo.

There is no point is processing and storing CMC data in assets repo, clients can retrieve on their own (==> watchmarket).
The list of exception _may_ stay here (as a static file), TBD (@EnoRage ?).

**Comment by EnoRage** [comment]
I think it could be fully migrated to the watchmarket, together with static
