### ISSUE TITLE
Please allow Trust Wallet /No forked repository found for user Vero7979 You need to fork the assets repository to be able create pull requests. Fork 'assets' Repo Your fork should be here: https://github.com/Vero7979/assets If you've forked recently, try to reload after a few minutes. To fork manually, go to the assets repository,

### ISSUE THREAD

**Issue by Vero7979** [trustwallet/assets#28993]
Please send above protocol TRUST WALLET/funds https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets at Trust

**Comment by cryptomanz1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details
