### ISSUE TITLE
Price not showing 

### ISSUE THREAD

**Issue by jmorris101** [trustwallet/assets#28994]
## Token Price not Showing

The old QDX token on BEP20 (contract: 0x9e3a9F1612028eeE48F85cA85f8Bed2f37d76848) is still displaying on Trust Wallet with active price feeds. However, the new QDX token on BEP20 (contract: 0x08BC237aA00F275b758542c9F5c125b568bc390A) is not showing a price or sourcing data, although the logo is now visible.

CoinMarketCap link: https://coinmarketcap.com/currencies/quidax/
CoinGecko link: https://www.coingecko.com/en/coins/quidax

Please assist in resolving this issue.

**We already made a pull request which was successfully merged to abandon the old QDX and also add the new QDX to trust wallet**

**Comment by ACCmaintenance** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@jmorris101

**Comment by Cryptocool1** [comment]
Hello, we will enable the pricing data for your new token soon

**Comment by Cryptocool1** [comment]
enabled
