### ISSUE TITLE
Removal of Contract 0xabF56cCe897D89e96502970053E52321F03d9c71

### ISSUE THREAD

**Issue by FCAJAY** [trustwallet/assets#2902]
https://github.com/trustwallet/assets/blob/c3ae621f83a7bb0281e46d9e731d52bdf82103af/blockchains/ethereum/whitelist.json#L3599

Dear Sir
I developed my Token on TRC20 So that i want to Remove this Contract.

Thanks & Regards
Ajay K Jayswal

(Chartered Accountant)
CMD- CryptoBharatCoin (CBC)
Mobile :- 8527960789
https://t.me/caajay
https://in.linkedin.com/in/caajaykjayswal

**Comment by catenocrypt** [comment]
Done with #2796 , closing.
