### ISSUE TITLE
USDT

### ISSUE THREAD

**Issue by Tarhanshop** [trustwallet/assets#29041]
_Originally posted by @Tarhanshop in https://github.com/ex3ndr/supervoice-separate/issues/1_

**Comment by Dellapots** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your request. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@Tarhanshop
