### ISSUE TITLE
Token Listed in ERC20 instead of ARB-ETH

### ISSUE THREAD

**Issue by ALTRANIUM** [trustwallet/assets#29070]
We recently created a PR - **_Add Altranium (ERC20) #28995_**

Instead of updating Logo and Fetching Dollar value, a new token has been listed instead under the incorrect network chain.

The desired (existing) network chain is Arbitrum; however it is published under ERC20.

Please advise.

**Comment by summerly01** [comment]
> We recently created a PR - **_Add Altranium (ERC20) #28995_**
> 
> Instead of updating Logo and Fetching Dollar value, a new token has been listed instead under the incorrect network chain.
> 
> The desired (existing) network chain is Arbitrum; however it is published under ERC20.
> 
> Please advise.

Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)

**Comment by cryptomanz1** [comment]
Fixed
