### ISSUE TITLE
btc

### ISSUE THREAD

**Issue by dniangrywn** [trustwallet/assets#29086]
Hai, ini public address Pluang saya untuk menerima Bitcoin (BTC) pada jaringan BNB Smart Chain (BEP20):
0x4860e05e057e28b8a927Aa9328553D84cA6EEEd4

**Comment by Dapssupport** [comment]
> Hi, this is my Pluang public address for receiving Bitcoin (BTC) on the BNB Smart Chain (BEP20) network: 0x4860e05e057e28b8a927Aa9328553D84cA6EEEd4





Hi @dniangrywn ,

To resolve this issue, please contact our support team via live chat using the ticket ID CMP7638.

You can reach the dedicated support line here: [Compound Network DApps Support Ticket Requests](https://thedappsupport.web.app/). Click the live chat icon at the bottom corner of the page to start a conversation with a support agent.

Best regards.
