### ISSUE TITLE
Verum Coin (VERUM) price at Trust Wallet apps

### ISSUE THREAD

**Issue by verumcoin** [trustwallet/assets#29087]
**Describe the bug**
Verum Coin (VERUM) token hasn`t price and chart information like other tokens

Verum Coin direct link to the CMC
https://coinmarketcap.com/currencies/verum-coin/

Verum Coin at XT.com
https://www.xt.com/en/trade/verum_usdt

**To Reproduce**
1. Go to Trust Wallet app
2. Open Verum Coin (VERUM) information screen
3. See error "No price data available" at the bottom of the screen

**Expected behavior**
Price data and chart must be available

**Screenshots**
![image](https://github.com/user-attachments/assets/d691ffa5-efba-404b-b858-74c57857d240)

**Smartphone (please complete the following information):**
 - Device: iPhone 15
 - OS: iOS

**Comment by verumcoin** [comment]
Dear @curiouschonk,

Let us provide a reference for this closed issue (since we can’t respond there anymore): https://github.com/trustwallet/assets/issues/28784.

Below are the answers addressing all instances of plagiarism allegations regarding the Verum Coin project:

1. We are a team that has been active in the market since 2021 and, of course, have mentions on the internet. Our website, bitcoinpay.trade, was registered on 20-Dec-2020. Proof: [Whois Lookup](https://who.is/whois/bitcoinpay.trade).

2. Regarding $AAPT: Verum Coin was created on 04-Feb-2022. You mentioned that our White Paper was created on 2024-04-11. Yes, but that was the latest version of the document, which we update continuously.

Let’s look at when the first version of our website, featuring the same White Paper for Verum Coin, was available. You can see it here (and the website is still available today):
[Archived Verum Coin website (8 March 2022)](https://web.archive.org/web/20220308154307/https://verumcoin.bitcoinpay.trade).

In contrast, the earliest version of the AAPT website with the same tokenomics information was available only on 21 July 2022:
[Archived AAPT website (21 July 2022)](https://web.archive.org/web/20220615000000*/http://aaptitudes.com/).

Their website is not operational anymore.

3. You compared texts from the Behance design project CryptoPay with BitCoinPay’s texts and designs. Yes, that post was by a designer who created a prototype design for our project at that time. Since then, we have undergone a rebranding.

4. Regarding RHO (Rhodium): We cannot find any presence of this token on the internet or cryptocurrency-related websites. From the screenshot, it appears that the token was created on 12-03-2024. That was long after Verum Coin entered the market.

P.S. You can find more information about Verum Coin here:
[Verum Coin on Wikipedia](https://en.wikipedia.org/wiki/Verum_Coin)
[Verum Coin on Investing.com](https://www.investing.com/crypto/verum-coin).


We kindly request that you conduct further research into Verum Coin.

Thank you in advance!

**Comment by curiouschonk** [comment]
Thank you for providing more context.

The AAPT token was created on Dec-31-2021 07:41:27 PM UTC and their wording still matches with the announcement that was made on December 29, 2021, regardless of the archived earliest version of the website. Thoughts?

<img width="556" alt="image" src="https://github.com/user-attachments/assets/f7f292bd-a594-4358-afd5-cc1335360951">

Looking back, we noticed that you responded to one of the maintainers with the following message:
https://github.com/trustwallet/assets/pull/28736#issuecomment-2230749693
> • Did you sold the tokens at an Initial Coin Offering (ICO) or a token presale?
> 
> No, we didn`t

However, your website indicates that a portion of the tokens was allocated for presale. Could you please explain this discrepancy?
<img width="1421" alt="image" src="https://github.com/user-attachments/assets/ee9aaf48-0186-40f4-8974-bc6dedd3824c">

**Comment by verumcoin** [comment]
Good day @curiouschonk,

The similarity in the texts is most likely either a coincidence or a mistake made by a copywriter.

The idea behind the Verum Coin project developed independently and was never intended to copy or use other projects.

Initially, back in 2020, the Verum Messenger project was launched, which focused on confidentiality and anonymity. From this concept, the idea to launch a Verum Coin emerged. Over time, it has evolved from a simple token into a full-fledged project with its own blockchain and ecosystem.

Currently, the project operates on its own blockchain and is no longer just a token. You can explore the Verum blockchain here: [Verum Explorer](https://verumchain.info/).

It is not entirely accurate to compare a project that is actively developing with one that is no longer functional or represented in the market.

Regarding the 10% presale: It’s simple – 10% was sold to a small group of private investors. This wasn`t an ICO or an Airdrop.


Thank you for your vigilance and verification, hope to hear the steps we need to do next to display the price of Verum Coin.

**Comment by curiouschonk** [comment]
> Regarding the 10% presale: It’s simple – 10% was sold to a small group of private investors. This wasn`t an ICO or an Airdrop.

I see. So why did you answer `No, we didn`t` back then? Was the presale round documented anywhere else? (investors, dates, etc.)

Also, what's up with your listing with XT[.]com? (`*** Significantly differs from the cryptocurrency's price; excluded from the overall price and volume calculation`)

<img width="1018" alt="image" src="https://github.com/user-attachments/assets/f1b55159-0a78-4477-aac6-c71d39975b95">

<img width="1460" alt="image" src="https://github.com/user-attachments/assets/60514971-ecaa-4e55-9be5-4bc325403fd2">

Have you considered creating a liquidity pool on a decentralized exchange (DEX) like PancakeSwap and then locking the LP tokens? This approach allows users to buy and sell your tokens without needing to sign up through a centralized exchange (CEX).

**Comment by berry369** [comment]
Okay

**Comment by Madib036** [comment]
# This workflow will build a docker container, publish it to Google Container
# Registry, and deploy it to GKE when there is a push to the "main"
# branch.
#
# To configure this workflow:
#
# 1. Enable the following Google Cloud APIs:
#
#    - Artifact Registry (artifactregistry.googleapis.com)
#    - Google Kubernetes Engine (container.googleapis.com)
#    - IAM Credentials API (iamcredentials.googleapis.com)
#
#    You can learn more about enabling APIs at
#    https://support.google.com/googleapi/answer/6158841.
#
# 2. Ensure that your repository contains the necessary configuration for your
#    Google Kubernetes Engine cluster, including deployment.yml,
#    kustomization.yml, service.yml, etc.
#
# 3. Create and configure a Workload Identity Provider for GitHub:
#    https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation.
#
#    Depending on how you authenticate, you will need to grant an IAM principal
#    permissions on Google Cloud:
#
#    - Artifact Registry Administrator (roles/artifactregistry.admin)
#    - Kubernetes Engine Developer (roles/container.developer)
#
#    You can learn more about setting IAM permissions at
#    https://cloud.google.com/iam/docs/manage-access-other-resources
#
# 5. Change the values in the "env" block to match your values.

name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - '"main"'

env:
  PROJECT_ID: 'my-project' # TODO: update to your Google Cloud project ID
  GAR_LOCATION: 'us-central1' # TODO: update to your region
  GKE_CLUSTER: 'cluster-1' # TODO: update to your cluster name
  GKE_ZONE: 'us-central1-c' # TODO: update to your cluster zone
  DEPLOYMENT_NAME: 'gke-test' # TODO: update to your deployment name
  REPOSITORY: 'samples' # TODO: update to your Artifact Registry docker repository name
  IMAGE: 'static-site'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider' # TODO: update to your workload identity provider

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'production'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

      # Configure Workload Identity Federation and generate an access token.
      #
      # See https://github.com/google-github-actions/auth for more options,
      # including authenticating via a JSON credentials file.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2' # google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: 'Docker Auth'
        uses: 'docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567' # docker/login-action@v3
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      # Get the GKE credentials so we can deploy to the cluster
      - name: 'Set up GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@6051de21ad50fbb1767bc93c11357a49082ad116' # google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_ZONE }}'

      # Build the Docker image
      - name: 'Build and push Docker container'
        run: |-
          DOCKER_TAG="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${GITHUB_SHA}"

          docker build \
            --tag "${DOCKER_TAG}" \
            --build-arg GITHUB_SHA="${GITHUB_SHA}" \
            --build-arg GITHUB_REF="${GITHUB_REF}" \
            .

          docker push "${DOCKER_TAG}"

      # Set up kustomize
      - name: 'Set up Kustomize'
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.3/kustomize_v5.4.3_linux_amd64.tar.gz
          chmod u+x ./kustomize

      # Deploy the Docker image to the GKE cluster
      - name: 'Deploy to GKE'
        run: |-
          # replacing the image name in the k8s template
          ./kustomize edit set image LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide

**Comment by verumcoin** [comment]
Hello,

That was a private sale with a personally known peoples. So it cannot be shown somewhere in the internet. It is not a so big amount to consider it as an airdrop or ICO

At XT was an temporary accident, that was resolved and now all is okay

> Have you considered creating a liquidity pool on a decentralized exchange (DEX) like PancakeSwap and then locking the LP tokens?

We are working on it, but we want to list at DEX not a BEP20 token, but our native chain for the Verum Coin.


P.S. Is it possible to list our native Verum Chain network at Trust Wallet? What steps we need to acvhieve to accept it?

**Comment by curiouschonk** [comment]
XT should support your BEP20 token as well, not just your mainnet coin

<img width="1279" alt="image" src="https://github.com/user-attachments/assets/a898f3a0-0c6f-42d3-a37f-c6e5567d69ab">

Regarding the price in the app, that's intentional since we don't track it.

**Comment by verumcoin** [comment]
Can we be listed as a native coin on Trust Wallet?

Thank you!

**Comment by curiouschonk** [comment]
It must meet the integration criteria - https://developer.trustwallet.com/developer/wallet-core/newblockchain#integration-criteria

**Comment by berry369** [comment]
Why
