### ISSUE TITLE
### Microsoft PowerToys version

### ISSUE THREAD

**Issue by Tarhanshop** [trustwallet/assets#29199]
### Microsoft PowerToys version

0.70.1

### Installation method

PowerToys auto-update

### Running as admin

Yes

### Area(s) with issue?

Keyboard Manager

### Steps to reproduce

When the computer restarts, the remapped shortcuts do not work. I have to turn the "Enable Keyboard Manager" switch off and back on for it to work.

### ✔️ Expected Behavior

The computer boots up, the remapped shortcuts are expected to work as the user intended.

### ❌ Actual Behavior

The remapped shortcuts do not work as the user intended until the "Enable Keyboard Manager" switch is turned off and back on when the computer is restarted.

_Originally posted by @SefaMeert in https://github.com/microsoft/PowerToys/issues/26840_

**Comment by SefaMeert** [comment]
This issue no longer exists for me. It seems to be resolved. I guess this issue still exists for you.
