### ISSUE TITLE
@zahidgopang, kind reminder:  please pay fee:  **500 TWT** to the address `0xB0036dDA3110d837bA43812fA2565d61d533C317`.

### ISSUE THREAD

**Issue by 9764319764319764** [trustwallet/assets#29227]
@zahidgopang, kind reminder:  please pay fee:  **500 TWT** to the address `0xB0036dDA3110d837bA43812fA2565d61d533C317`.
 Alternatively, 2.5 BNB is also accepted (same address).

 **QR** code: [Trust]( https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=https%3A%2F%2Flink.trustwallet.com%2Fsend%3Fasset%3Dc20000714_t0x4B0F1812e5Df2A09796481Ff14017e6005508003%26address%3D0xB0036dDA3110d837bA43812fA2565d61d533C317%26amount%3D500 ) | [other wallet]( https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=0xB0036dDA3110d837bA43812fA2565d61d533C317%3Famount%3D500 )
 See the [Pull Request Fee FAQ](https://developer.trustwallet.com/assets/faq).

_Originally posted by @merge-fee-bot in https://github.com/trustwallet/assets/pull/29220#issuecomment-2380314992_

**Comment by zahidgopang** [comment]
@Cryptocool1 the logo updated right of my wallet ? all done.
