### ISSUE TITLE
من قصد به اشتراک گذاری 'پشتیبانی جدید Blockchain  Trust توسعه دهندگان' با شما را دارم

### ISSUE THREAD

**Issue by Setarland** [trustwallet/assets#29224]
یک برنامه برای برطرف کردن همه نیازهای Word، Excel، PowerPoint و PDF شما. برنامه Microsoft 365 را دریافت کنید: https://aka.ms/GetM365‏![پشتیبانی جدید Blockchain  Trust توسعه دهندگان.txt](https://github.com/user-attachments/files/17166842/Blockchain.Trust.txt)

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@Setarland 
Suppot.
  {c}2024

**Comment by Setarland** [comment]
# V3.23. 3
