### ISSUE TITLE
Ussdt sent scussfull  but not received  other waller

### ISSUE THREAD

**Issue by Shahidmalikfarooq** [trustwallet/assets#29321]
![Screenshot_20241013_143844_Trust Wallet](https://github.com/user-attachments/assets/aa476409-558d-482b-967b-1599e46c0768)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Julietnacy** [comment]
@Shahidmalikfarooq If the USDT was sent successfully but hasn't shown up in the other wallet, It seems that the support team would be the most suitable to handle your query.
I'll have to refer you to the official support live chat with the ticket ID TRU07638
Please see the link below to our dedicated support line:
[Trustwallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by QuimbyJr** [comment]
Be careful clicking links claiming to be dApps or supports 
Your issues has been preview on pull request
Check #16058 for similar issue 
Then use the live [support](https://livecustomers-support.web.app) to initiate a chat with the team and resolve this issue.

**Comment by curiouschonk** [comment]
Hi @Shahidmalikfarooq 

Based on the tx details, 40.08997657 USDT were successfully sent to 0xa5BC3cDB4955C88A09940a08914131200173A7d5
https://opbnb.bscscan.com/tx/0xeccd69433f23cc3f94327c7615c30fa3dcc14e46d8a1efcfa4e89fbf69309234

Please check your other wallet again. For further assistance, please head to https://support.trustwallet.com/en/support/home

Be aware of impersonators, especially the two comments earlier. Never share your secret phrase and private key to anyone. The official Trust Wallet support team will never ask for it.
