### ISSUE TITLE
Add logo LoanBurst (LBurst) token to trust wallet

### ISSUE THREAD

**Issue by loanbursttoken** [trustwallet/assets#2933]
Add logo LoanBurst (LBurst) token to trust wallet

Token name :LoanBurst
Token symbol :LBurst
Token decimal :18
Tokem contact address : 0x93eCD2ecDFb91aB2fEe28A8779A6adfe2851cda6

**Comment by catenocrypt** [comment]
Please open a Pull Request with the addition.
