### ISSUE TITLE
Add PME Token on Polygon blockchain

### ISSUE THREAD

**Issue by mehdi-agh** [trustwallet/assets#29494]
Dear TrustWallet Team,

We hope this message finds you well. We are submitting a request to list the PCO Land Meta Earth (PME) token on TrustWallet.

We have already paid the listing fee, as mentioned in the previous request. Since then, PME has grown significantly, now having 12,000+ holders and 39,000+ transactions.

Additionally, we would like to note that PME has recently updated its smart contract address from the old one to 0xFD1eEb2f3399872735f3Df735816c4FC607E12C4. This update has been reflected on both CoinMarketCap and CoinGecko:

https://coinmarketcap.com/currencies/pco-metaverse/
https://www.coingecko.com/en/coins/pco-metaverse
https://polygonscan.com/token/0xfd1eeb2f3399872735f3df735816c4fc607e12c4

Given the growing number of PME holders, many of whom actively use TrustWallet, we kindly ask for the listing request to be reviewed again.
@Cryptocool1  @cryptomanz1  @natedaiger  @hexorx

_Originally posted by @mehdi-agh in https://github.com/trustwallet/assets/issues/28282#issuecomment-2425309076_

**Comment by cryptomanz1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details
