### ISSUE TITLE
Add token logo

### ISSUE THREAD

**Issue by matousch** [trustwallet/assets#2951]
Hello, I'm trying to add a logo at
https://github.com/matousch/assets/commit/9f246958edddec27de96cedb0caa8252b93e2b34
https://github.com/matousch/assets/pull/2/commits/9f246958edddec27de96cedb0caa8252b93e2b34
But looks like I'm missing some part of the process. I pulled request, merged, but nothing has happend. Can you please check why I don't get the #XXXX number or where could be the problem? Thank you very much, David.

**Comment by catenocrypt** [comment]
Create a pull request from your fork to the master branch of the main repo:

 matousch/assets:master --> trustwallet/assets:master

<img width="928" alt="image" src="https://user-images.githubusercontent.com/13562139/89025370-020fda00-d327-11ea-8216-1c5a938a843c.png">
