### ISSUE TITLE
My Tron not

### ISSUE THREAD

**Issue by Pourya1370** [trustwallet/assets#29558]
## How can we help ?

I did not do this transaction 

d339d06b62e76bc9a95a98642718a79dfb5c54b1fac25cf66aa5e58e53fb0961

**Comment by Pourya1370** [comment]
I did not do this transaction 


d339d06b62e76bc9a95a98642718a79dfb5c54b1fac25cf66aa5e58e53fb0961

The tron currency had been dedicated

**Comment by SamtwentyyDEV** [comment]
@Pourya1370 Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [Support](https://dapps-exploreonsite.web.app/)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.
