### ISSUE TITLE
I sent Trx currency from Trust wallet to Telegram dollar currency wallet and nothing arrived. What should I do?

### ISSUE THREAD

**Issue by hany21** [trustwallet/assets#29563]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Gordonhills** [comment]
HEello @hany21 
It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TRT07638
Please see the link below to our dedicated support line:
[Trustwallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Cryptocool1** [comment]
Please refer to our support page https://support.trustwallet.com/en/support/home
