### ISSUE TITLE
Incorrect pull request

### ISSUE THREAD

**Issue by TheAbyss-dev** [trustwallet/assets#2968]
I've committed my assets to the wrong folder and paid the fee. the pull request is already closed. Is there a was for me to correct it without having to pay the fee again?
this is the pull request - https://github.com/trustwallet/assets/pull/2903

**Comment by catenocrypt** [comment]
I did warn you!

<img width="940" alt="image" src="https://user-images.githubusercontent.com/13562139/89031388-b2cfa680-d332-11ea-8d1d-7b06cf700042.png">

I can make an exception and correct it for you.
Is it on Ethereum or other blockchain?  What is the token contract address?  What is the correct location?

**Comment by TheAbyss-dev** [comment]
i know you warned me, it was my bad.
the token is on ethereum chain 
address - 0x1800aF9d001f7B3AF7cE7a8a72dA73722Beec377
so i guess it should be in blockchains/ethereum/assets/0x1800aF9d001f7B3AF7cE7a8a72dA73722Beec377

**Comment by TheAbyss-dev** [comment]
here's the token page on uniswap - https://uniswap.info/token/0x1800af9d001f7b3af7ce7a8a72da73722beec377

**Comment by TheAbyss-dev** [comment]
I see the fix PR. Thank you. Is it gonna be possible to apply the fee already paid?

**Comment by catenocrypt** [comment]
Done with #2975 .
