### ISSUE TITLE
How to add other Blockchain-Projects

### ISSUE THREAD

**Issue by HeroHann** [trustwallet/assets#2969]
I had a look through your paperwork on how to add a coin to Trust-Wallet. Problem is, that the Coin I wanted to add is not on one of the chains you provided. Is there any chance for outside devs to implement other chains into the app?

**Comment by catenocrypt** [comment]
Adding support for a new blockchain is possible, but it required some development work, and there are also some criteria for acceptance.
Please consult our contribution guides:

https://developer.trustwallet.com/wallet-core/newblockchain
