### ISSUE TITLE
No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message.

### ISSUE THREAD

**Issue by PGPAI** [trustwallet/assets#29716]
No token files found. If you try to add/modify a token, check the name and location of your files! Logo file must be named exactly 'logo.png'. If you are not adding a token, ignore this message.

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/29715#issuecomment-2519929748_

**Comment by PGPAI** [comment]
i have added a logo.png . u dont see it ?

**Comment by Cryptocool1** [comment]
Please create new PR, follow doc https://developer.trustwallet.com/listing-new-assets/requirements
You may want to try our Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://developer.trustwallet.com/listing-new-assets/repository_details
