### ISSUE TITLE
Delay in Processing Pull Request

### ISSUE THREAD

**Issue by EuropaCoinFun** [trustwallet/assets#29728]
Hello, @Cryptocool1!
We submitted a pull request for our token to be added to Trust Wallet, but it seems the process is delayed. Our investors are frustrated because they cannot see the token or use it properly within the Trust Wallet.
Could you please provide an update on the status of our pull request? If additional information or action is required from our side to expedite the process, we are happy to comply.

**Comment by hanabi6251** [comment]
4ヶ月よ 前の話を
