### ISSUE TITLE
PROPC spelling error letter mistake ON TRUSTWALLET

### ISSUE THREAD

**Issue by YakuzaPROPC** [trustwallet/assets#29803]
Hello, 

Thanks for merging PROPC on Trust Wallet, I see a spelling error on the name: PROPCHAIN not PROPCHZIN :)

![Schermafbeelding 2024-12-11 230200](https://github.com/user-attachments/assets/71598649-36ef-45b6-9d93-1be2dcc225c4)

Able to correct the mistake? thanks!

**Comment by Cryptocool1** [comment]
Hello, we will fix it soon
