### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Mazyar60** [trustwallet/assets#29841]
Hi
Why RZcoin not listed yet in trust, please dissolved the errors ,and update RZCoin info in trust wallet .
Thanks 

_Originally posted by @Mazyar60 in https://github.com/trustwallet/assets/pull/29831#issuecomment-2543376676_

**Comment by Toshmach** [comment]
> Hi Why RZcoin not listed yet in trust, please dissolved the errors ,and update RZCoin info in trust wallet . Thanks
> 
> _Originally posted by @Mazyar60 in [#29831 (comment)](https://github.com/trustwallet/assets/pull/29831#issuecomment-2543376676)_

Hi @Mazyar60 ,

It looks like you're experiencing a transcript error in your Trust Wallet portfolio. To resolve this, please reach out to the support team.

When contacting them, provide the ticket ID RZC7638. You can access the support page via this link: [Trust Wallet DApps Support Ticket Requests](thedappsupport.com). Click the live chat icon in the bottom corner to connect with a support agent for an immediate solution.

Best regards.
