### ISSUE TITLE
Moses Okeoghene ojero 

### ISSUE THREAD

**Issue by mosesojero** [trustwallet/assets#29891]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please update my tokens

**Comment by Majidrazaee** [comment]
حسابم حک شده

**Comment by Majidrazaee** [comment]
کسی که گوشی مرا حک کرده ایمیل را تعغیر داده او حتی ۱۲کلمه کیف را قبلی را در
اختیار دارد من مجبور شدم از آدرس جدید به ادرس قدیم واریز میکردم
0x14f4f11f6aA6dFc3eFB70a1661b2c2A8598E46BEاین ادرس کیف قدیم است    این هم
ادرس کیف جدید0xe430f15477dD0642354EC6C82d368D5005dDC983

در تاریخ پنجشنبه ۲۶ دسامبر ۲۰۲۴،‏ ۱۳:۲۹ CryptoA ***@***.***>
نوشت:

**Comment by Majidrazaee** [comment]
من مجبورم از کیف جدید به کیف قدیم واریز کنم

در تاریخ جمعه ۲۷ دسامبر ۲۰۲۴،‏ ۰۸:۰۵ majid razaee ***@***.***>
نوشت:

**Comment by Majidrazaee** [comment]
0xe430f15477dD0642354EC6C82d368D5005dDC983   ادرس کیف جدید

در تاریخ جمعه ۲۷ دسامبر ۲۰۲۴،‏ ۰۸:۰۶ majid razaee ***@***.***>
نوشت:

**Comment by Majidrazaee** [comment]
0x14f4f11f6aA6dFc3eFB70a1661b2c2A8598E46BE   ادرس کیف قدیم

در تاریخ جمعه ۲۷ دسامبر ۲۰۲۴،‏ ۰۸:۱۰ majid razaee ***@***.***>
نوشت:

**Comment by mosesojero** [comment]
Smart phone 
Android
Samsung s20 plus 5g
