### ISSUE TITLE
Add logo Wellness Cash Coin (WCC) to trust wallet

### ISSUE THREAD

**Issue by Fosterindia** [trustwallet/assets#3004]
Add logo Wellness Cash Coin (WCC) to trust wallet

Token Name : Wellness Cash Coin
Token symbol : WCC
Token decimal : 18
Token contract address : 0xad5307C84B31F0B4E1C8bCaA67704F57FbdAe74F

![0xad5307C84B31F0B4E1C8bCaA67704F57FbdAe74F](https://user-images.githubusercontent.com/69118342/89143873-ae410300-d569-11ea-996c-e958d0a21ba4.png)

**Comment by zachzwei** [comment]
Please follow this guide to submit a new asset:
https://community.trustwallet.com/t/how-to-submit-a-new-token-asset/3863/2
