### ISSUE TITLE
How to delist token from TW?

### ISSUE THREAD

**Issue by advexon** [trustwallet/assets#3005]

**Comment by advexon** [comment]
I tried to delist our token by adding the smart contract address to the blacklist JSON file but it is still showing on the TW app. I also made the payment which was required for pull request by TW bot.

**Comment by catenocrypt** [comment]
Probably it should be in checksum format in blacklist as well, 0x1Cdca6811e2ef23D6099d09D2754211d3c7b5aF1 . I will try.
( #2529 ).

**Comment by catenocrypt** [comment]
Solving with #3011 .
@advexon , give it a few hours, and check it again.  If still not correct, please reopen this issue.

**Comment by advexon** [comment]
> Solving with #3011 .
> @advexon , give it a few hours, and check it again. If still not correct, please reopen this issue.

The issue was not solved. I tried many ways but didn't work.
As you mentioned to remove the contract address from the whitelist, I couldn't find the contract address on the whitelist section. The contract isn't in the whitelist to be removed.
