### ISSUE TITLE
Add logo Wellness Cash Coin (WCC) to trust wallet

### ISSUE THREAD

**Issue by Fosterindia** [trustwallet/assets#3126]
Add logo Wellness Cash Coin (WCC) to trust wallet

Token Name : Wellness Cash Coin
Token symbol : WCC
Token decimal : 18
Token contract address : 0xad5307C84B31F0B4E1C8bCaA67704F57FbdAe74F
0xad5307C84B31F0B4E1C8bCaA67704F57FbdAe74F

**Comment by catenocrypt** [comment]
Please open new pull request for new coin logo (if you haven't done so yet).
