### ISSUE TITLE
Add CZK20 token logo #3136

### ISSUE THREAD

**Issue by matousch** [trustwallet/assets#3158]
## How can we help ?

Hello Victor, you have merged my pull request #3136, but the logo hasn't changed. Could you check, please? Thank you, David.

**Comment by matousch** [comment]
I still need this to be fixed. Can you help? David.

**Comment by matousch** [comment]
I added the logo to https://github.com/matousch/assets/blob/e8ddfdb1356c86d0722f8eae440df0da68dd8a11/blockchains/ethereum/assets/0x48b43ef8ba132fa6153b494ba67acefdd4ac3ecb/logo.png
looks like it did not merged correctly

**Comment by catenocrypt** [comment]
TOTR coin, merged with #3136, contract https://etherscan.io/address/0x1BE9F6861D11f2fd363a75225040eDE6374b65bF, is available in Trust Wallet.  Closing.

**Comment by matousch** [comment]
TOTR coin was merged correctly earlier at https://github.com/trustwallet/assets/pull/2970
CZK20 is a different issue and pull request, the logo still not merged correctly. Please help. https://github.com/matousch/assets/blob/e8ddfdb1356c86d0722f8eae440df0da68dd8a11/blockchains/ethereum/assets/0x48b43ef8ba132fa6153b494ba67acefdd4ac3ecb/logo.png

**Comment by catenocrypt** [comment]
@matousch , can you specify which PR contained CYK20?
#3136 contained TOTR logo:
https://github.com/trustwallet/assets/pull/3136/files
https://github.com/matousch/assets/blob/ffbee6bb03f16d1c60a69b1bace10aa12fe999c5/blockchains/ethereum/assets/0x1BE9F6861D11f2fd363a75225040eDE6374b65bF/logo.png
![image](https://user-images.githubusercontent.com/13562139/89797204-ef698200-db2a-11ea-985c-519b29be76d5.png)

**Comment by matousch** [comment]
https://github.com/matousch/assets/pull/3
https://github.com/matousch/assets/blob/e8ddfdb1356c86d0722f8eae440df0da68dd8a11/blockchains/ethereum/assets/0x48b43ef8ba132fa6153b494ba67acefdd4ac3ecb/logo.png
