### ISSUE TITLE
Pull request new token. Not sure everything went good

### ISSUE THREAD

**Issue by Christian-RIZE** [trustwallet/assets#3196]
I recently made a pull request for a new token. 

However, I see many projects which get's within a few hours reply. I am waiting way longer compared to those projects. 

See https://github.com/rizetoken/assets/pull/1

Thanks in advance

**Comment by catenocrypt** [comment]
@Christian-RIZE , no, it is not correct.  You made a PR from a branch in your fork to the master branch of your fork.  Target should be master branch of truswallet/assets repo!

<img width="672" alt="image" src="https://user-images.githubusercontent.com/13562139/89791698-eb863180-db23-11ea-884d-349000fd9348.png">
