### ISSUE TITLE
Add Community Token (COM) to trust wallet

### ISSUE THREAD

**Issue by ComToken** [trustwallet/assets#3201]
Add Community Token (COM) to trust wallet

Token Name : Community Token
Token Symbol : COM
Token Supply: 1,000,000
Token Contract Address : 0x1B4052d98fb1888C2Bf3B8d3b930e0aFf8A910dF
![0x1B4052d98fb1888C2Bf3B8d3b930e0aFf8A910dF](https://user-images.githubusercontent.com/69433040/89762877-eec2f280-db0e-11ea-9a88-47911d7faa38.png)

**Comment by ComToken** [comment]
already paid .please update sir

**Comment by ComToken** [comment]
new request https://github.com/trustwallet/assets/pull/3210 

already paid it from this sir 

https://github.com/trustwallet/assets/pull/3198

**Comment by ComToken** [comment]
Please update now sir

**Comment by catenocrypt** [comment]
#3210 has been merged already, closing.
