### ISSUE TITLE
Consider to allow transparent PNGs only

### ISSUE THREAD

**Issue by jondoe1337** [trustwallet/assets#3300]
**Is your feature request related to a problem? Please describe.**
When using logos that are not transparent on a site that has a dark background it doesn't look nice.

**Describe the solution you'd like**
Logo applications must provide a transparent background PNG.

**Describe alternatives you've considered**
Transparent PNGs will look better on sites with different backgrounds than white.

**Additional context**
Example - Tether Logo: https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png

**Comment by catenocrypt** [comment]
Thanks for the idea, this has occured to us as well, but was not yet addressed.
Note that transaparent backgroun can also pose problems: a dark logo with transparent background is hard to see on dark background (the app has normal and dark mode).

**Comment by jondoe1337** [comment]
Makes sense. However in that case I would want to have it transparent as well to change it for myself easier.
