### ISSUE TITLE
add Madaza Option (MADAZA) to trust wallet logo update

### ISSUE THREAD

**Issue by little-einsteins** [trustwallet/assets#3320]
add Madaza Option (MADAZA) to trust wallet logo update

add Madaza Option (MADAZA) to trust wallet logo update
ERC20 TOKEN NAME : Madaza Option
ERC20 TOKEN SYMBOL: MADAZA
ERC20 TOKEN SUPPLY: 38,000,000 MADAZA
ERC20 TOKEN CONTRACT ADDRESS: 0x4b0516FED07e12a6a76a8cBf6b9A0ecdC808206e

![0x4b0516FED07e12a6a76a8cBf6b9A0ecdC808206e](https://user-images.githubusercontent.com/69500640/90169853-c9f3a700-ddbc-11ea-8879-d20f1ef958dd.png)

**Comment by little-einsteins** [comment]
ok

**Comment by catenocrypt** [comment]
Please open a pull request with new logo.
https://developer.trustwallet.com/add_new_asset
