### ISSUE TITLE
Add WINSSHI (WNS) to trust wallet logo update

### ISSUE THREAD

**Issue by winsshi** [trustwallet/assets#3367]
Add WINSSHI (WNS) to trust wallet logo update

TOKEN NAME- WINSSHI
TOKEN SYMBOL- WNS
TOTAL SUPPLY - 1,000,000,000 WNS
SMART CONTRACT ADDRESS-0x4a0eedf6e95581cda46a767e612e83731c0cd418

![0x4a0eedf6e95581cda46a767e612e83731c0cd418](https://user-images.githubusercontent.com/69614174/90312080-3be40180-df1f-11ea-9e43-12e8cf53d8b0.png)

**Comment by little-einsteins** [comment]
please need urgent sir

**Comment by winsshi** [comment]
logo is not show

**Comment by catenocrypt** [comment]
Please open a pull request with new logo.
https://developer.trustwallet.com/add_new_asset
