### ISSUE TITLE
Add BETX Share (BETX) to trust wallet logo update

### ISSUE THREAD

**Issue by BETxShare** [trustwallet/assets#3412]
Add BETX Share (BETX) to trust wallet logo update

TOKEN NAME- BETX Share
TOKEN SYMBOL- BETX
TOTAL SUPPLY - 350,000,000 BETX
Decimals:2
CONTRACT ADDRESS- 0x11799ef12A8b4e79865abb167DF88f14629d1E4f

![0x11799ef12A8b4e79865abb167DF88f14629d1E4f](https://user-images.githubusercontent.com/69656642/90496226-3119ae80-e163-11ea-83b4-05de27b919a0.png)

**Comment by BETxShare** [comment]
already paid

**Comment by catenocrypt** [comment]
Please hold your horses, pull request processing is a manual activity, takes around a day.

**Comment by catenocrypt** [comment]
PR has been processed, but one of the token addresses provided is incorrect.  Please check #3410 .

**Comment by BETxShare** [comment]
Add BETX Share (BETX) to trust wallet logo update

TOKEN NAME- BETX Share
TOKEN SYMBOL- BETX
TOTAL SUPPLY - 350,000,000 BETX
Decimals:2
CONTRACT ADDRESS- 0x11799ef12A8b4e79865abb167DF88f14629d1E4f

correct detail sir

**Comment by catenocrypt** [comment]
Has been added already

**Comment by BETxShare** [comment]
please update new logo 

![0x11799ef12A8b4e79865abb167DF88f14629d1E4f](https://user-images.githubusercontent.com/69656642/90590207-90c49800-e1fd-11ea-8d74-d2abbed21a6e.png)

**Comment by BETxShare** [comment]
this is transparent logo sir 

BETX Share (BETX) to trust wallet logo update

TOKEN NAME- BETX Share
TOKEN SYMBOL- BETX
TOTAL SUPPLY - 350,000,000 BETX
Decimals:2
CONTRACT ADDRESS- 0x11799ef12A8b4e79865abb167DF88f14629d1E4f

![0x11799ef12A8b4e79865abb167DF88f14629d1E4f](https://user-images.githubusercontent.com/69656642/90590229-a043e100-e1fd-11ea-881e-b3e8bff756ba.png)
