### ISSUE TITLE
Add Bethel Coin (Bethel) to trust wallet logo update

### ISSUE THREAD

**Issue by bethelcoin500** [trustwallet/assets#3415]
Add Bethel Coin (Bethel) to trust wallet logo update

TOKEN NAME- Bethel Coin
TOKEN SYMBOL- Bethel
TOTAL SUPPLY - 500,000,000,000 Bethel
Decimals: 18
CONTRACT ADDRESS-0xa497473a983aAC21519737fb8E210F34Cc96b016

![0xa497473a983aAC21519737fb8E210F34Cc96b016](https://user-images.githubusercontent.com/69813956/90444356-5b378600-e0fb-11ea-9cfe-742f697a1944.png)

**Comment by catenocrypt** [comment]
Has been added already #3414 .
