### ISSUE TITLE
Please update Internxt's token logo

### ISSUE THREAD

**Issue by fvsegarra** [trustwallet/assets#3578]
Hey guys,
It's Fran, CEO at Internxt.
Mind updating our logo https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/assets/0xa8006C4ca56F24d6836727D106349320dB7fEF82/logo.png to https://internxt.com/img/round.png 
Thank you

**Comment by zachzwei** [comment]
Please follow this guide in order to submit a pull request for the token logo update.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863/2
