### ISSUE TITLE
Please add  Logo

### ISSUE THREAD

**Issue by FiolaNetwork** [trustwallet/assets#3599]
Please add Fiola Network Logo
Fiola Token properties
-Ticker: FLA
-Total Suply: 1,000,000,000
-Decimal: 18
-Contract Address:
0x7bE5901F679BDE8202a123c84C19
BBCE2CF3449B
https://etherscan.io/token/0x7bE5901F679BDE8202a123c84C19BBCE2CF3449B
Logo Download link. https://www.dropbox.com/s/83ofu9ab26nxr24/FiolaNetworkLogo.jpg?dl=0

**Comment by zachzwei** [comment]
Please follow the guide below to submit this new asset.
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

You can follow this format when adding an info.json file:

``` {
   "name":"Bitcoin",
   "website":"https://bitcoin.org",
   "source_code":"https://github.com/bitcoin",
   "white_paper":"https://bitcoin.org/bitcoin.pdf",
   "short_description":"Bitcoin is a cryptocurrency and worldwide payment system.",
   "explorer":"https://blockchain.info",
   "research":"https://research.binance.com/en/projects/bitcoin"
}
