### ISSUE TITLE
FREE coin (TRC10 token) does not display price (based on CMC or Coingecko)

### ISSUE THREAD

**Issue by TheFreeCoin** [trustwallet/assets#3666]
The FREE coin is a multi-blockchain token : ETH ERC20 and TRON TRC10 (similar approach as for example USDT)

Both versions are supported by Trust. Both versions are the same coin, with 1 price.

For the ERC20 FREE coin, TRUST displays a correct price.

For the TRC10 FREE version, this price is not displayed by TRUST.

Links to collect the price for the TRC10 version of the FREE coin 

1) https://coinmarketcap.com/currencies/free-coin/
2)https://www.coingecko.com/en/coins/free-coin

Thank you to also display price for FREE coin TRC10 in Trust

**Comment by catenocrypt** [comment]
This is indeed the case, Coin Market Cap returns only one instance of this token (the ERC20 version).
There is no way to fix this easily on our side, plus a token of 125 tx so far does not justify much effort on our side, sorry.

https://www.coingecko.com/en/coins/free-coin

**Comment by TheFreeCoin** [comment]
@catenocrypt  CMC only has 1 price for both ERC20 and TRC10 tokens of the same coin (like they also have only 1 price for USDT, which has ERC20, TRC10 and Omni tokens).
So please display the CMC or Coingecko price for both the ERC20 and TRC10 version of the token. I assume you do this already for USDT ?


PS : This TRC10 token is heavily traded on PoloniDex, in "self listing" mode, but this is not included in "tron transactions"
