### ISSUE TITLE
add Logo and information for Popcorn Token (CORN)

### ISSUE THREAD

**Issue by popcorntoken** [trustwallet/assets#3707]
add Logo and information for Popcorn Token (CORN)
Token Name : Popcorn Token
Token Symbol : CORN
Token Supply :1,811,032.06 CORN
Contract: 0x3080ec2A6960432F179c66D388099A48E82e2047

![logo](https://user-images.githubusercontent.com/70378818/91688006-9e273e00-eb7e-11ea-9bf6-f029be9f4f8f.png)

**Comment by zachzwei** [comment]
Please submit a PR by following this guide:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
