### ISSUE TITLE
Add Fiola Logo 

### ISSUE THREAD

**Issue by FiolaNetwork** [trustwallet/assets#3785]
Fiola Token properties 
-Ticker: FLA
-Total Suply: 1,000,000,000
-Decimal: 18
-Contract Address: 0x7bE5901F679BDE8202a123c84C19BBCE2CF3449B
-Website: https://fiola.network/
[FiolaNetwork Logo Download Link](https://www.dropbox.com/s/r4pdun8bxq52v5y/FiolaNetworkLogo.jpg?dl=0) (https://www.dropbox.com/s/r4pdun8bxq52v5y/FiolaNetworkLogo.jpg?dl=0) https://etherscan.io/token/0x7bE5901F679BDE8202a123c84C19BBCE2CF3449B

**Comment by catenocrypt** [comment]
You need to create a pull request, containing logo.png and info.json files, in the proper location.
See: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
