### ISSUE TITLE
add logo YFIBusiness.Finance (YFIB) to trust wallet

### ISSUE THREAD

**Issue by yfibusiness** [trustwallet/assets#3795]
please check it yfibusiness@df5f1c3

add logo YFIBusiness.Finance (YFIB) to trust wallet
Token Name :YFIBusiness.Finance
Token Symbol : YFIB
Total Supply: 30,000 YFIB
Token Contract: 0x47632da9227e322eda59f9e7691eacc6430ac87c

**Comment by catenocrypt** [comment]
Please open a PR with the new files, as described here
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
