### ISSUE TITLE
DPC TRC20 LOGO UPDATE

### ISSUE THREAD

**Issue by nozaif** [trustwallet/assets#3798]
Kindly update dpc trc20 coin logo on your wallet About on all other tron wallets above logo added kindly update it in your wallet
![1599240667346](https://user-images.githubusercontent.com/70771270/92271568-7c70e280-ef01-11ea-9e14-f3f34596e83e.png)

**Comment by catenocrypt** [comment]
Please open a PR with the new files, as described here
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
