### ISSUE TITLE
We will be closing this for now as we do not see that much activity with this token.

### ISSUE THREAD

**Issue by Dice-finance-child** [trustwallet/assets#3849]
We will be closing this for now as we do not see that much activity with this token.
You can reopen when you have met the requirements mentioned here:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

_Originally posted by @zachzwei in https://github.com/trustwallet/assets/pull/3533#issuecomment-678646517_

-------------------------------------------------------------------------------------- 

hello we were hoping to see if we could reopen this pull request now that we are over all of the minimum requirements. If there are any issues with this request please let me know.

https://etherscan.io/token/0xd55BD2C12B30075b325Bc35aEf0B46363B3818f8
Holders:
588 addresses

**Comment by catenocrypt** [comment]
PR #3533 reopened.
