### ISSUE TITLE
BitBall (BTB) logo correction request.

### ISSUE THREAD

**Issue by BitballErc20** [trustwallet/assets#4052]
**Describe the bug**
Hi, recently a lot of our community members are asking us regarding the different logo of BitBall BTB on Trustwallet app. 
**To Reproduce**
While adding BitBall tokens, trust wallet app still shows the old logo.
BTB contract: https://etherscan.io/token/0x06e0feb0d74106c7ada8497754074d222ec6bcdf
This is our logo which can be verified on coingecko, CoinMarketCap, etherscan or any other. 
![562051F0-2616-4DED-B7F9-460151D7EA20](https://user-images.githubusercontent.com/39954951/93667681-21c3b300-facb-11ea-8f00-a597a6e85dce.jpeg)

**Expected behavior**
Our official logo should show when a user adds BTB token address on trust wallet app.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 Chrome or App
**Smartphone (please complete the following information):**
 - N/A

**Additional context**
If any other questions regarding this request, please contact us on Support@bitball-btb.com or Bitball@mail.com

**Comment by catenocrypt** [comment]
There is no info on ERC20 token `0x06e0feb0d74106c7ada8497754074d222ec6bcdf`.  Are you sure it was added?  In which PR?  When?

**Comment by BitballErc20** [comment]
Hello, thanks for your reply.
If it was not added then why it shows our old logo when a user adds BTB contract address?
