### ISSUE TITLE
want to add my token logo

### ISSUE THREAD

**Issue by MuzammalRamzan** [trustwallet/assets#4510]
## How can we help ?

how to pay fee to add token logo here!
because i have sent token logo request many times!

**Comment by catenocrypt** [comment]
You need to create a Pull Request into trustwallet/assets repository, detailed docs on below link.
Where did you submit requests?
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved

**Comment by MuzammalRamzan** [comment]
I have submit three times in same repo!
either we have to pay fee for it?

**Comment by catenocrypt** [comment]
What is PR number?  Fee has to be paid for every PR.
