### ISSUE TITLE
Issue with displaying JUL and JULb tokens on Trust wallet mobile application

### ISSUE THREAD

**Issue by RohitChangediya** [trustwallet/assets#4584]
**Describe the bug**
The JUL and JULb tokens are no more visible on trust wallet mobile applications, the token was searchable earlier but suddenly it stopped showing the tokens and details

**To Reproduce**
1. search for JUL or JULb tokens in the mobile app and you see tokens without logo and information

**Expected behavior**
The token is expected to be seen with the logo and information on the app which was seen earlier

**Screenshots**
![photo_2020-10-24_11-41-23](https://user-images.githubusercontent.com/7242037/97069421-e5193900-15ed-11eb-9e14-4a0f56799c59.jpg)

**Desktop (please complete the following information):**
 
**Smartphone (please complete the following information):**
 - Android 

**Additional context**

**Comment by RohitChangediya** [comment]
Hi @catenocrypt we are awaiting a fix for this issue!

Thank you

**Comment by zachzwei** [comment]
Try re-importing your wallet. Not seeing this issue right now on our current builds.
https://community.trustwallet.com/t/how-to-re-import-your-wallet/564
