### ISSUE TITLE
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.

### ISSUE THREAD

**Issue by AcapSLP** [trustwallet/assets#4843]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863#how-to-get-approved
This token has below-limit usage yet (335). Rejecting PR for now. Please come back to us when all criteria are met.

https://etherscan.io/token/0xC626e0619aC79AFEa9281c8eB9b1a9f9D3Fab532

_Originally posted by @catenocrypt in https://github.com/trustwallet/assets/pull/4838#issuecomment-728961324_

This was posted 10 hours ago and I just sent TWT without refreshing the page so i didnt see it. is our TWT gone for good or can you please send it back to bnb1fkpwrmntgryynvm7nsljaem2ey66cljqvyc0jr    ?

**Comment by AcapSLP** [comment]
Can you guys help us and either add our token logo or send us back our TWT? We are not a scam token, you can come to our community and see we are not a scam we are a small currency. if you absolutely cannot add the logo can we get our TWT back? I didn't refresh the page and see the request was already denied 10 hours before I sent the TWT. We need our token logo on here because there is a REAL scammer who has issued a phishing token with the same name on Uniswap with 70 ETH liquidity

**Comment by AcapSLP** [comment]
![Screenshot_2020-11-18 Uniswap Info](https://user-images.githubusercontent.com/72445644/99469093-ec580c00-2939-11eb-8532-abdc53b29397.png)
Look! You can see the scam token (FRC) appears above us (FR) in the search.

**Comment by AcapSLP** [comment]
https://t.me/freedomreserve1 come here and check us.

**Comment by AcapSLP** [comment]
There are hundreds of users who have this token stored in CCTip tipping bot its just not visible on-chain

**Comment by catenocrypt** [comment]
Please use the PR for communicating about the PR
