### ISSUE TITLE
only 1000 assets, 5000 are removed for Ethereum, how do I find the rest?

### ISSUE THREAD

**Issue by uniterminal** [trustwallet/assets#4945]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by quantifydefi** [comment]
So trustwallet claims to support all Ethereum token assets, but in reality that is not true as this is labeled "wontfix"... all I am asking for is a location where all of the assets can be found and not a truncated version of the repo

**Comment by catenocrypt** [comment]
This doe not make sense, what do you mean?
Trust wallet supports _all_ ERC20 tokens, and additionally 6000 have logo as well.

```
$ ls blockchains/ethereum/assets/ | wc
    6069    6069  260967
```

**Comment by quantifydefi** [comment]
I mean where can I go to find the other 5000+ assets because github truncates the repo... 
![github](https://user-images.githubusercontent.com/71191084/101060527-8389aa00-355d-11eb-9a81-123f9d4473da.JPG)

**Comment by catenocrypt** [comment]
LOL  That's only in the web display.  Clone it locally or use Github Desktop App.
