### ISSUE TITLE
3 days gone but no respond on my team pull request

### ISSUE THREAD

**Issue by rickyponting632** [trustwallet/assets#5142]
0x2090c8295769791ab7A3CF1CC6e0AA19F35e441A #5133
My other team member posted pull request #5133 3 days ago , fee also paid but nobody is looking at the request to process it and add token . 
Why they taking so long 
Developers are very slow to act and don’t care about users fee. That fee is lot of money so please reply .

**Comment by catenocrypt** [comment]
PR has been commented.  Sorry for delay.
