### ISSUE TITLE
Token merged into trust wallet assets

### ISSUE THREAD

**Issue by tusharsingh7** [trustwallet/assets#5145]
My pull request #5136 is successfully merged into trust wallet assets . 
In how much time it will reflect on trust wallet and also on uniswap . #5136

**Comment by catenocrypt** [comment]
For me a search for 'alch' shows Alchemy with the updated logo.

**Comment by tusharsingh7** [comment]
Yeah but token information like website , short description not showing up till now .

**Comment by tusharsingh7** [comment]
@catenocrypt
