### ISSUE TITLE
we have paid the fee previously. please skip merge fee bot.

### ISSUE THREAD

**Issue by AcapSLP** [trustwallet/assets#5163]
Hi! In order to compensate for the efforts of processing PRs, we kindly ask for a contribution.

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/5162#issuecomment-749626385_

We have previously paid the fee. It was said that this fee would be carried over since we paid 10 hours after our first pr was rejected.

https://explorer.binance.org/tx/9AD89AB7515C0E12EF47AB4DB2D587F5C8311A80D69909FF65A5430C5A1805C1

please could you skip the merge fee bot before reviewing our request, thank you for your extra efforts in advance.

**Comment by AcapSLP** [comment]
@zachzwei remember you said our fee would carry over?

**Comment by catenocrypt** [comment]
Please handle inside the PR.  Previous fee can be carried over, don't worry.
