### ISSUE TITLE
> It shows no price, I suppose. Is it listed on CMC?

### ISSUE THREAD

**Issue by congbkhit** [trustwallet/assets#5205]
> It shows no price, I suppose. Is it listed on CMC?

@catenocrypt I want to update price of my token. How to do it? 
This is my token https://coinmarketcap.com/currencies/richlab-token/ on CMC.
Please help me.

_Originally posted by @congbkhit in https://github.com/trustwallet/assets/issues/4376#issuecomment-748495222_

**Comment by UdayBindal2312** [comment]
it is listed on justswap and oneswap  not on cmc

**Comment by UdayBindal2312** [comment]
No , listed on oneswap
