### ISSUE TITLE
AAVE aTokens need an update

### ISSUE THREAD

**Issue by RebelCoderRU** [trustwallet/assets#5330]
Hello.

AAVE [aTokens](https://aave.com/atokens) have moved to Version 2. Trust wallet has a list of V1, and they don't work. I had to add aTokens manually to view AAVE balance. There is no icon, $ amount, and it is not included in total wallets funds amount.

![tw_aave](https://user-images.githubusercontent.com/20476773/105078332-818c9380-5a96-11eb-977a-72dffe210894.jpg)

aTokens list needs to be updated to support V2.

**Comment by RebelCoderRU** [comment]
Sorry, why did this get a `wontfix` tag? Will this be looked at for the upcoming release?

**Comment by duc811997** [comment]
> Hello.
> 
> AAVE [aTokens](https://aave.com/atokens) have moved to Version 2. Trust wallet has a list of V1, and they don't work. I had to add aTokens manually to view AAVE balance. There is no icon, $ amount, and it is not included in total wallets funds amount.
> 
> ![tw_aave](https://user-images.githubusercontent.com/20476773/105078332-818c9380-5a96-11eb-977a-72dffe210894.jpg)
> 
> aTokens list needs to be updated to support V2.

**Comment by helpfulBrother** [comment]
@RebelCoderRU - although there is no movement on this issue @sirsoth is working with TW to provide all the required info.

We are committed to getting this resolved 👍

**Comment by vikmeup** [comment]
Follow the guidelines to submit changes: https://developer.trustwallet.com/add_new_asset
