### ISSUE TITLE
Integrate automated pulling of trading pairs from Uniswap And PancakeSwap

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/assets#5331]
**Is your feature request related to a problem? Please describe.**

We need to enable automatic pull for pairs that are:
- have at least $1M in liquidity

Also this should include ability to add specific pairs manually, when needed. 

Asset information could be pulled from: https://api.trustwallet.com/v1/assets/c714_tBTCB-1DE
 
#### Uniswap: 
List: https://github.com/trustwallet/assets/blob/master/blockchains/ethereum/tokenlist.json
Tokens info: https://info.uniswap.org/tokens
API: https://uniswap.org/docs/v2/API/queries/

#### PancakeSwap: 
List: https://github.com/trustwallet/assets/blob/master/blockchains/smartchain/tokenlist.json
Tokens: https://pancakeswap.info/

**Comment by catenocrypt** [comment]
PancakeSwap info (https://pancakeswap.info ) uses bscgraph.org Subgraph to retrieve pairs:
https://api.bscgraph.org/subgraphs/name/wowswap
This is not an official deployed Subgraph, but appears to be using the same framework.
(there is also an undeployed subpgraph attempt by Panckaswap https://thegraph.com/explorer/subgraph/pancake-swap/pancakeswap )

BTW, the Graph infrastructure (https://thegraph.com ) seems to have some potential for future integrations for us.

```
curl -d '{"operationName":"pairs","variables":{},"query":"query pairs {\n  pairs(first: 200, orderBy: trackedReserveETH, orderDirection: desc) {\n    id\n    __typename\n  }\n}\n"}' https://api.bscgraph.org/subgraphs/name/wowswap
```
