### ISSUE TITLE
Just logo updates

### ISSUE THREAD

**Issue by bi0hazard12** [trustwallet/assets#5372]
## How can we help ?

Hello,

Just want to try to understand if we need to pay a fee just for some logos updates? We have already the tokens accept and running for few months on trustwallet, but we updated our logos and wanted to update it again but since isn't a new listing we want to understand if that's okay just to request for a update logo without fee?

Thank you so much

**Comment by vikmeup** [comment]
Just submit pull request, the team will review it.
