### ISSUE TITLE
Please list and add logo for CHG Coin

### ISSUE THREAD

**Issue by stealthmachines** [trustwallet/assets#5387]
Thank you in advance!!!

ICO date Dec. 2017 
ICO price $0.21/coin
https://chgcoin.org
https://wecharg.com
https://forum.chgcoin.org
Youtube- https://www.youtube.com/channel/UCf8IU41uJ0h5TqhpftKwD_Q
FB- https://www.facebook.com/ChargCoin/
https://etherscan.io/token/0xc4a86561cb0b7ea1214904f26e6d50fd357c7986
18 Decimals
Ticker: CHG
Name: Charg Coin
logo - 
![image](https://user-images.githubusercontent.com/24325826/105802709-f9583380-5f58-11eb-97ea-cffbdafed192.png)
Pool link: https://info.uniswap.org/token/0xc4a86561cb0b7ea1214904f26e6d50fd357c7986
Json List Link: https://chgcoin.org/CHG_v_0_0_0.json

CMC- https://coinmarketcap.com/currencies/charg-coin/
Gecko - https://www.coingecko.com/en/coins/charg-coin

CHG 2.0 coming soon - https://stats.chgcoin.org/

Thank you!  Blessings!

**Comment by vikmeup** [comment]
Follow: https://developer.trustwallet.com/add_new_asset
