### ISSUE TITLE
Add ETH JSON-RPC Compatible Chain

### ISSUE THREAD

**Issue by scott-ss** [trustwallet/assets#5482]
- Is there a standard contact window or process for adding an Ethereum compatible chain to Trust Wallet?
- The implementation is derived from a recent go-ethereum code so the JSON-RPC compatibility is high.

**Comment by catenocrypt** [comment]
There is a lot of info on this here:
https://developer.trustwallet.com/add_new_asset

I recommend Trust Developers telegram channel for questions  https://t.me/trust_developers
