### ISSUE TITLE
About uploading Dapp

### ISSUE THREAD

**Issue by ethplayer** [trustwallet/assets#549]
## How can we help ?

What do I need to do to help upload my Dapp to the New Dapp plate

**Comment by ethplayer** [comment]
> ## 我们能帮你什么吗 ？
> 我需要做什么来帮助将Dapp上传到New Dapp板上
I want to put Dapp in this section

**Comment by ethplayer** [comment]
> > ## 我们能帮你什么吗？
> > 我需要做什么来帮助将DAPP上传到新DAPP板上
> > 我想把DAPP在本节

![QQ图片20191029165906](https://user-images.githubusercontent.com/56289556/67752278-aea5ee00-fa6d-11e9-8cb3-405c03a46d58.jpg)

**Comment by ethplayer** [comment]
> ## How can we help ?
> What do I need to do to help upload my Dapp to the New Dapp plate

I want to put Dapp in this section
![2019](https://user-images.githubusercontent.com/56289556/67752778-9387ae00-fa6e-11e9-92ca-71e8d51edc22.jpg)

**Comment by kolya182** [comment]
Submit this form https://docs.google.com/forms/d/e/1FAIpQLSd5p9L78zKXIiu9E5yFRPf5UkvsLZ7TbUDLFBRIi1qMd8Td4A/viewform
