### ISSUE TITLE
Trust wallet does not show price of ditto token

### ISSUE THREAD

**Issue by Timidan** [trustwallet/assets#5572]
## How can we help ?

Ditto token [info.json](https://github.com/trustwallet/assets/pull/5182/commits/6d285392b17b463f42fa0e488b539e50f0ce1be5#diff-f12faee6a1c83268284573e6d598467afa0eecb35409d88b94ca1b94adab8378) has been added to the trust wallet assets and fee has been paid. but Trust wallet does not show the price of ditto on the app..Ditto is available on [coingecko](https://www.coingecko.com/en/coins/ditto)

Are there any further actions required?

Thanks

**Comment by Timidan** [comment]
Just saw that this was assigned.... If you have any questions about ditto, I will be very happy to answer them🙂

**Comment by Iamdeadlyz** [comment]
Hi @Timidan. The price of DITTO (BEP20) should appear now.

**Comment by Timidan** [comment]
Yep.. Thanks a lot.... Closing now
