### ISSUE TITLE
add logo to truse wallet on bep20 platform

### ISSUE THREAD

**Issue by hieplx** [trustwallet/assets#5608]
## How can we help ?

how do i add my coin logo to trust wallet

**Comment by catenocrypt** [comment]
Please refer to this documentation:  https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

One convenient way is to use our web app: go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See  https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
