### ISSUE TITLE
When updating tokenlist, remove tokens with no pairs

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/assets#5769]
Pairs are nulled and filled based on the result returned from API; but tokens are not removed currently.

**Comment by KunKaxx** [comment]
Don’t understand. Sorry

**Comment by Maxusz666** [comment]
)

**Comment by Maxusz666** [comment]
Ok

**Comment by KunKaxe** [comment]
.

**Comment by juan-silveira** [comment]
How to suggest update at tokenlist.json in smartchain in order to get new added coins over the last two weeks?

**Comment by catenocrypt** [comment]
Was updated yesterday, but no eligible tokens found.
