### ISSUE TITLE
Add the metadata to assets, it can help the user understand better

### ISSUE THREAD

**Issue by TamirTian** [trustwallet/assets#597]
I think we can add metadata to the 'assets' path.

For Example:

The path looks like **ethereum/assets/0x0a7e91c185B6fA2B795bDc739F2269257Fd24De8/metadata.json**

The metadata's content looks like [this](https://github.com/consenlabs/token-profile/blob/master/erc20/0x0a7e91c185B6fA2B795bDc739F2269257Fd24De8.json)

**Comment by kolya182** [comment]
Good idea, will help defiantly. Let me build script to fetch info from their repo and combine with our.

**Comment by kolya182** [comment]
@TamirTian  Do you use `assets` repo info somewhere ?

**Comment by TamirTian** [comment]
yeah, I used assets-repo(old repo) and token-profile(repo) on my website [SpiderDEX](url)

**Comment by TamirTian** [comment]
The content will be used for new version of website
@kolya182

**Comment by kolya182** [comment]
@TamirTian What tother resource besides https://etherscamdb.info/  and https://github.com/MyEtherWallet/ethereum-lists we could use to put a comprehensive list of assets info ?

**Comment by TamirTian** [comment]
The Etherscan have a comprehensive of lists. [https://etherscan.io/token/{token-address}](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7).

And we can provide and export the comprehensive list of ERC721/ERC1155 assets if you need them.
@kolya182

**Comment by TamirTian** [comment]
Also the on-chainn have a basic info

**Comment by TamirTian** [comment]
https://eips.ethereum.org/EIPS/eip-20
![image](https://user-images.githubusercontent.com/20901836/68651828-2e9a8080-0563-11ea-8a73-3c68d88f2085.png)

**Comment by kolya182** [comment]
> The Etherscan has a comprehensive of lists. [https://etherscan.io/token/{token-address}](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7).
> 
> And we can provide and export the comprehensive list of ERC721/ERC1155 assets if you need them.
> @kolya182
We pull erc721,erc1155 from opensea https://github.com/trustwallet/assets/blob/master/script/opesea_contrats.ts is your list different ?

**Comment by TamirTian** [comment]
**SpiderDEX** and **OpenSea**  should be the same, the data-source form the on-chain and thrid.
We added multilingual metadata

**Comment by vikmeup** [comment]
We have ability to set information about the token: https://github.com/trustwallet/assets/blob/master/blockchains/bitcoin/info/info.json, this is for fungible tokens. No plans to support ERC721 at this point as OpenSea provides that information

**Comment by TamirTian** [comment]
@vikmeup https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets
but the ERC20 doesn't contain metadata

**Comment by TamirTian** [comment]
like this https://github.com/consenlabs/token-profile/blob/master/erc20/0x0a7e91c185B6fA2B795bDc739F2269257Fd24De8.json
