### ISSUE TITLE
Membrana ( MBN)  token price displaying and Price updating isn't avaliable on both iOS and Android apps

### ISSUE THREAD

**Issue by ivanin-illia** [trustwallet/assets#598]
## MBN( membrana.io) token price and price change displaying?
Hey.
Could you please help me to understand and find the way of why the token price and token price change doesn't show up in trust wallet?
membrana.io
MBN token ( erc20)

**Comment by kolya182** [comment]
Price has been added.
![Uploading Screenshot_1573460216.png…]()
