### ISSUE TITLE
Token is no longer on TRUST's asset list

### ISSUE THREAD

**Issue by baahapp** [trustwallet/assets#6024]
Hello, greetings!
Contract Token Number: 0x1600c5502e7e94cacf73c124331cfa3e20add40e
It disappeared from the TRUST list, it turns out that we are now having difficulties with our partners holding the Token since they are all familiar with using the Token and locating by the way of typing the name of the Token, why was our Token removed without any justification? Does TRUST's portfolio have any BUGs? Please review the case of our contract Token asset: 0x1600c5502e7e94cacf73c124331cfa3e20add40e
Because we have been at TRUST for 2 years and disappearing from there has not been good for the project and for the reputation of this renowned asset custody platform.
I am waiting for some help. Thanks

**Comment by aboody8007** [comment]
> Hello, greetings!
> 
> Contract Token Number: 0x1600c5502e7e94cacf73c124331cfa3e20add40e
> 
> It disappeared from the TRUST list, it turns out that we are now having difficulties with our partners holding the Token since they are all familiar with using the Token and locating by the way of typing the name of the Token, why was our Token removed without any justification? Does TRUST's portfolio have any BUGs? Please review the case of our contract Token asset: 0x1600c5502e7e94cacf73c124331cfa3e20add40e
> 
> Because we have been at TRUST for 2 years and disappearing from there has not been good for the project and for the reputation of this renowned asset custody platform.
> 
> I am waiting for some help. Thanks

**Comment by catenocrypt** [comment]
I see that this token was set to 'abandoned' during a recent check.  Circulation is quite low, 214 holders, 392 total transactions.
Please provide arguments for activating again.

**Comment by baahapp** [comment]
Hello, see in our explorer that we are making constant movements even on the last day. The Token in question does not have such a high movement because it is a Token of real estate participation assets with a reserved and active public. However, in this new phase that we are implementing in the project that is the asset, it will be accepted in the project's marketplace and its partners, this will undoubtedly generate many operations at TRUST and many customers.

But I confess that as a project developer I was taken by surprise and our client owner of the project also caught by surprise, I ask for your help so that we can resume where we were at TRUST so that we can be happy and our dententores of assets also because the people who use our asset has some difficulty with the internet, that is, the way it was listed was doing well and calm now people are lost in the process of implementing the manual code. I have always been a member of the TRUST telegram group from the beginning helping in the development of the TRUST project as much as possible, please help this colleague to keep the token listed as it was before so that we can continue to move forward with our project and reach out to others levels.

I look forward to your consideration on the matter.

**Comment by aboody8007** [comment]
bnb136ns6lfw4zs5hg4n85vdthaad7hq5m4gtkgf23 

My money was withdrawn from this wallet and I could not access it, and I was only banned for viewing and not spending any money I have and I have withdrawals documented with pictures, time and day

**Comment by catenocrypt** [comment]
Please provide the website for this project/token, so we can check (RCO, 0x1600C5502E7e94CaCf73C124331cfa3e20ADd40e).

**Comment by baahapp** [comment]
Hello, of course!

The website is www.ricoin.app

Even the token is implementing its own wallet in offchain and blockchain in the coming days. But we would very much like to keep our currency as it was in TRUST as we are going to encourage people to leave TRUST to have even more control and security over their assets.

I await your help my nobleman!
