### ISSUE TITLE
Filecoin nonce too high and wallet stuck after tx failure

### ISSUE THREAD

**Issue by Keref** [trustwallet/assets#6170]
**Describe the bug**
A failed transaction a few days ago when the gas price crashed caused a transaction to be stuck. It has disappeared from the filecoin explorer but is stick in the wallet without being detected as failed. It is not possible 

**To Reproduce**
Can't reproduce the tx stuck, on some other wallet it seems it resolved itself. As nonce can't be manually set, a replacement tx can't be made

**Expected behavior**
Manually set nonce or gas price or gas limit (as all of these occasionally fail to be set properly automatically, resulting in failing transactions).

**Smartphone (please complete the following information):**
Version 1.27.18

**Comment by Keref** [comment]
Additionally, I think that this is caused by the tx nonce 0 to have too low gas price (gas went very low for a few hours before spiking up again) and being dropped from mempool, but trust wallet doesn't detect that it's been dropped and tx is stuck pending

**Comment by SAFEBTCOFFICIAL** [comment]
Has this issue been sorted sir

Also how can we get price to reflect on trust?
