### ISSUE TITLE
Update Contract Address for the STASH token

### ISSUE THREAD

**Issue by bitstashco** [trustwallet/assets#6418]
Old contract address: 0x965f109d31ccb77005858defae0ebaf7b4381652

New contract address: 0xe4f356ecce6fbda81ecdea2e38527e59422861c2

Token was migrated you can verify here: https://www.coingecko.com/en/coins/bitstash-marketplace

**Comment by catenocrypt** [comment]
Need to create PR with that.  For old token, keep it there, just set `status` to `abandoned`.
