### ISSUE TITLE
We just made the payment

### ISSUE THREAD

**Issue by XSL-Labs** [trustwallet/assets#6558]
We just made the payment 
Actually we have more than  2500 token holders and more than 5000 transactions. 
You can check that here : https://bscscan.com/token/0x7e52a123ed6db6ac872a875552935fbbd2544c86

Thank you.

_Originally posted by @XSL-Labs in https://github.com/trustwallet/assets/issues/6253#issuecomment-821851907_

**Comment by XSL-Labs** [comment]
Hello, 
Did you check our payment regarding this Pull request : 6253 ?

**Comment by Cryptocool1** [comment]
hello, 

> Hello,
> Did you check our payment regarding this Pull request : 6253 ?

Hello, 
According to our rules, your SYLLogo.png needs to be renamed to logo.png

**Comment by XSL-Labs** [comment]
Hello @Cryptocool1, 
Can you reopen the PR in order to do this update ?
thanks.

**Comment by catenocrypt** [comment]
Please provide TXID so we can check.
