### ISSUE TITLE
process to remove a scam token?

### ISSUE THREAD

**Issue by rohanmc** [trustwallet/assets#6616]
I made a PR (https://github.com/trustwallet/assets/pull/6615) to remove the scam bep20 token for ecomi, but it's requesting a PR merge fee? is this something that's need to delete the token as well? can you please let me know if there's some other process to remove a fake token?

**Comment by vikmeup** [comment]
Merged: https://github.com/trustwallet/assets/pull/6615

**Comment by rohanmc** [comment]
@vikmeup thanks for merging it :)
A follow up question, if you don't mind, Is there something else that needs to be done after deleting the asset directory? i ask, because the token still shows up in trustwallet (i assumed the action with upload --delete to s3 would take care of it). is it just a matter of waiting for the changes to propagate ?

thanks

**Comment by vikmeup** [comment]
> @vikmeup thanks for merging it :)
> A follow up question, if you don't mind, Is there something else that needs to be done after deleting the asset directory? i ask, because the token still shows up in trustwallet (i assumed the action with upload --delete to s3 would take care of it). is it just a matter of waiting for the changes to propagate ?
> 
> thanks

Image is cached to 30 days, but it won't be available for the new users
