### ISSUE TITLE
SYL logo 

### ISSUE THREAD

**Issue by XSL-Labs** [trustwallet/assets#6770]
## How can we help ?

Hello @catenocrypt,
Can  you please check this new RP --> Add SYL logo and info #6738
                                     related to RP --> Add XSL Logo and info #6253, as requested.

<img width="914" alt="Screenshot 2021-04-23 at 11 12 10" src="https://user-images.githubusercontent.com/78526827/115849022-c83ab280-a424-11eb-8b78-6bdd5008b304.png">

**Comment by Cryptocool1** [comment]
Hello, your changes are ok. You can pay fee now

**Comment by XSL-Labs** [comment]
Hello @Cryptocool1,
The Fee was paid on the RP( #6738) as i said, i don't understand are you reading my message ?
@catenocrypt can you  help pleas ?
