### ISSUE TITLE
Auto-close message overwrites PR description

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/assets#6888]
If a PR is auto-closed, and it had non-empty description, the closing message overrides the description.
Not a big deal, a little annoying only when PR is reopened.

**Comment by Connecteq** [comment]
Can you please tell us if our logo will be added. We have been trying but we having error. Can you please provide us with the  best way to deal with this.

**Comment by ecointoken** [comment]
I can't do it, please help me!

**Comment by LasTshaMAN** [comment]
Here is an example of this behavior: https://github.com/trustwallet/assets/pull/8675

**Comment by Blacknft** [comment]
Hello everyone, how do I add my logo token.  Please who knows this?

**Comment by Blacknft** [comment]
Closed #6888.
