### ISSUE TITLE
Adding of OCTI Logo and Token information - Why does PR keep getting closed?

### ISSUE THREAD

**Issue by OCTIONOFFICIAL** [trustwallet/assets#7057]
## How can we help ?

Hi I am the project lead for OCTION, my devs have been trying to submit a pull request to merge our token information and logo onto the main branch for numerous times, sorry to ask, but why does it keep getting closed without any approvals or comments?
We have submitted a pull request for our token logo and information for coming close to 5 times already. 

#6545 
#7021 
#6874 

were all submitted by us. 

#7056 is the latest one, 

pls kindly tell us what is the issue? Our community has been asking us for the logo and token information to be added to Trustwallet.

**Comment by Cryptocool1** [comment]
Hello,
did you pay for your PR? 
The bot close all unpaid PRs after 48hours
