### ISSUE TITLE
Incostent property on `Bifrost` : `short_description`

### ISSUE THREAD

**Issue by mason-chase** [trustwallet/assets#7170]
Hi,

This property is not consistent with other assets, and it is not even short in comparison of `description`:

It is longer!

```
{
    "name": "Bifrost",
    "website": "https://thebifrost.io/",
    "source_code": "https://github.com/bifrost-platform",
    "white_paper": "https://thebifrost.io/static/Bifrost_WP_Eng.pdf",
    "short_description": "Middleware platform that enables developers to create Decentralized Applications (DApps) on top of multiple protocols",
    "description": "Developers can combine the best protocols to develop substantially more scalable and flexible DApps.",
    "explorer": "https://etherscan.io/token/0x0c7D5ae016f806603CB1782bEa29AC69471CAb9c",
    "type": "ERC20",
    "symbol": "BFC",
    "decimals": 18,
    "status": "active",
    "id": "0x0c7D5ae016f806603CB1782bEa29AC69471CAb9c"
}
```

Cheers
Mason

**Comment by Cryptocool1** [comment]
You can delete your short description.
 It should be of the form:
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
