### ISSUE TITLE
Bad Socials `PoolTogether`

### ISSUE THREAD

**Issue by mason-chase** [trustwallet/assets#7181]
Hi

Object is invalid again:

```
{
    "name": "PoolTogether",
    "website": "https://pooltogether.com",
    "description": "PoolTogether is the open source, decentralized primitive for no-loss prize games",
    "socials": [
        "https://twitter.com/PoolTogether_",
        "https://discord.com/invite/hxPhPDW",
        "https://medium.com/pooltogether",
        "https://github.com/pooltogether"
    ],
    "explorer": "https://etherscan.io/token/0x0cEC1A9154Ff802e7934Fc916Ed7Ca50bDE6844e",
    "type": "ERC20",
    "symbol": "POOL",
    "decimals": 18,
    "status": "active",
    "id": "0x0cEC1A9154Ff802e7934Fc916Ed7Ca50bDE6844e"
}
```

**Comment by Cryptocool1** [comment]
the form:
{
    "name": "Trust Wallet Token",
    "type": "ERC20",
    "symbol": "TWT",
    "decimals": 8,
    "description": "Utility token to increase adoption of cryptocurrency.",
    "website": "https://trustwallet.com",
    "explorer": "https://explorer.binance.org/asset/TWT-8C2",
    "status": "active",
    "id": "TWT-8C2"
}
Please follow documentation: https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

**Comment by catenocrypt** [comment]
Note: Info from `socials` section have been consolidated to new `links` section, see #10140 .
