### ISSUE TITLE
**PR Summary**

### ISSUE THREAD

**Issue by cuonght38** [trustwallet/assets#7278]
**PR Summary** 
Files in PR:  2 
Token in PR: BEP20 0xbcb24AFb019BE7E93EA9C43B7E22Bb55D5B7f45D 
Symbol: **BSCS** decimals: 18  
Links: [Logo](https://raw.githubusercontent.com/cuonght38/assets/master/blockchains/smartchain/assets/0xbcb24AFb019BE7E93EA9C43B7E22Bb55D5B7f45D/logo.png) [Info](https://raw.githubusercontent.com/cuonght38/assets/master/blockchains/smartchain/assets/0xbcb24AFb019BE7E93EA9C43B7E22Bb55D5B7f45D/info.json) [Website](https://bscstation.org/) [ExplorerFromInfo](https://bscscan.com/address/0xbcb24afb019be7e93ea9c43b7e22bb55d5b7f45d) [ExplorerFromID](https://bscscan.com/token/0xbcb24AFb019BE7E93EA9C43B7E22Bb55D5B7f45D) 
Token check error: 
!  No. of holders could not be checked; Could not parse number from explorer page; opening fragment not found, https://bscscan.com/address/0xbcb24afb019be7e93ea9c43b7e22bb55d5b7f45d '">' -1 41015 275250 ress for identifying
✓  Token type OK (BEP20); Contract/ID is OK; Type field OK; Symbol field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (21.457 kB); Logo dimensions OK (256x256); 
 

<span style="padding: 5px; background-color: rgb(32,32,32);"><img src="https://raw.githubusercontent.com/cuonght38/assets/master/blockchains/smartchain/assets/0xbcb24AFb019BE7E93EA9C43B7E22Bb55D5B7f45D/logo.png" style="max-width: 64px; border-radius: 48%;" width="48" height="48"/></span>

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/7277#issuecomment-831211912_

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

**Comment by cuonght38** [comment]
My token has met the requirements for updating information. But why hasn't my update request been approved yet?
https://bscscan.com/token/0xbcb24afb019be7e93ea9c43b7e22bb55d5b7f45d
Previously I added information and logo. Now I'm just asking for a new logo update.
Please resolve it and get back to me, I have completed paying the fees
