### ISSUE TITLE
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.

### ISSUE THREAD

**Issue by MichaelCS38** [trustwallet/assets#7315]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at (mentioned in the first message by the bot): https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).

_Originally posted by @Cryptocool1 in https://github.com/trustwallet/assets/issues/7278#issuecomment-831675844_

**Comment by Cryptocool1** [comment]
Hello
What problems do you have?

**Comment by MichaelCS38** [comment]
My token has met the requirements for updating information. But why hasn't
my update request been approved yet?
https://bscscan.com/token/0xbcb24afb019be7e93ea9c43b7e22bb55d5b7f45d
Previously I added information and logo. Now I'm just asking for a new logo
update.
Please resolve it and get back to me, I have completed paying the fees

Vào Th 3, 4 thg 5, 2021 vào lúc 11:47 CryptoA ***@***.***>
đã viết:

**Comment by Cryptocool1** [comment]
Sorry, fixed it. 
have a great day!

**Comment by MichaelCS38** [comment]
why i haven't seen it updated on trust wallet
