### ISSUE TITLE
Incorrect Pricing Since Token Swap: CYFM

### ISSUE THREAD

**Issue by CyberFM** [trustwallet/assets#737]
## How can we help ?

CyberFM (CYFM) performed a token swap a short while back. 

Trust Wallet shows the pricing for 0x3f06b5d78406cd97bdf10f5c420b241d32759c80 

However the new Contract ID for the CYFM token is: 0x32b87fb81674aa79214e51ae42d571136e29d385

In your https://github.com/trustwallet/assets/blob/master/pricing/coinmarketcap/mapping.json

You'd see: 
    {
        "coin": 60,
        "type": "token",
        "token_id": "0x3f06B5D78406cD97bdf10f5C420B241D32759c80",
        "id": 3146
    },

Is it as simple as changing it to:
    {
        "coin": 60,
        "type": "token",
        "token_id": "0x32b87fb81674aa79214e51ae42d571136e29d385",
        "id": 3146
    },

Thanks in advance.

**Comment by kolya182** [comment]
This mapping hasn't bee used yet in prod, planning next week. The reason we created this map opensource to handle cases when CMC will still returning old contract https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=YOURKEY&limit=5000

<img width="670" alt="Screen Shot 2019-12-02 at 5 58 20 PM" src="https://user-images.githubusercontent.com/3277207/70013697-53b05c80-152d-11ea-9a2a-02360cd01a45.png">

Changed to new contract, price should be available in couple minutes.

Where i can read a news about contract swap ?. This is will be once of the criteria to provide when updating contract address.

**Comment by hottweelz** [comment]
Great Question, so in terms of ERC20 Swaps, I wouldn't necessarily "rely on a news article" although we did write one and it's kinda awesome if I do say so myself: https://medium.com/@doyoumftu/the-cyfm-swap-contract-upgrade-11a9be639288

I would honestly suggest using ETHERSCAN to validate the contract swaps (anyone can write a news article).

https://etherscan.io/token/0x3f06b5d78406cd97bdf10f5c420b241d32759c80

If you look carefully on the above etherscan link, (for our OLD CYFM Token) You'll see a grey bar that is titled " Token migration announcement. CYBERFM token contract has migrated to a new address." with a direct link to the NEW CYFM Token.  This in my opinion would be the most "validated" and "Legit" way to authenticate.

Hope this helps and thanks again!
