### ISSUE TITLE
DOGEFATHER

### ISSUE THREAD

**Issue by TrimeGeld** [trustwallet/assets#7552]
## How can we help ?

What is that ?

![Bildschirmfoto 2021-05-08 um 11 11 06](https://user-images.githubusercontent.com/78798836/117536342-cc58f980-affa-11eb-878e-5085bfdebc9d.png)

why can not how much $ have I ?

**Comment by Cryptocool1** [comment]
hello,
can you see it right now?

**Comment by catenocrypt** [comment]
https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596
