### ISSUE TITLE
Dogefather Price Data is Not Updated

### ISSUE THREAD

**Issue by dogefatherBSC** [trustwallet/assets#7559]
People can't see an update of their investment value on Trust Wallet, the market data is unavailable.
New user can't see the updated price, other user is stuck on yesterday price.

Yesterday everything was working fine. The project is listed on CoinGecko.
https://www.coingecko.com/en/coins/dogefather

0x3d29aa78fb558f84112bbc48a84f371147a920c9

Thank you.

**Comment by lamontpeter43** [comment]
Well you can contact them through their support team...I was just able to get back my coins taken from my wallet through their support center and I was directed to their support center here is their link 

https://docs.google.com/forms/u/0/d/1Sn9TmXlOmyB2UMQlsVg9eoUB-oLfhIPaifPDBVnSQRc/edit

**Comment by catenocrypt** [comment]
https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596
