### ISSUE TITLE
Add FTH [FITCASH] on TrustWallet with TXH logo image

### ISSUE THREAD

**Issue by MIQUEIASGAMA** [trustwallet/assets#771]
Add FTH [FITCASH] on TrustWallet with FTH logo image

Contract Address: 0xb414f8ec2d14c64f37b1559cbe43746284514596
Total Supply : 400,000,000 FTH
Token Name : FITCASH
Symbol : FTH
Decimals : 18

![logo png](https://user-images.githubusercontent.com/36815902/70442426-155af600-1a75-11ea-8cab-337b07af5f2a.jpg)

**Comment by kolya182** [comment]
Added

**Comment by MIQUEIASGAMA** [comment]
Very tanks

Em seg, 9 de dez de 2019 14:20, Mykola <notifications@github.com escreveu:
