### ISSUE TITLE
Add EDUC [educca ] on TrustWallet with logo 

### ISSUE THREAD

**Issue by Educca** [trustwallet/assets#790]
Add EDUC [educca ] on TrustWallet with logo 
Token Name	: educca 
Total Supply	: 30,000,000 EDUC
Symbol		: EDUC
Decimals	: 18
Contract Address: 0x4e4f2cf7c828e277b9a997261165fa7074ec66bf
![logo](https://user-images.githubusercontent.com/58003952/70647951-15731580-1c70-11ea-908a-1cbbfb675662.png)

**Comment by kolya182** [comment]
Added
