### ISSUE TITLE
Price not showing in TW after PR merged into assets

### ISSUE THREAD

**Issue by spacecorgi-official** [trustwallet/assets#7902]
## How can we help ?
Our PR was merged into master here: https://github.com/trustwallet/assets/pull/7748

However, the price does not show in TW. The token is on [CMC](https://coinmarketcap.com/currencies/spacecorgi/) and [CG](https://www.coingecko.com/en/coins/spacecorgi).

Is there anything else we need to do to get the price up?

**Comment by Cryptocool1** [comment]
Hello,
can you see the price now?

**Comment by catenocrypt** [comment]
https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596
