### ISSUE TITLE
Ethereum assets are incorrect case - format is unclear

### ISSUE THREAD

**Issue by bgits** [trustwallet/assets#799]
**Describe the bug**
The case of the Ethereum address assets are incorrect.

**To Reproduce**
1. Go to https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f
2. check address and compare to https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x6B175474E89094C44Da98b954EedeAC495271d0F/logo.png

It's not clear what case formating this repo is using

**Expected behavior**
Case should either match standard or be all lowercase or uppercased.

**Comment by kolya182** [comment]
It is very clear when you read https://github.com/trustwallet/assets#what-changed
