### ISSUE TITLE
why you charge money and then delete the file we submitted? 

### ISSUE THREAD

**Issue by vm06007** [trustwallet/assets#8003]
## How can we help ?
https://github.com/trustwallet/assets/pull/7991 check this request <-- your staff deleted the file we submit and suggest the token address is different!

the correct token address is 0x66... so please refund/revert or restore the correct.json file that your staff deleted for some reason!!!

**Comment by coffee-converter** [comment]
Agreed...maintainers please correct this issue!  We pay more than reasonable fees for these merges.
