### ISSUE TITLE
Price error bug on certain tokens listed.

### ISSUE THREAD

**Issue by xeraphislord** [trustwallet/assets#8086]
**Describe the bug**
Tokens "Rocket Bunny" "Shih Tzu" "Vether" "Hungry Bear" has a bug that won't properly update pricing and chart.

**To Reproduce**
This is for the ones who manages the description of the tokens on here.

**Expected behavior**
This issue to be fixed by coders ASAP!

**Screenshots**
N/A

**Desktop (please complete the following information):**
 Not necessary

**Smartphone (please complete the following information):**
 Not necessary

**Additional context**
N/A

**Comment by spacecorgi-official** [comment]
Our token "SpaceCorgi" (SCORGI) is also not showing price despite being merged to master several days ago.

**Comment by catenocrypt** [comment]
https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596
