### ISSUE TITLE
TXL showing old logo even though PR has been merged

### ISSUE THREAD

**Issue by seb0zz** [trustwallet/assets#8183]
**Describe the bug**
App is showing the old logo for TXL even after a successful merge of the [new logo PR](https://github.com/trustwallet/assets/pull/5694).

**To Reproduce**
1. Go to 'Receive'
2. Search for 'TXL'
3. See the old logo

**Expected behavior**
The new logo should show up.

**Screenshots**
![IMG_3253](https://user-images.githubusercontent.com/1436535/118409342-4be56900-b68a-11eb-9ca1-eda5f06808ad.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 14.4.2
 - Version: 5.25

**Comment by catenocrypt** [comment]
I checked now, the updated logo is shown.

**Comment by seb0zz** [comment]
@catenocrypt that's strange. It seems that for users who added the coin before the logo change, they can't see the new one. Is there a way to purge the caches?
