### ISSUE TITLE
PR 8237, requesting reopen. Closed by merge-fee-bot while payment was confirming.

### ISSUE THREAD

**Issue by agent725** [trustwallet/assets#8400]
During the time we sent payment, merge-fee-bot has closed our pull request. Please assist, thank you!

---

This PR is being closed due to inactivity. If you wish to continue, please have us reopen the PR before sending your payment, or just create a new one.
Do NOT send payments for closed PR, as the fee may by lost!
  (48 vs. 48 hrs)

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/8237#issuecomment-843989891_

**Comment by agent725** [comment]
Transaction ID: CF27C799D0BCE35B3B72A930B373203DA3F578436BDDB74A0E1082F34BADA72D

**Comment by Cryptocool1** [comment]
merged
