### ISSUE TITLE
Add USC [ upscaleeth ] on TrustWallet

### ISSUE THREAD

**Issue by upscaleeth** [trustwallet/assets#848]
Add USC [ upscaleeth ] on TrustWallet
TOKEN NAME : upscaleeth 
TOKEN SYMBOL : USC
TOKEN SUPPLY : 10,000,000,000 USC
TOKEN CONTRACT ADDRESS : 0x01522e6c543ff04e74842abd0f2afecc5ef5c281
![0x01522e6c543ff04e74842abd0f2afecc5ef5c281](https://user-images.githubusercontent.com/58970386/70981592-71f48b80-20db-11ea-88a8-d4de54a8c053.png)

**Comment by kolya182** [comment]
https://github.com/trustwallet/assets/commit/b43dc0d9cc3e123092dc27ab33421dccc688f46a
