### ISSUE TITLE
Add JNN [ JeyennCoin ] on TrustWallet 

### ISSUE THREAD

**Issue by coinxpo** [trustwallet/assets#858]
Add JNN [ JeyennCoin ] on TrustWallet

Contract Address: 0x36bf67c9aa1d67a06bfec145f08e20112a54c0f7
Token Name - JeyennCoin
Ticker- JNN
Supply token- 100,000,000,000 JNN
Decimal- 18

![0x36bf67c9aa1d67a06bfec145f08e20112a54c0f7](https://user-images.githubusercontent.com/58912128/71025195-8d3bb700-212c-11ea-9915-ddd096c36da7.png)

**Comment by kolya182** [comment]
https://github.com/trustwallet/assets/commit/3dfaa36325711e7a1d722fae725872156744e9f3
