### ISSUE TITLE
Payment #7157

### ISSUE THREAD

**Issue by HackerSpaceToken** [trustwallet/assets#8605]
Good morning I would like to know if I pay the 2 BNB I will not need to have the 2500 holds?

**Comment by HackerSpaceToken** [comment]
I have this doubt because we are wanting a lot for our logo, but we didn’t reach the holdings,
and we don’t know if paying these 2 BNB fees we’ll be able to get the logo

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.

**Comment by Cryptocool1** [comment]
You need to pay 2 BNB or 250 TWT even if you have 2500 holder addresses and 5000 transactions

**Comment by HackerSpaceToken** [comment]
I understood :( now that we got the 2 BNB I was thinking that paying the BNB would work but ok thanks!
