### ISSUE TITLE
Trust wallet policy on token acceptance 

### ISSUE THREAD

**Issue by ArtjomProzorov** [trustwallet/assets#8767]
Hello guys,

I am just a community member and i saw that PR declined for Signata $SATA due to the fact that the holder quantity isn't 2500. @Cryptocool1 mentioned that this is done to filter scam, so my questions is how do you judge a token is a scam or not by the amount of holders holding that token?

So there is no audit check from your end on the actual contract code and no check if liquidity locked or no , so why the hell the team who is legit and public + is done by the IT company who is official registered in Australian registry cannot pass just because of the amount of people holding it ? Please explain your logic here because its truly not the way it should be   , you should have different ways to pass by this verification and it definitely should not be the quantity of holders ! 

![image](https://user-images.githubusercontent.com/43901335/119694322-cfa31080-be55-11eb-9917-3635a69234d4.png)

**Comment by ArtjomProzorov** [comment]
??

**Comment by ArtjomProzorov** [comment]
will anyone take time answering this please

**Comment by Cryptocool1** [comment]
sorry, it's our rules. Please come back to us when all criteria are met.
