### ISSUE TITLE
File not allowed: 0x8869eac0d82245a2df50a0fad770d72ce63649d1/Logo.png. Please revert it.

### ISSUE THREAD

**Issue by Doggyswapio** [trustwallet/assets#8773]
File not allowed: 0x8869eac0d82245a2df50a0fad770d72ce63649d1/Logo.png. Please revert it. 
File not allowed: 0x8869eac0d82245a2df50a0fad770d72ce63649d1/info.json. Please revert it.

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/8772#issuecomment-849023277_

**Comment by Doggyswapio** [comment]
why file not allow

**Comment by Cryptocool1** [comment]
hello,
This is a BEP20 token, correct folder is blockchains/smartchain/assets. 
Logo file should be named logo.png
