### ISSUE TITLE
**PR Summary**

### ISSUE THREAD

**Issue by gtrole** [trustwallet/assets#8831]
**PR Summary** 
Files in PR:  2 
Token in PR: BEP20 0xb813939458aA42ca57B870bEf4bEc24945aDDA6D 
Symbol: **MONKI** decimals: 18  
Links: [Logo](https://raw.githubusercontent.com/gtrole/assets/br0525-133638/blockchains/smartchain/assets/0xb813939458aA42ca57B870bEf4bEc24945aDDA6D/logo.png) [Info](https://raw.githubusercontent.com/gtrole/assets/br0525-133638/blockchains/smartchain/assets/0xb813939458aA42ca57B870bEf4bEc24945aDDA6D/info.json) [Website](https://www.monki.network) [Explorer](https://bscscan.com/token/0xb813939458aA42ca57B870bEf4bEc24945aDDA6D) 
Token check error: 
!  Symbol possibly has wrong casing, expected 'MONKI' instead of 'monki', please cross-check with explorer page.
✓  Token type OK (BEP20); Contract/ID is OK; Type field OK; Decimals field OK; Description field OK; Website field OK; Explorer field OK; Status field OK; Id field OK; Logo image type is OK (image/png); Logo image size is OK (76.574 kB); Logo dimensions OK (509x509); Token circulation OK (no. of holders: 10584); 
 

<span style="padding: 5px; background-color: rgb(32,32,32);"><img src="https://raw.githubusercontent.com/gtrole/assets/br0525-133638/blockchains/smartchain/assets/0xb813939458aA42ca57B870bEf4bEc24945aDDA6D/logo.png" style="max-width: 64px; border-radius: 48%;" width="48" height="48"/></span>

_Originally posted by @merge-fee-bot[bot] in https://github.com/trustwallet/assets/issues/8670#issuecomment-847548920_

**Comment by Cryptocool1** [comment]
This PR closed due to inactivity.

**Comment by gtrole** [comment]
Do we need to submit the materials again?

**Comment by Cryptocool1** [comment]
> Do we need to submit the materials again?
I can reopen PR.

**Comment by gtrole** [comment]
I realized that I had written MONKI as MONKI, which was wrong

**Comment by gtrole** [comment]
Open PR. Is it OK if I pay within 48 hours

**Comment by gtrole** [comment]
Hello, did I do the right thing?

**Comment by gtrole** [comment]
pay fee: 250 TWT with the memo 8670 to the address bnb1tqq9llyr3dyjd559dha6z5r5etk3qfwk07m098.
That's it, right?I need to get a positive answer. Thank you for your help

**Comment by gtrole** [comment]
I have to resubmit it
