### ISSUE TITLE
Add logo for SST

### ISSUE THREAD

**Issue by daniilmolch** [trustwallet/assets#8929]
Hello! We have fulfilled your conditions: 500 holders and 2000+ transactions, can you add a logo to our SST token? https://etherscan.io/token/0x2863916C6ebDBBf0c6f02F87b7eB478509299868

_Originally posted by @daniilmolch in https://github.com/trustwallet/assets/issues/4396#issuecomment-850835761_

**Comment by Cryptocool1** [comment]
As per our policy, brand new tokens are not included, there is a minimum requirement of 2500 holder addresses and 5000 transactions, in order to filter out scam tokens.
See the criteria at : https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863).
