### ISSUE TITLE
Could you please reopen the PR, fee was sent

### ISSUE THREAD

**Issue by vovanushka** [trustwallet/assets#9199]
Could you please reopen the PR, fee was sent with 9038
https://explorer.binance.org/tx/765A6691E88FD1223D34B9B3672710FD2B380C47290892D65EF796FD4011898D

_Originally posted by @vovanushka in https://github.com/trustwallet/assets/issues/9038#issuecomment-853116626_

**Comment by vovanushka** [comment]
@catenocrypt

**Comment by Cryptocool1** [comment]
reopened
