### ISSUE TITLE
Token BEP20 - 0x12b6ffba41844a51a25e13065d393e54af0633df: Could not retrieve info file; dartchain/assets/master 0x12b6ffba41844a51a25e13065d393e54af0633df, HttpError: Not Found

### ISSUE THREAD

**Issue by dartchain** [trustwallet/assets#9216]
Token BEP20 - 0x12b6ffba41844a51a25e13065d393e54af0633df:
Could not retrieve info file; dartchain/assets/master 0x12b6ffba41844a51a25e13065d393e54af0633df, HttpError: Not Found

how can i solve this error?

**Comment by Cryptocool1** [comment]
fixed
