### ISSUE TITLE
Add EVCO [ EVCOIN ] on TrustWallet

### ISSUE THREAD

**Issue by coinxpo** [trustwallet/assets#924]
Add EVCO [ EVCOIN ] on TrustWallet

Contract Address: 0xaa5c28be0f1173612ea3fcc9e461ccb7b9390213
Token Name - EVCOIN 
Ticker- EVCO 
Supply token- 400,000,000 EVCO
Decimal- 18

![0xaa5c28be0f1173612ea3fcc9e461ccb7b9390213](https://user-images.githubusercontent.com/58912128/71552727-34232b80-2a28-11ea-8d6b-cf4d3a2659c3.png)

**Comment by kolya182** [comment]
Added

**Comment by coinxpo** [comment]
thank you sir

**Comment by coinxpo** [comment]
don't see ,show old logo sir 
please sir Update logo EVCO [ EVCOIN ] on TrustWallet

Contract Address: 0xaa5c28be0f1173612ea3fcc9e461ccb7b9390213
Token Name - EVCOIN
Ticker- EVCO
Supply token- 400,000,000 EVCO
Decimal- 18

![0xaa5c28be0f1173612ea3fcc9e461ccb7b9390213](https://user-images.githubusercontent.com/58912128/71584298-0927fd00-2b38-11ea-9185-bba2e7221e26.png)
