### ISSUE TITLE
Old asset icons cached forever

### ISSUE THREAD

**Issue by seb0zz** [trustwallet/assets#9346]
**Describe the bug**
If an asset is added with an icon and that icon is changed, the app will not reflect the change. Only after a full reinstallation, the image will be updated.

**To Reproduce**
1. Add an asset with an icon.
2. Check the asset and icon in the app, see that it's correct.
3. Update the asset icon.
4. Check the asset and icon in the app, see the old one.
5. Reinstall the app, see the new one.

**Expected behavior**
I would expected the cache to be busted.

**Smartphone (please complete the following information):**
 - OS: iOS
 - Browser: Mobile App
 - Version: Newest but also older versions

**Comment by vikmeup** [comment]
It's cached for 30 days on the client

**Comment by seb0zz** [comment]
@vikmeup I can reproduce the issue even after 30 days.
