### ISSUE TITLE
@Cryptocool1 do you know how long is going to take to the logo to be updated?

### ISSUE THREAD

**Issue by spikeleetendieswap** [trustwallet/assets#9360]
@Cryptocool1 do you know how long is going to take to the logo to be updated?

For some reason the old one hasn't been updated

_Originally posted by @spikeleetendieswap in https://github.com/trustwallet/assets/issues/9339#issuecomment-854769002_

**Comment by Cryptocool1** [comment]
hello,
https://community.trustwallet.com/t/why-is-there-no-token-logo-or-price/138596
