### ISSUE TITLE
uploading asset files(info.json and logo.png) to trustwallet asset location

### ISSUE THREAD

**Issue by myquery** [trustwallet/assets#9362]
## How can we help ?
i followed the community guide https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863 to add doggyInu($DOGI) logo
to trustwallet repository but the option of dragging and dropping the asset files on the asset location is not triggering the event to accept the files. i would appreciate if a CLI option exist to upload the assets files so that doggyInu logo application can commence

**Comment by Cryptocool1** [comment]
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.
