### ISSUE TITLE
Remove Listed Token

### ISSUE THREAD

**Issue by cbucks** [trustwallet/assets#944]
## How can we help ?

I removed the assets logo of our previous token.

But it did not remove the listing of our previous token.

How can I completely remove our previous listed tokens?

We need this because our token holders are confused.

Please help me address this issue. Thank you.

**Comment by kolya182** [comment]
https://github.com/trustwallet/assets#why-do-i-still-see-old-logo-in-trust-wallet-after-uploaded-new-one

**Comment by kolya182** [comment]
Search results will be updated in 15-30 minutes

**Comment by cbucks** [comment]
Okay thank you for accommodating.
