### ISSUE TITLE
MCM is not a BEP20 token, PR 9696

### ISSUE THREAD

**Issue by sputniky** [trustwallet/assets#9700]
Comment on PR 9696 was:
This is a BEp20 token, correct folder is blockchains/smartchain/assets.
Please create new PR, follow doc https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863
You may want to try our new Assets app in beta; go to https://assets.trustwallet.com, log on with Github, enter contract ID, logo and some additional info, and it will create a PR for you.
See https://community.trustwallet.com/t/how-to-submit-a-token-logo-using-assets-app/82957.

_Originally posted by @Cryptocool1 in https://github.com/trustwallet/assets/issues/9696#issuecomment-857002164_

But this is wrong, MCM is not a BEP20 token. It is no token at all from no base chain as it is a fully original blockchain, so just a coin like bitcoin. More info: mochimo.org.
Hence is it possible to add it at this location?

**Comment by sputniky** [comment]
I think I understood what happens: probably you mixed up mochiswap with mochimo. Mochiswap (MOCHI) is a BEP-20 token as you say, and we can find it here: https://coinmarketcap.com/currencies/mochiswap/
However this is not the same coin as Mochimo (MCM), which is a completely different and original blockchain, with a specific block explorer and with quantum-resistant functionality.
You can find this coin here: https://coinmarketcap.com/currencies/mochimo/

The fact that the price is about the same is a complete chance, it has nothing to do with it, really.

So is it possible to add Mochimo (MCM) to the location I posted in the PR please?

**Comment by Cryptocool1** [comment]
please create new PR
