### ISSUE TITLE
The logo not look right

### ISSUE THREAD

**Issue by safeenergyx** [trustwallet/assets#9765]
can we change the logo? it doesn't look right in the wallet, it's crooked?

_Originally posted by @safeenergyx in https://github.com/trustwallet/assets/issues/9762#issuecomment-858107513_

**Comment by safeenergyx** [comment]
![logo](https://user-images.githubusercontent.com/85645712/121431010-87214200-c981-11eb-883f-3edbc2da375b.png)

**Comment by Cryptocool1** [comment]
you can create new PR
